// Face positions for any crop (8 Oct 2026). hero-focus.mjs bakes two fixed
// crops (one desktop window, one phone window); sheets, drawers and panels
// show the same photos through many other window shapes, and a fixed
// percentage chosen for one shape can land on the chest in another
// (Chandu: "the face detection is not working on the pop up sheets on
// tablet... I just got cleavage"). This writes each photo's own numbers so
// FacePhoto can place the face for whatever box it is in:
//   [image aspect (w/h), face centre x, face top, face centre y], fractions
//   from the top-left; photos with no face but a person use the person's top.
//
// Usage (macOS, from the repo root):
//   swiftc -O -o /tmp/faces scripts/career-photos/faces.swift
//   find public/images/app -type f \( -name '*.webp' -o -name '*.jpg' -o -name '*.png' \) > /tmp/photos.txt
//   /tmp/faces "$PWD" /tmp/photos.txt > /tmp/faces.tsv
//   node scripts/career-photos/face-data.mjs /tmp/faces.tsv

import { readFileSync, writeFileSync } from "node:fs";

const r3 = (n) => Math.round(n * 1000) / 1000;
const rows = readFileSync(process.argv[2], "utf8").split("\n").filter((l) => l.includes("\t")).map((line) => {
  const [rel, size, F, H] = line.split("\t");
  if (!size || size === "LOADFAIL") return null;
  const [w, h] = size.split("x").map(Number);
  const faces = (F || "").replace(/^F:/, "").split("|").filter(Boolean).map((s) => s.split(",").map(Number))
    .filter((f) => f[4] >= 0.5).sort((a, b) => b[3] - a[3]);
  const humans = (H || "").replace(/^H:/, "").split("|").filter(Boolean).map((s) => s.split(",").map(Number));
  let cx = 0.5, top, cy;
  if (faces.length) { const [x, t, b] = faces[0]; cx = x; top = t; cy = (t + b) / 2; }
  else if (humans.length) { top = Math.min(...humans.map((x) => x[0])); cy = top + 0.07; }
  else return null;
  return [rel.replace(/^public/, ""), [r3(w / h), r3(cx), r3(top), r3(cy)]];
}).filter(Boolean).sort(([a], [b]) => a.localeCompare(b));

const body = rows.map(([p, v]) => `  ${JSON.stringify(p)}: [${v.join(", ")}],`).join("\n");
writeFileSync("src/components/career/faceData.ts", `// Face position per photo, for crops of any shape (FacePhoto). Generated by
// scripts/career-photos/face-data.mjs from Apple Vision face detection
// (scripts/career-photos/faces.swift). Do not hand-edit; re-run the script.
// [image aspect (w/h), face centre x, face top, face centre y], fractions
// of the image from its top-left.

export const FACE_DATA: Record<string, readonly [number, number, number, number]> = {
${body}
};
`);
console.log(`${rows.length} photos with a face or a person`);
