// Career Detail header crops from face detection (4 Oct 2026).
//
// The header shows a portrait poster through a wide window (desktop panel
// about 487x370, phone about 333x359 with the title over the bottom), so
// only part of the photo's height is visible and a fixed crop cut heads
// off. This places each photo so the main face's centre sits at TARGET of
// the window height, keeping the top of the head in frame, separately for
// desktop and phone, and writes src/components/career/heroFocus.ts.
//
// Usage (macOS, from the repo root):
//   swiftc -O -o /tmp/faces scripts/career-photos/faces.swift
//   find public/images/app -name '*.webp' > /tmp/photos.txt
//   /tmp/faces "$PWD" /tmp/photos.txt > /tmp/faces.tsv
//   node scripts/career-photos/hero-focus.mjs /tmp/faces.tsv
// Then check the contact sheet (contact-sheet.mjs) and add any hand fixes
// to OVERRIDES below, never to the generated file.

import { readFileSync, writeFileSync } from "node:fs";

const WINDOWS = { desktop: 487 / 370, mobile: 333 / 359 };
const TARGET = { desktop: 0.36, mobile: 0.3 };
const CROWN = 0.06; // space kept above the face box, as a share of the window

// Hand fixes after looking at every header, keyed by photo path:
// { desktop: "50% 20%", mobile: "50% 10%" }.
export const OVERRIDES = {};

function focus(line) {
  const [rel, size, F, H] = line.split("\t");
  const [w, h] = size.split("x").map(Number);
  const faces = (F || "").replace(/^F:/, "").split("|").filter(Boolean).map((s) => s.split(",").map(Number))
    .filter((f) => f[4] >= 0.5).sort((a, b) => b[3] - a[3]);
  const humans = (H || "").replace(/^H:/, "").split("|").filter(Boolean).map((s) => s.split(",").map(Number));
  let cy, top;
  if (faces.length) { const [, t, b] = faces[0]; top = t; cy = (t + b) / 2; }
  else if (humans.length) { top = Math.min(...humans.map((x) => x[0])); cy = top + 0.07; }
  else return null;
  const out = {};
  for (const k of Object.keys(WINDOWS)) {
    const f = Math.min(1, (w / h) / WINDOWS[k]);
    if (f >= 1) { out[k] = "50% 50%"; continue; }
    let p = (cy - TARGET[k] * f) / (1 - f);
    p = Math.min(p, (top - CROWN * f) / (1 - f));
    p = Math.max(0, Math.min(1, p));
    out[k] = `50% ${Math.round(p * 100)}%`;
  }
  return { path: rel.replace(/^public/, ""), ...out };
}

const rows = readFileSync(process.argv[2], "utf8").split("\n").filter((l) => l.includes("\t")).map(focus).filter(Boolean);
const map = Object.fromEntries(rows.map((r) => [r.path, { desktop: r.desktop, mobile: r.mobile }]));
Object.assign(map, OVERRIDES);
const body = Object.entries(map).sort(([a], [b]) => a.localeCompare(b)).map(([p, v]) => `  ${JSON.stringify(p)}: { desktop: ${JSON.stringify(v.desktop)}, mobile: ${JSON.stringify(v.mobile)} },`).join("\n");
writeFileSync("src/components/career/heroFocus.ts", `// Career Detail header crop per photo (object-position), so the subject's
// head is in view on desktop and on phones. Generated by
// scripts/career-photos/hero-focus.mjs from Apple Vision face detection
// (scripts/career-photos/faces.swift); see scripts/career-photos/README.md.
// Do not hand-edit: add fixes to OVERRIDES in hero-focus.mjs and re-run.

export const HERO_FOCUS_BY_PHOTO: Record<string, { desktop: string; mobile: string }> = {
${body}
};

export function heroFocus(photo: string): { desktop: string; mobile: string } | undefined {
  return HERO_FOCUS_BY_PHOTO[photo];
}
`);
console.log(`${rows.length} photos with a face or person; written src/components/career/heroFocus.ts`);
