// The reference caseload, verbatim: all 120 rows of the Replit reference's
// Students table (web-app-prototype-maishak.replit.app/students), captured
// 24 Sept 2026 so v1 of the Counselor Dashboard matches the reference 1:1 in
// content, not just structure (direct instruction: "make sure the contents
// of cards match the replit 1:1 in v1"). Column order per row:
//   name, grade, careerTrack, roadmapPct, status,
//   Career Report, Resume, Applications, Rec. Letter, Transcript,
//   postsecondaryIntent, lastActive
// "—" is the reference's own marker for a milestone that doesn't apply yet.
// Dates are the reference's; do not relabel them.

export type ReferenceRow = [
  name: string,
  grade: number,
  careerTrack: string,
  roadmapPct: number,
  status: string,
  careerReport: string,
  resume: string,
  applications: string,
  recLetter: string,
  transcript: string,
  postsecondaryIntent: string,
  lastActive: string,
];

export const REFERENCE_ROSTER: ReferenceRow[] = [
  ["Emma Rodriguez", 12, "Technology", 92, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Marcus Thompson", 11, "Healthcare", 78, "On Track", "Approved", "Pending Review", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Aisha Patel", 10, "Finance & Business", 65, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Diego Martinez", 12, "Skilled Trades", 85, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Trade/Technical School", "2024-01-13"],
  ["Olivia Chen", 11, "Arts & Media", 55, "Needs Attention", "Changes Requested", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-12"],
  ["Jamal Washington", 9, "Technology", 42, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Sophia Kim", 12, "Education", 88, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Liam O'Connor", 10, "Law & Government", 58, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Isabella Santos", 11, "Healthcare", 48, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-10"],
  ["Noah Anderson", 9, "Skilled Trades", 38, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Mia Johnson", 12, "Technology", 95, "On Track", "Approved", "Approved", "Completed", "Completed", "Completed", "4-Year College", "2024-01-15"],
  ["Ethan Garcia", 11, "Finance & Business", 72, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Ava Brown", 10, "Healthcare", 62, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Lucas Miller", 9, "Arts & Media", 35, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Charlotte Davis", 12, "Law & Government", 32, "At Risk", "Approved", "Not Started", "Not Started", "Not Started", "Not Started", "Undecided", "2024-01-08"],
  ["Mason Wilson", 11, "Technology", 81, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Amelia Moore", 10, "Education", 68, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Elijah Taylor", 12, "Skilled Trades", 89, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Trade/Technical School", "2024-01-14"],
  ["Harper Anderson", 9, "Healthcare", 40, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Jackson Thomas", 11, "Finance & Business", 52, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-11"],
  ["Scarlett Jackson", 12, "Arts & Media", 76, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-13"],
  ["Benjamin White", 10, "Technology", 70, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Aria Martinez", 9, "Law & Government", 44, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Henry Rodriguez", 11, "Healthcare", 75, "On Track", "Approved", "Pending Review", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Luna Hernandez", 12, "Finance & Business", 91, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Alexander Lopez", 10, "Skilled Trades", 60, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "Trade/Technical School", "2024-01-14"],
  ["Penelope Gonzalez", 9, "Education", 36, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Sebastian Wilson", 11, "Arts & Media", 45, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-09"],
  ["Chloe Anderson", 12, "Technology", 87, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-14"],
  ["Daniel Thomas", 10, "Healthcare", 66, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Victoria Martinez", 9, "Finance & Business", 41, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Matthew Garcia", 11, "Law & Government", 69, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-13"],
  ["Sofia Rodriguez", 12, "Skilled Trades", 83, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Trade/Technical School", "2024-01-15"],
  ["Joseph Hernandez", 10, "Arts & Media", 57, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Emily Lopez", 9, "Technology", 39, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["David Gonzalez", 11, "Education", 71, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Elizabeth Wilson", 12, "Healthcare", 28, "At Risk", "Changes Requested", "Not Started", "Not Started", "Not Started", "Not Started", "Undecided", "2024-01-07"],
  ["William Anderson", 10, "Finance & Business", 63, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Evelyn Thomas", 9, "Skilled Trades", 37, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["James Taylor", 11, "Technology", 79, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Ryan Park", 9, "Technology", 45, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Hannah Nguyen", 9, "Healthcare", 52, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Tyler Brooks", 9, "Finance & Business", 38, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Naomi White", 9, "Arts & Media", 49, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-13"],
  ["Carlos Rivera", 9, "Skilled Trades", 41, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Zoe Mitchell", 9, "Education", 55, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Ahmad Hassan", 9, "Technology", 33, "Needs Attention", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-08"],
  ["Sofia Vargas", 9, "Law & Government", 48, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Marcus Lee", 9, "Technology", 43, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Priya Sharma", 9, "Healthcare", 57, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Diego Flores", 9, "Skilled Trades", 36, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-13"],
  ["Lily Thompson", 9, "Arts & Media", 50, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Jordan Hayes", 9, "Finance & Business", 44, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Maya Foster", 9, "Education", 59, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Ethan Clark", 9, "Technology", 28, "At Risk", "Overdue", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-06"],
  ["Aaliyah Davis", 9, "Healthcare", 47, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Connor Walsh", 9, "Law & Government", 42, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-15"],
  ["Fatima Al-Rashid", 9, "Education", 54, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-13"],
  ["Jake Morrison", 9, "Finance & Business", 35, "Needs Attention", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-09"],
  ["Isabelle Chen", 9, "Arts & Media", 61, "On Track", "Pending Review", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Kai Nakamura", 9, "Technology", 39, "On Track", "In Progress", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-14"],
  ["Brandon Scott", 10, "Technology", 68, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Alexis Torres", 10, "Healthcare", 72, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Darius King", 10, "Finance & Business", 58, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Samantha Cooper", 10, "Education", 75, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-13"],
  ["Noel Adams", 10, "Skilled Trades", 63, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "Trade/Technical School", "2024-01-15"],
  ["Jasmine Hill", 10, "Arts & Media", 55, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-11"],
  ["Derek Wang", 10, "Technology", 80, "On Track", "Approved", "Pending Review", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Nina Campbell", 10, "Law & Government", 65, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Owen Reed", 10, "Healthcare", 70, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Monique Barnes", 10, "Education", 48, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-09"],
  ["Caleb Nguyen", 10, "Technology", 74, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Rachel Kim", 10, "Finance & Business", 67, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Isaiah Johnson", 10, "Skilled Trades", 61, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "Trade/Technical School", "2024-01-13"],
  ["Talia Rodriguez", 10, "Healthcare", 76, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Miles Patterson", 10, "Law & Government", 52, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Grace Chen", 10, "Education", 71, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Dante Williams", 10, "Arts & Media", 42, "At Risk", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-07"],
  ["Cora Martinez", 10, "Finance & Business", 69, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Felix Hernandez", 10, "Skilled Trades", 64, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "Trade/Technical School", "2024-01-15"],
  ["Amara Jackson", 10, "Technology", 77, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-13"],
  ["Lena Patel", 10, "Healthcare", 66, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Ryan Mitchell", 11, "Technology", 83, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Alexandra Park", 11, "Healthcare", 76, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Damien Torres", 11, "Finance & Business", 68, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Keisha Brown", 11, "Education", 74, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-13"],
  ["Austin Rivera", 11, "Skilled Trades", 71, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "Trade/Technical School", "2024-01-15"],
  ["Clara Nguyen", 11, "Law & Government", 85, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Malik Washington", 11, "Arts & Media", 47, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-10"],
  ["Bianca Flores", 11, "Healthcare", 80, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Jalen Harris", 11, "Technology", 73, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Zara Ahmed", 11, "Finance & Business", 66, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Preston Kim", 11, "Technology", 88, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-13"],
  ["Lily Santos", 11, "Education", 60, "Needs Attention", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-11"],
  ["Dominic Garcia", 11, "Law & Government", 77, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Aisha Williams", 11, "Healthcare", 82, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Blake Anderson", 11, "Skilled Trades", 70, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "Trade/Technical School", "2024-01-15"],
  ["Camille Foster", 11, "Arts & Media", 36, "At Risk", "Approved", "Not Started", "Not Started", "—", "—", "Undecided", "2024-01-06"],
  ["Nathan Lee", 11, "Finance & Business", 75, "On Track", "Approved", "In Progress", "Not Started", "—", "—", "4-Year College", "2024-01-13"],
  ["Destiny Cooper", 11, "Education", 63, "On Track", "Approved", "Not Started", "Not Started", "—", "—", "4-Year College", "2024-01-15"],
  ["Marco Reyes", 11, "Technology", 79, "On Track", "Approved", "Approved", "Not Started", "—", "—", "4-Year College", "2024-01-14"],
  ["Aiden Robinson", 12, "Technology", 91, "On Track", "Approved", "Approved", "Completed", "Completed", "Completed", "4-Year College", "2024-01-15"],
  ["Simone Davis", 12, "Healthcare", 86, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-14"],
  ["Trevor Hughes", 12, "Skilled Trades", 88, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Trade/Technical School", "2024-01-15"],
  ["Nicole Mendez", 12, "Education", 93, "On Track", "Approved", "Approved", "Completed", "Completed", "Completed", "4-Year College", "2024-01-13"],
  ["Marcus Bailey", 12, "Arts & Media", 79, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Kylie Thompson", 12, "Finance & Business", 84, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-14"],
  ["Devon Carter", 12, "Law & Government", 75, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Priya Ramirez", 12, "Healthcare", 90, "On Track", "Approved", "Approved", "Completed", "Completed", "Completed", "4-Year College", "2024-01-13"],
  ["Calvin Brooks", 12, "Skilled Trades", 82, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Trade/Technical School", "2024-01-15"],
  ["Serena Johnson", 12, "Technology", 96, "On Track", "Approved", "Approved", "Completed", "Completed", "Completed", "4-Year College", "2024-01-14"],
  ["Troy Hamilton", 12, "Finance & Business", 71, "Needs Attention", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Undecided", "2024-01-11"],
  ["Keisha Miles", 12, "Education", 88, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Eric Perez", 12, "Law & Government", 77, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-13"],
  ["Jasmine Taylor", 12, "Arts & Media", 83, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-15"],
  ["Omar Hassan", 12, "Healthcare", 24, "At Risk", "Overdue", "Not Started", "Not Started", "Not Started", "Not Started", "Undecided", "2024-01-05"],
  ["Britney Clark", 12, "Finance & Business", 89, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "4-Year College", "2024-01-14"],
  ["Elias Nguyen", 12, "Technology", 94, "On Track", "Approved", "Approved", "Completed", "Completed", "Completed", "4-Year College", "2024-01-15"],
  ["Tamara Wilson", 12, "Healthcare", 78, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "2-Year College", "2024-01-13"],
  ["Shane Morris", 12, "Skilled Trades", 85, "On Track", "Approved", "Approved", "In Progress", "In Progress", "Approved", "Trade/Technical School", "2024-01-15"],
];
