// Generated by scripts/colleges/build-extra.mjs from the page text saved in
// scripts/colleges/reference/*.json (the live reference, read logged in on
// 2026-09-04). Do not edit by hand. data.ts prefers these over synthDetail.
import type { College, CollegeDetail } from "./data";

export const REF_DETAIL: Record<string, CollegeDetail> = {
 "black-hills-state-university": {
  "address": "1200 University St, Spearfish, South Dakota",
  "partOf": "South Dakota Board of Regents",
  "tuitionInState": 7616,
  "tuitionOutState": 10718,
  "fees": 1300,
  "housing": true,
  "housingCost": 3926,
  "foodCost": 3630,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 11863
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 13379
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 15588
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 18072
   },
   {
    "label": "Over $110,000",
    "pay": 18604
   }
  ],
  "scholarshipShare": 55,
  "scholarshipAvg": 3114,
  "pell": 38,
  "require": [
   "High school grades",
   "Class rank",
   "Your school record",
   "Specific school subjects"
  ],
  "consider": [
   "SAT or ACT scores"
  ],
  "scores": {
   "sat": "965 to 1135",
   "sentSat": 6,
   "act": "18 to 24",
   "sentAct": 66
  },
  "finish4": 29,
  "ratio": "17 to 1",
  "programmeCount": 94,
  "levels": [
   {
    "label": "Certificates",
    "n": 17
   },
   {
    "label": "Associate",
    "n": 8
   },
   {
    "label": "Bachelor's",
    "n": 56
   },
   {
    "label": "Master's",
    "n": 8
   },
   {
    "label": "Graduate certificates",
    "n": 5
   }
  ],
  "programmes": [
   {
    "name": "Business Administration and Management, General",
    "grads": 55,
    "share": 12,
    "pay": "$36,641"
   },
   {
    "name": "Elementary Education and Teaching",
    "grads": 35,
    "share": 8,
    "pay": "$36,857"
   },
   {
    "name": "Psychology, General",
    "grads": 30,
    "share": 7,
    "pay": "$28,162"
   },
   {
    "name": "Sport and Fitness Administration/Management",
    "grads": 25,
    "share": 5,
    "pay": "$21,080"
   },
   {
    "name": "Community Organization and Advocacy",
    "grads": 20,
    "share": 4,
    "pay": "$29,934"
   },
   {
    "name": "Biology/Biological Sciences, General",
    "grads": 18,
    "share": 4,
    "pay": "$25,935"
   }
  ],
  "gradStudents": 148,
  "fullTime": 1591,
  "partTime": 1755,
  "women": 62,
  "men": 38,
  "makeup": [
   {
    "label": "White",
    "n": 2272,
    "pct": 71
   },
   {
    "label": "Not reported",
    "n": 468,
    "pct": 15
   },
   {
    "label": "Hispanic or Latino",
    "n": 154,
    "pct": 5
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 89,
    "pct": 3
   },
   {
    "label": "Two or more races",
    "n": 77,
    "pct": 2
   },
   {
    "label": "Black or African American",
    "n": 60,
    "pct": 2
   },
   {
    "label": "International",
    "n": 48,
    "pct": 2
   },
   {
    "label": "Asian",
    "n": 28,
    "pct": 1
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 2,
    "pct": 0
   }
  ],
  "ways": [
   "Classes in the evening or at weekends",
   "Study abroad",
   "ROTC: Army",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "sport": {
   "league": "NCAA Division II with football",
   "students": 510,
   "teams": [
    "Football",
    "Track and Field and Cross Country (combined)",
    "Basketball",
    "Rodeo",
    "Golf",
    "Soccer",
    "Softball",
    "Volleyball"
   ]
  },
  "pay6": 38927,
  "debt": 26000,
  "monthly": 276
 },
 "dakota-state-university": {
  "address": "820 N Washington Ave, Madison, South Dakota",
  "partOf": "South Dakota Board of Regents",
  "tuitionInState": 7616,
  "tuitionOutState": 10718,
  "fees": 2038,
  "housing": true,
  "housingCost": 4746,
  "foodCost": 4320,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 17317
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 18792
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 19165
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 22601
   },
   {
    "label": "Over $110,000",
    "pay": 23269
   }
  ],
  "scholarshipShare": 79,
  "scholarshipAvg": 3560,
  "pell": 28,
  "require": [
   "High school grades",
   "Class rank",
   "Your school record",
   "An English test"
  ],
  "consider": [
   "SAT or ACT scores"
  ],
  "scores": {
   "sat": "1190 to 1440",
   "sentSat": 16,
   "act": "20 to 27",
   "sentAct": 67
  },
  "finish4": 34,
  "ratio": "18 to 1",
  "programmeCount": 69,
  "levels": [
   {
    "label": "Certificates",
    "n": 15
   },
   {
    "label": "Associate",
    "n": 8
   },
   {
    "label": "Bachelor's",
    "n": 30
   },
   {
    "label": "Master's",
    "n": 7
   },
   {
    "label": "Doctorates",
    "n": 3
   },
   {
    "label": "Graduate certificates",
    "n": 6
   }
  ],
  "programmes": [
   {
    "name": "Computer and Information Systems Security/Auditing/Information Assurance",
    "grads": 82,
    "share": 12,
    "pay": "$49,983"
   },
   {
    "name": "Computer and Information Sciences, General",
    "grads": 64,
    "share": 10,
    "pay": "$50,973"
   },
   {
    "name": "Elementary Education and Teaching",
    "grads": 36,
    "share": 5,
    "pay": "not published"
   },
   {
    "name": "System, Networking, and LAN/WAN Management/Manager",
    "grads": 27,
    "share": 4,
    "pay": "$49,983"
   },
   {
    "name": "Computer Graphics",
    "grads": 24,
    "share": 4,
    "pay": "$25,986"
   },
   {
    "name": "General Studies",
    "grads": 16,
    "share": 2,
    "pay": "not published"
   }
  ],
  "gradStudents": 708,
  "fullTime": 1718,
  "partTime": 2056,
  "women": 41,
  "men": 59,
  "makeup": [
   {
    "label": "White",
    "n": 2372,
    "pct": 77
   },
   {
    "label": "International",
    "n": 171,
    "pct": 6
   },
   {
    "label": "Hispanic or Latino",
    "n": 120,
    "pct": 4
   },
   {
    "label": "Not reported",
    "n": 93,
    "pct": 3
   },
   {
    "label": "Black or African American",
    "n": 92,
    "pct": 3
   },
   {
    "label": "Two or more races",
    "n": 90,
    "pct": 3
   },
   {
    "label": "Asian",
    "n": 68,
    "pct": 2
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 55,
    "pct": 2
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 5,
    "pct": 0
   }
  ],
  "ways": [
   "Study abroad",
   "ROTC: Air Force",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "sport": {
   "league": "NAIA Division I",
   "students": 585,
   "teams": [
    "Football",
    "Track and Field (Indoor)",
    "Track and Field (Outdoor)",
    "Baseball",
    "Basketball",
    "Cross Country",
    "Softball",
    "Volleyball"
   ]
  },
  "pay6": 46146,
  "debt": 23500,
  "monthly": 249
 },
 "dakota-wesleyan-university": {
  "address": "1200 W University Ave, Mitchell, South Dakota",
  "tuitionInState": 32500,
  "tuitionOutState": 32500,
  "fees": 1290,
  "housing": true,
  "housingCost": 3650,
  "foodCost": 4900,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 15251
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 15750
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 15927
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 19048
   },
   {
    "label": "Over $110,000",
    "pay": 22416
   }
  ],
  "scholarshipShare": 100,
  "scholarshipAvg": 18351,
  "pell": 32,
  "require": [
   "High school grades",
   "Your school record",
   "An English test"
  ],
  "consider": [],
  "finish4": 43,
  "ratio": "12 to 1",
  "programmeCount": 69,
  "levels": [
   {
    "label": "Associate",
    "n": 4
   },
   {
    "label": "Bachelor's",
    "n": 53
   },
   {
    "label": "Master's",
    "n": 8
   },
   {
    "label": "Graduate certificates",
    "n": 4
   }
  ],
  "programmes": [
   {
    "name": "Registered Nursing/Registered Nurse",
    "grads": 42,
    "share": 19,
    "pay": "$60,155"
   },
   {
    "name": "Business Administration and Management, General",
    "grads": 14,
    "share": 6,
    "pay": "not published"
   },
   {
    "name": "Elementary Education and Teaching",
    "grads": 12,
    "share": 5,
    "pay": "not published"
   },
   {
    "name": "Biochemistry",
    "grads": 10,
    "share": 4,
    "pay": "not published"
   },
   {
    "name": "Entrepreneurship/Entrepreneurial Studies",
    "grads": 10,
    "share": 4,
    "pay": "not published"
   },
   {
    "name": "Digital Arts",
    "grads": 9,
    "share": 4,
    "pay": "not published"
   }
  ],
  "gradStudents": 121,
  "fullTime": 719,
  "partTime": 173,
  "women": 53,
  "men": 47,
  "makeup": [
   {
    "label": "White",
    "n": 630,
    "pct": 82
   },
   {
    "label": "Hispanic or Latino",
    "n": 50,
    "pct": 6
   },
   {
    "label": "Two or more races",
    "n": 37,
    "pct": 5
   },
   {
    "label": "International",
    "n": 23,
    "pct": 3
   },
   {
    "label": "Black or African American",
    "n": 15,
    "pct": 2
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 10,
    "pct": 1
   },
   {
    "label": "Asian",
    "n": 3,
    "pct": 0
   },
   {
    "label": "Not reported",
    "n": 3,
    "pct": 0
   }
  ],
  "ways": [
   "Study abroad",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study"
  ],
  "notOffered": [
   "Help finding a job when you finish",
   "Childcare on campus"
  ],
  "sport": {
   "league": "NAIA Division I",
   "students": 292,
   "teams": [
    "Football",
    "Track and Field and Cross Country (combined)",
    "Soccer",
    "Baseball",
    "Basketball",
    "Wrestling",
    "Golf",
    "Softball",
    "Volleyball"
   ]
  },
  "pay6": 49432,
  "debt": 27000,
  "monthly": 286
 },
 "kairos-university": {
  "address": "2100 S Summit Ave, Sioux Falls, South Dakota",
  "tuitionInState": 3600,
  "tuitionOutState": 3600,
  "fees": 0,
  "housing": false,
  "bands": [],
  "require": [
   "Recommendations"
  ],
  "consider": [
   "High school grades",
   "Your school record",
   "SAT or ACT scores",
   "An English test",
   "Work experience",
   "A personal essay"
  ],
  "ratio": "9 to 1",
  "programmeCount": 14,
  "levels": [
   {
    "label": "Associate",
    "n": 2
   },
   {
    "label": "Bachelor's",
    "n": 2
   },
   {
    "label": "Master's",
    "n": 6
   },
   {
    "label": "Doctorates",
    "n": 3
   },
   {
    "label": "Graduate certificates",
    "n": 1
   }
  ],
  "programmes": [
   {
    "name": "Organizational Leadership",
    "grads": 14,
    "share": 6,
    "pay": "not published"
   },
   {
    "name": "Theology/Theological Studies",
    "grads": 14,
    "share": 6,
    "pay": "not published"
   }
  ],
  "gradStudents": 1157,
  "fullTime": 108,
  "partTime": 1131,
  "women": 41,
  "men": 59,
  "makeup": [
   {
    "label": "White",
    "n": 70,
    "pct": 85
   },
   {
    "label": "Black or African American",
    "n": 6,
    "pct": 7
   },
   {
    "label": "Not reported",
    "n": 4,
    "pct": 5
   },
   {
    "label": "Asian",
    "n": 2,
    "pct": 2
   }
  ],
  "ways": [],
  "helps": [
   "Careers advice"
  ],
  "notOffered": [
   "Help finding work while you study",
   "Help finding a job when you finish",
   "Childcare on campus"
  ],
  "pay6": null,
  "debt": null
 },
 "lake-area-technical-college": {
  "address": "1201 Arrow Ave, Watertown, South Dakota",
  "partOf": "South Dakota Board of Technical Education",
  "tuitionInState": 3720,
  "tuitionOutState": 3720,
  "fees": 2998,
  "housing": false,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 11193
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 12971
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 14129
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 18118
   },
   {
    "label": "Over $110,000",
    "pay": 18230
   }
  ],
  "scholarshipShare": 25,
  "scholarshipAvg": 4714,
  "pell": 34,
  "require": [],
  "consider": [],
  "ratio": "16 to 1",
  "programmeCount": 45,
  "levels": [
   {
    "label": "Certificates",
    "n": 18
   },
   {
    "label": "Associate",
    "n": 27
   }
  ],
  "programmes": [
   {
    "name": "Diesel Mechanics Technology/Technician",
    "grads": 92,
    "share": 11,
    "pay": "$41,649"
   },
   {
    "name": "Agricultural Business and Management, General",
    "grads": 87,
    "share": 10,
    "pay": "$36,747"
   },
   {
    "name": "Marketing/Marketing Management, General",
    "grads": 64,
    "share": 8,
    "pay": "$29,474"
   },
   {
    "name": "Registered Nursing/Registered Nurse",
    "grads": 47,
    "share": 6,
    "pay": "not published"
   },
   {
    "name": "Computer Science",
    "grads": 28,
    "share": 3,
    "pay": "$41,208"
   },
   {
    "name": "Welding Technology/Welder",
    "grads": 25,
    "share": 3,
    "pay": "$37,581"
   }
  ],
  "fullTime": 1464,
  "partTime": 848,
  "women": 49,
  "men": 51,
  "makeup": [
   {
    "label": "White",
    "n": 2059,
    "pct": 89
   },
   {
    "label": "Hispanic or Latino",
    "n": 65,
    "pct": 3
   },
   {
    "label": "Not reported",
    "n": 63,
    "pct": 3
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 53,
    "pct": 2
   },
   {
    "label": "Black or African American",
    "n": 35,
    "pct": 2
   },
   {
    "label": "Asian",
    "n": 18,
    "pct": 1
   },
   {
    "label": "Two or more races",
    "n": 10,
    "pct": 0
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 7,
    "pct": 0
   },
   {
    "label": "International",
    "n": 2,
    "pct": 0
   }
  ],
  "ways": [
   "Classes in the evening or at weekends"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish",
   "Childcare on campus"
  ],
  "sport": {
   "league": "NJCAA Division III",
   "students": 70,
   "teams": [
    "Rodeo"
   ]
  },
  "pay6": 43659,
  "debt": 12000,
  "monthly": 127
 },
 "mitchell-technical-college": {
  "address": "1800 E. Spruce Street, Mitchell, South Dakota",
  "partOf": "South Dakota Board of Technical Education",
  "tuitionInState": 4092,
  "tuitionOutState": 4092,
  "fees": 3432,
  "housing": false,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 9750
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 10505
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 12945
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 16044
   },
   {
    "label": "Over $110,000",
    "pay": 16493
   }
  ],
  "scholarshipShare": 21,
  "scholarshipAvg": 989,
  "pell": 33,
  "require": [],
  "consider": [],
  "ratio": "12 to 1",
  "programmeCount": 50,
  "levels": [
   {
    "label": "Certificates",
    "n": 15
   },
   {
    "label": "Associate",
    "n": 35
   }
  ],
  "programmes": [
   {
    "name": "Electrician",
    "grads": 50,
    "share": 10,
    "pay": "$42,848"
   },
   {
    "name": "Registered Nursing/Registered Nurse",
    "grads": 21,
    "share": 4,
    "pay": "not published"
   },
   {
    "name": "Agribusiness/Agricultural Business Operations",
    "grads": 18,
    "share": 3,
    "pay": "not published"
   },
   {
    "name": "Electrical and Power Transmission Installation/Installer, General",
    "grads": 18,
    "share": 3,
    "pay": "$42,848"
   },
   {
    "name": "Agricultural Mechanization, General",
    "grads": 17,
    "share": 3,
    "pay": "$40,163"
   },
   {
    "name": "Radiologic Technology/Science - Radiographer",
    "grads": 16,
    "share": 3,
    "pay": "$51,161"
   }
  ],
  "fullTime": 841,
  "partTime": 345,
  "women": 33,
  "men": 67,
  "makeup": [
   {
    "label": "White",
    "n": 1046,
    "pct": 88
   },
   {
    "label": "Two or more races",
    "n": 45,
    "pct": 4
   },
   {
    "label": "Hispanic or Latino",
    "n": 35,
    "pct": 3
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 24,
    "pct": 2
   },
   {
    "label": "Not reported",
    "n": 19,
    "pct": 2
   },
   {
    "label": "Asian",
    "n": 7,
    "pct": 1
   },
   {
    "label": "Black or African American",
    "n": 6,
    "pct": 1
   },
   {
    "label": "International",
    "n": 3,
    "pct": 0
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 1,
    "pct": 0
   }
  ],
  "ways": [],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "pay6": 47849,
  "debt": 12000,
  "monthly": 127
 },
 "mount-marty-university": {
  "address": "1105 W. 8th Street, Yankton, South Dakota",
  "tuitionInState": 31500,
  "tuitionOutState": 31500,
  "fees": 3100,
  "housing": true,
  "housingCost": 9800,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 19564
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 18492
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 23669
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 22331
   },
   {
    "label": "Over $110,000",
    "pay": 23601
   }
  ],
  "scholarshipShare": 91,
  "scholarshipAvg": 24363,
  "pell": 29,
  "require": [
   "High school grades",
   "Your school record"
  ],
  "consider": [
   "Class rank",
   "SAT or ACT scores",
   "An English test"
  ],
  "scores": {
   "sat": "Not published",
   "sentSat": 0,
   "act": "18 to 25",
   "sentAct": 48
  },
  "finish4": 41,
  "ratio": "12 to 1",
  "programmeCount": 56,
  "levels": [
   {
    "label": "Certificates",
    "n": 4
   },
   {
    "label": "Associate",
    "n": 7
   },
   {
    "label": "Bachelor's",
    "n": 33
   },
   {
    "label": "Master's",
    "n": 6
   },
   {
    "label": "Doctorates",
    "n": 2
   },
   {
    "label": "Graduate certificates",
    "n": 4
   }
  ],
  "programmes": [
   {
    "name": "Sports, Kinesiology, and Physical Education/Fitness, Other",
    "grads": 25,
    "share": 11,
    "pay": "not published"
   },
   {
    "name": "Registered Nursing/Registered Nurse",
    "grads": 22,
    "share": 9,
    "pay": "$61,763"
   },
   {
    "name": "Business Administration and Management, General",
    "grads": 17,
    "share": 7,
    "pay": "not published"
   },
   {
    "name": "Elementary Education and Teaching",
    "grads": 15,
    "share": 6,
    "pay": "$38,340"
   },
   {
    "name": "Secondary Education and Teaching",
    "grads": 10,
    "share": 4,
    "pay": "$38,340"
   },
   {
    "name": "Accounting",
    "grads": 6,
    "share": 3,
    "pay": "not published"
   }
  ],
  "gradStudents": 262,
  "fullTime": 829,
  "partTime": 455,
  "women": 46,
  "men": 54,
  "makeup": [
   {
    "label": "White",
    "n": 690,
    "pct": 68
   },
   {
    "label": "Hispanic or Latino",
    "n": 79,
    "pct": 8
   },
   {
    "label": "Not reported",
    "n": 70,
    "pct": 7
   },
   {
    "label": "International",
    "n": 66,
    "pct": 6
   },
   {
    "label": "Black or African American",
    "n": 52,
    "pct": 5
   },
   {
    "label": "Two or more races",
    "n": 29,
    "pct": 3
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 27,
    "pct": 3
   },
   {
    "label": "Asian",
    "n": 9,
    "pct": 1
   }
  ],
  "ways": [
   "ROTC: Army",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "sport": {
   "league": "NAIA Division II",
   "students": 524,
   "teams": [
    "Football",
    "Baseball",
    "Basketball",
    "Track and Field and Cross Country (combined)",
    "Soccer",
    "Tennis",
    "Golf",
    "Archery",
    "Softball",
    "Volleyball"
   ]
  },
  "pay6": 46984,
  "debt": 26396,
  "monthly": 280
 },
 "northern-state-university": {
  "address": "1200 S Jay St, Aberdeen, South Dakota",
  "partOf": "South Dakota Board of Regents",
  "tuitionInState": 7616,
  "tuitionOutState": 10718,
  "fees": 1229,
  "housing": true,
  "housingCost": 6002,
  "foodCost": 4572,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 10762
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 12087
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 15293
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 18372
   },
   {
    "label": "Over $110,000",
    "pay": 17933
   }
  ],
  "scholarshipShare": 90,
  "scholarshipAvg": 4084,
  "pell": 32,
  "require": [
   "High school grades",
   "Class rank",
   "Your school record",
   "Specific school subjects",
   "An English test"
  ],
  "consider": [
   "Recommendations",
   "SAT or ACT scores",
   "A personal essay"
  ],
  "scores": {
   "sat": "980 to 1160",
   "sentSat": 2,
   "act": "18 to 24",
   "sentAct": 74
  },
  "finish4": 35,
  "ratio": "19 to 1",
  "programmeCount": 84,
  "levels": [
   {
    "label": "Certificates",
    "n": 14
   },
   {
    "label": "Associate",
    "n": 7
   },
   {
    "label": "Bachelor's",
    "n": 44
   },
   {
    "label": "Master's",
    "n": 11
   },
   {
    "label": "Graduate certificates",
    "n": 8
   }
  ],
  "programmes": [
   {
    "name": "Elementary Education and Teaching",
    "grads": 33,
    "share": 9,
    "pay": "$39,033"
   },
   {
    "name": "Business Administration and Management, General",
    "grads": 25,
    "share": 7,
    "pay": "$38,996"
   },
   {
    "name": "Biology/Biological Sciences, General",
    "grads": 21,
    "share": 6,
    "pay": "not published"
   },
   {
    "name": "Psychology, General",
    "grads": 18,
    "share": 5,
    "pay": "not published"
   },
   {
    "name": "Exercise Physiology and Kinesiology",
    "grads": 17,
    "share": 5,
    "pay": "not published"
   },
   {
    "name": "Criminal Justice/Safety Studies",
    "grads": 12,
    "share": 3,
    "pay": "not published"
   }
  ],
  "gradStudents": 539,
  "fullTime": 1187,
  "partTime": 2521,
  "women": 60,
  "men": 40,
  "makeup": [
   {
    "label": "White",
    "n": 2569,
    "pct": 81
   },
   {
    "label": "Hispanic or Latino",
    "n": 131,
    "pct": 4
   },
   {
    "label": "Two or more races",
    "n": 101,
    "pct": 3
   },
   {
    "label": "International",
    "n": 99,
    "pct": 3
   },
   {
    "label": "Not reported",
    "n": 85,
    "pct": 3
   },
   {
    "label": "Black or African American",
    "n": 70,
    "pct": 2
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 58,
    "pct": 2
   },
   {
    "label": "Asian",
    "n": 51,
    "pct": 2
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 5,
    "pct": 0
   }
  ],
  "ways": [
   "Study abroad",
   "Undergraduate research",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "sport": {
   "league": "NCAA Division II with football",
   "students": 522,
   "teams": [
    "Football",
    "Track and Field and Cross Country (combined)",
    "Baseball",
    "Wrestling",
    "Basketball",
    "Soccer",
    "Softball",
    "Swimming and Diving (combined)",
    "Volleyball"
   ]
  },
  "pay6": 41536,
  "debt": 22320,
  "monthly": 237
 },
 "paul-mitchell-the-school-rapid-city": {
  "address": "333 Omaha St. Suite 6 & 7, Rapid City, South Dakota",
  "tuitionInState": null,
  "tuitionOutState": null,
  "fees": null,
  "housing": false,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 17122
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 18376
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 22626
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 24848
   },
   {
    "label": "Over $110,000",
    "pay": 25771
   }
  ],
  "scholarshipShare": 70,
  "scholarshipAvg": 500,
  "pell": 70,
  "require": [],
  "consider": [],
  "ratio": "11 to 1",
  "programmeCount": 4,
  "levels": [
   {
    "label": "Certificates",
    "n": 4
   }
  ],
  "programmes": [
   {
    "name": "Aesthetician/Esthetician and Skin Care Specialist Certificate, under a year",
    "grads": 20,
    "share": 37,
    "pay": "not published"
   },
   {
    "name": "Cosmetology/Cosmetologist, General Certificate, 1-2 years",
    "grads": 17,
    "share": 31,
    "pay": "not published"
   },
   {
    "name": "Massage Therapy/Therapeutic Massage Certificate, under a year",
    "grads": 11,
    "share": 20,
    "pay": "$14,756"
   },
   {
    "name": "Nail Technician/Specialist and Manicurist Certificate, under a year",
    "grads": 6,
    "share": 11,
    "pay": "not published"
   }
  ],
  "fullTime": 64,
  "partTime": 2,
  "women": 92,
  "men": 8,
  "makeup": [
   {
    "label": "White",
    "n": 50,
    "pct": 76
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 12,
    "pct": 18
   },
   {
    "label": "Two or more races",
    "n": 2,
    "pct": 3
   },
   {
    "label": "Black or African American",
    "n": 1,
    "pct": 2
   },
   {
    "label": "Asian",
    "n": 1,
    "pct": 2
   }
  ],
  "ways": [],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "pay6": 22585,
  "debt": 7917,
  "monthly": 84
 },
 "sinte-gleska-university": {
  "address": "E. Highway 18, 101 Antelope Lake Circle, Mission, South Dakota",
  "tuitionInState": 4200,
  "tuitionOutState": 4200,
  "fees": 514,
  "housing": false,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 11728
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 13818
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 14839
   }
  ],
  "scholarshipShare": 0,
  "pell": 91,
  "require": [],
  "consider": [],
  "finish4": 50,
  "ratio": "16 to 1",
  "programmeCount": 90,
  "levels": [
   {
    "label": "Certificates",
    "n": 17
   },
   {
    "label": "Associate",
    "n": 34
   },
   {
    "label": "Bachelor's",
    "n": 26
   },
   {
    "label": "Master's",
    "n": 11
   },
   {
    "label": "Graduate certificates",
    "n": 2
   }
  ],
  "programmes": [
   {
    "name": "Mental Health Counseling/Counselor",
    "grads": 10,
    "share": 12,
    "pay": "not published"
   },
   {
    "name": "Human Services, General",
    "grads": 8,
    "share": 10,
    "pay": "not published"
   },
   {
    "name": "Accounting and Business/Management",
    "grads": 4,
    "share": 5,
    "pay": "not published"
   },
   {
    "name": "Early Childhood Education and Teaching",
    "grads": 3,
    "share": 4,
    "pay": "not published"
   },
   {
    "name": "Teacher Education and Professional Development, Specific Levels and Methods, Other",
    "grads": 3,
    "share": 4,
    "pay": "not published"
   },
   {
    "name": "Business Administration, Management and Operations, Other",
    "grads": 2,
    "share": 2,
    "pay": "not published"
   }
  ],
  "gradStudents": 77,
  "fullTime": 212,
  "partTime": 380,
  "women": 75,
  "men": 25,
  "makeup": [
   {
    "label": "American Indian or Alaska Native",
    "n": 470,
    "pct": 91
   },
   {
    "label": "White",
    "n": 42,
    "pct": 8
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 3,
    "pct": 1
   }
  ],
  "ways": [
   "Classes in the evening or at weekends",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Childcare on campus"
  ],
  "notOffered": [
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "pay6": 15889,
  "debt": null
 },
 "sisseton-wahpeton-college": {
  "address": "12572 BIA Rd 700, Sisseton, South Dakota",
  "tuitionInState": 3840,
  "tuitionOutState": 3840,
  "fees": 490,
  "housing": true,
  "housingCost": 3330,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 590
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 5909
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 5315
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 7871
   }
  ],
  "scholarshipShare": 40,
  "scholarshipAvg": 3760,
  "pell": 83,
  "require": [],
  "consider": [],
  "ratio": "8 to 1",
  "programmeCount": 18,
  "levels": [
   {
    "label": "Certificates",
    "n": 5
   },
   {
    "label": "Associate",
    "n": 11
   },
   {
    "label": "Bachelor's",
    "n": 2
   }
  ],
  "programmes": [
   {
    "name": "Business Administration and Management, General",
    "grads": 10,
    "share": 19,
    "pay": "not published"
   },
   {
    "name": "Behavioral Sciences",
    "grads": 4,
    "share": 8,
    "pay": "not published"
   }
  ],
  "fullTime": 145,
  "partTime": 61,
  "women": 61,
  "men": 39,
  "makeup": [
   {
    "label": "American Indian or Alaska Native",
    "n": 194,
    "pct": 94
   },
   {
    "label": "Black or African American",
    "n": 5,
    "pct": 2
   },
   {
    "label": "White",
    "n": 3,
    "pct": 1
   },
   {
    "label": "Two or more races",
    "n": 3,
    "pct": 1
   },
   {
    "label": "Hispanic or Latino",
    "n": 1,
    "pct": 0
   }
  ],
  "ways": [],
  "helps": [
   "Careers advice",
   "Help finding work while you study"
  ],
  "notOffered": [
   "Help finding a job when you finish",
   "Childcare on campus"
  ],
  "sport": {
   "league": "Independent",
   "students": 34,
   "teams": [
    "Basketball",
    "Volleyball"
   ]
  },
  "pay6": 23940,
  "debt": null
 },
 "south-dakota-school-of-mines-and-technology": {
  "address": "501 E Saint Joseph St, Rapid City, South Dakota",
  "partOf": "South Dakota Board of Regents",
  "tuitionInState": 7800,
  "tuitionOutState": 12200,
  "fees": 2700,
  "housing": true,
  "housingCost": 4358,
  "foodCost": 4322,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 15348
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 17909
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 18366
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 21176
   },
   {
    "label": "Over $110,000",
    "pay": 21993
   }
  ],
  "scholarshipShare": 75,
  "scholarshipAvg": 3860,
  "pell": 21,
  "require": [
   "Your school record",
   "An English test"
  ],
  "consider": [
   "High school grades",
   "Specific school subjects",
   "SAT or ACT scores",
   "A personal essay"
  ],
  "scores": {
   "sat": "1140 to 1340",
   "sentSat": 25,
   "act": "24 to 30",
   "sentAct": 79
  },
  "finish4": 24,
  "ratio": "12 to 1",
  "programmeCount": 59,
  "levels": [
   {
    "label": "Associate",
    "n": 1
   },
   {
    "label": "Bachelor's",
    "n": 21
   },
   {
    "label": "Master's",
    "n": 19
   },
   {
    "label": "Doctorates",
    "n": 10
   },
   {
    "label": "Graduate certificates",
    "n": 8
   }
  ],
  "programmes": [
   {
    "name": "Mechanical Engineering",
    "grads": 84,
    "share": 17,
    "pay": "$63,634"
   },
   {
    "name": "Computer and Information Sciences, General",
    "grads": 35,
    "share": 7,
    "pay": "not published"
   },
   {
    "name": "Civil Engineering, General",
    "grads": 32,
    "share": 6,
    "pay": "$62,408"
   },
   {
    "name": "Metallurgical Engineering",
    "grads": 29,
    "share": 6,
    "pay": "not published"
   },
   {
    "name": "Electrical and Electronics Engineering",
    "grads": 26,
    "share": 5,
    "pay": "$64,157"
   },
   {
    "name": "Industrial Engineering",
    "grads": 25,
    "share": 5,
    "pay": "$64,319"
   }
  ],
  "gradStudents": 360,
  "fullTime": 2020,
  "partTime": 556,
  "women": 23,
  "men": 77,
  "makeup": [
   {
    "label": "White",
    "n": 1793,
    "pct": 81
   },
   {
    "label": "Hispanic or Latino",
    "n": 124,
    "pct": 6
   },
   {
    "label": "Not reported",
    "n": 100,
    "pct": 5
   },
   {
    "label": "Two or more races",
    "n": 61,
    "pct": 3
   },
   {
    "label": "Asian",
    "n": 43,
    "pct": 2
   },
   {
    "label": "International",
    "n": 38,
    "pct": 2
   },
   {
    "label": "Black or African American",
    "n": 30,
    "pct": 1
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 25,
    "pct": 1
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 2,
    "pct": 0
   }
  ],
  "ways": [
   "Study abroad",
   "ROTC: Army"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "sport": {
   "league": "NCAA Division II with football",
   "students": 439,
   "teams": [
    "Track and Field and Cross Country (combined)",
    "Football",
    "Soccer",
    "Basketball",
    "Golf",
    "Volleyball"
   ]
  },
  "pay6": 62863,
  "debt": 27000,
  "monthly": 286
 },
 "university-of-sioux-falls": {
  "address": "1101 W 22nd St, Sioux Falls, South Dakota",
  "tuitionInState": 21150,
  "tuitionOutState": 21150,
  "fees": 600,
  "housing": true,
  "housingCost": 4250,
  "foodCost": 4450,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 18145
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 17804
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 17992
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 21375
   },
   {
    "label": "Over $110,000",
    "pay": 24038
   }
  ],
  "scholarshipShare": 100,
  "scholarshipAvg": 10554,
  "pell": 32,
  "require": [
   "High school grades"
  ],
  "consider": [
   "Specific school subjects"
  ],
  "finish4": 49,
  "ratio": "18 to 1",
  "programmeCount": 66,
  "levels": [
   {
    "label": "Associate",
    "n": 9
   },
   {
    "label": "Bachelor's",
    "n": 49
   },
   {
    "label": "Master's",
    "n": 7
   },
   {
    "label": "Doctorates",
    "n": 1
   }
  ],
  "programmes": [
   {
    "name": "Business Administration and Management, General",
    "grads": 56,
    "share": 13,
    "pay": "$41,830"
   },
   {
    "name": "Registered Nursing/Registered Nurse",
    "grads": 38,
    "share": 9,
    "pay": "$60,096"
   },
   {
    "name": "Psychology, General",
    "grads": 33,
    "share": 8,
    "pay": "$28,556"
   },
   {
    "name": "Exercise Science and Kinesiology",
    "grads": 21,
    "share": 5,
    "pay": "$30,066"
   },
   {
    "name": "Elementary Education and Teaching",
    "grads": 19,
    "share": 4,
    "pay": "$35,814"
   },
   {
    "name": "Criminal Justice/Safety Studies",
    "grads": 18,
    "share": 4,
    "pay": "$32,984"
   }
  ],
  "gradStudents": 209,
  "fullTime": 1220,
  "partTime": 230,
  "women": 61,
  "men": 39,
  "makeup": [
   {
    "label": "White",
    "n": 935,
    "pct": 75
   },
   {
    "label": "Hispanic or Latino",
    "n": 86,
    "pct": 7
   },
   {
    "label": "Two or more races",
    "n": 73,
    "pct": 6
   },
   {
    "label": "Black or African American",
    "n": 58,
    "pct": 5
   },
   {
    "label": "Not reported",
    "n": 42,
    "pct": 3
   },
   {
    "label": "Asian",
    "n": 22,
    "pct": 2
   },
   {
    "label": "International",
    "n": 17,
    "pct": 1
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 4,
    "pct": 0
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 4,
    "pct": 0
   }
  ],
  "ways": [
   "Classes in the evening or at weekends",
   "Study abroad",
   "ROTC: Air Force",
   "Teacher training: approved by the state"
  ],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "sport": {
   "league": "NCAA Division II with football",
   "students": 616,
   "teams": [
    "Football",
    "Track and Field and Cross Country (combined)",
    "Baseball",
    "Wrestling",
    "Basketball",
    "Golf",
    "Soccer",
    "Softball",
    "Swimming",
    "Tennis",
    "Volleyball"
   ]
  },
  "pay6": 46712,
  "debt": 23249,
  "monthly": 246
 },
 "western-dakota-technical-college": {
  "address": "800 Mickelson Dr, Rapid City, South Dakota",
  "partOf": "South Dakota Board of Technical Education",
  "tuitionInState": 3596,
  "tuitionOutState": 3596,
  "fees": 4698,
  "housing": true,
  "housingCost": 5900,
  "bands": [
   {
    "label": "Under $30,000",
    "pay": 10071
   },
   {
    "label": "$30,000 to $48,000",
    "pay": 10543
   },
   {
    "label": "$48,000 to $75,000",
    "pay": 14003
   },
   {
    "label": "$75,000 to $110,000",
    "pay": 18657
   },
   {
    "label": "Over $110,000",
    "pay": 18845
   }
  ],
  "scholarshipShare": 17,
  "scholarshipAvg": 2861,
  "pell": 51,
  "require": [],
  "consider": [],
  "ratio": "11 to 1",
  "programmeCount": 46,
  "levels": [
   {
    "label": "Certificates",
    "n": 21
   },
   {
    "label": "Associate",
    "n": 25
   }
  ],
  "programmes": [
   {
    "name": "Registered Nursing/Registered Nurse",
    "grads": 34,
    "share": 10,
    "pay": "not published"
   },
   {
    "name": "Electrician",
    "grads": 19,
    "share": 6,
    "pay": "$37,211"
   },
   {
    "name": "Computer Systems Networking and Telecommunications",
    "grads": 15,
    "share": 5,
    "pay": "$34,470"
   },
   {
    "name": "Health Services/Allied Health/Health Sciences, General",
    "grads": 15,
    "share": 5,
    "pay": "not published"
   },
   {
    "name": "Diesel Mechanics Technology/Technician",
    "grads": 12,
    "share": 4,
    "pay": "$38,609"
   },
   {
    "name": "Drafting and Design Technology/Technician, General",
    "grads": 10,
    "share": 3,
    "pay": "$37,098"
   }
  ],
  "fullTime": 531,
  "partTime": 633,
  "women": 56,
  "men": 44,
  "makeup": [
   {
    "label": "White",
    "n": 888,
    "pct": 76
   },
   {
    "label": "American Indian or Alaska Native",
    "n": 91,
    "pct": 8
   },
   {
    "label": "Hispanic or Latino",
    "n": 71,
    "pct": 6
   },
   {
    "label": "Two or more races",
    "n": 51,
    "pct": 4
   },
   {
    "label": "Not reported",
    "n": 32,
    "pct": 3
   },
   {
    "label": "Black or African American",
    "n": 16,
    "pct": 1
   },
   {
    "label": "Asian",
    "n": 13,
    "pct": 1
   },
   {
    "label": "Native Hawaiian or Pacific Islander",
    "n": 1,
    "pct": 0
   },
   {
    "label": "International",
    "n": 1,
    "pct": 0
   }
  ],
  "ways": [],
  "helps": [
   "Careers advice",
   "Help finding work while you study",
   "Help finding a job when you finish"
  ],
  "notOffered": [
   "Childcare on campus"
  ],
  "pay6": 36971,
  "debt": 15000,
  "monthly": 159
 }
};

/** Card-level figures from the same pages, applied over the hand-typed
 *  entries in data.ts so the card and the page never disagree. */
export const REF_BASE: Record<string, Partial<College>> = {
 "black-hills-state-university": {
  "undergrads": 3198,
  "netPrice": 15911,
  "finish": 42,
  "retention": 72,
  "repay": 69,
  "admitRate": 96,
  "applied": 1690,
  "website": "https://www.bhsu.edu/"
 },
 "dakota-state-university": {
  "undergrads": 3066,
  "netPrice": 21057,
  "finish": 45,
  "retention": 75,
  "repay": 73,
  "admitRate": 88,
  "applied": 2418,
  "website": "https://dsu.edu/"
 },
 "dakota-wesleyan-university": {
  "undergrads": 771,
  "netPrice": 19735,
  "finish": 59,
  "retention": 75,
  "repay": 72,
  "admitRate": 73,
  "applied": 1247,
  "website": "https://www.dwu.edu/"
 },
 "kairos-university": {
  "undergrads": 82,
  "netPrice": null,
  "finish": null,
  "retention": null,
  "repay": null,
  "admitRate": 85,
  "applied": 39,
  "website": "https://www.kairos.edu/"
 },
 "lake-area-technical-college": {
  "undergrads": 2312,
  "netPrice": 15979,
  "finish": 73,
  "retention": 81,
  "repay": 76,
  "admitRate": null,
  "website": "https://www.lakeareatech.edu/"
 },
 "mitchell-technical-college": {
  "undergrads": 1186,
  "netPrice": 13460,
  "finish": 73,
  "retention": 85,
  "repay": 70,
  "admitRate": null,
  "website": "https://www.mitchelltech.edu/"
 },
 "mount-marty-university": {
  "undergrads": 1022,
  "netPrice": 22227,
  "finish": 53,
  "retention": 68,
  "repay": 71,
  "admitRate": 43,
  "applied": 1750,
  "website": "https://www.mountmarty.edu/"
 },
 "northern-state-university": {
  "undergrads": 3169,
  "netPrice": 15812,
  "finish": 50,
  "retention": 77,
  "repay": 71,
  "admitRate": 93,
  "applied": 1086,
  "website": "https://northern.edu/"
 },
 "paul-mitchell-the-school-rapid-city": {
  "undergrads": 66,
  "netPrice": 19694,
  "finish": null,
  "retention": 80,
  "repay": 58,
  "admitRate": null,
  "website": "https://paulmitchell.edu/rapidcity"
 },
 "sinte-gleska-university": {
  "undergrads": 515,
  "netPrice": 12768,
  "finish": 7,
  "retention": 100,
  "repay": null,
  "admitRate": null,
  "website": "https://www.sintegleska.edu/"
 },
 "sisseton-wahpeton-college": {
  "undergrads": 206,
  "netPrice": 2977,
  "finish": 17,
  "retention": null,
  "repay": null,
  "admitRate": null,
  "website": "https://www.swcollege.edu/"
 },
 "south-dakota-school-of-mines-and-technology": {
  "undergrads": 2216,
  "netPrice": 20183,
  "finish": 58,
  "retention": 84,
  "repay": 82,
  "admitRate": 80,
  "applied": 1565,
  "website": "https://www.sdsmt.edu/"
 },
 "university-of-sioux-falls": {
  "undergrads": 1241,
  "netPrice": 21383,
  "finish": 62,
  "retention": 74,
  "repay": 78,
  "admitRate": 83,
  "applied": 2291,
  "website": "https://www.usiouxfalls.edu/"
 },
 "western-dakota-technical-college": {
  "undergrads": 1164,
  "netPrice": 12670,
  "finish": 46,
  "retention": 67,
  "repay": 54,
  "admitRate": null,
  "website": "https://www.wdt.edu/"
 }
};
