// Turns scripts/colleges/reference/<slug>.json (extracted from the live
// reference while logged in) into src/components/colleges/extra.ts.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
const dir = "scripts/colleges/reference";
const DESC = new Set(["Real research before you graduate", "Military training alongside your degree", "You can study around a job", "A supported route into college"]);
const pct = (s) => (s ? Number(String(s).replace("%", "")) : null);
const score = (s) => { if (!s) return null; const m = s.match(/^(\d+)[–-](\d+)(\d+)% of students sent scores$/); if (!m) return null; return { lo: Number(m[1]), hi: Number(m[2]), sent: Number(m[3]) }; };
// "530–6102% ..." is ambiguous where hi and sent run together; the reference
// prints hi as 3 digits for SAT and 2 for ACT, so split by known widths.
const scoreW = (s, hiWidth) => { if (!s) return null; const m = s.match(/^(\d+)[–-](\d+)% of students sent scores$/); if (!m) return null; const rest = m[2]; return { lo: Number(m[1]), hi: Number(rest.slice(0, hiWidth)), sent: Number(rest.slice(hiWidth)) }; };
const out = {};
for (const f of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
  const j = JSON.parse(readFileSync(`${dir}/${f}`, "utf8"));
  const waysLines = (j.ways ?? "").split("\n").filter(Boolean).filter((l) => !/^They told the government/.test(l));
  const ways = [];
  for (const l of waysLines) { if (DESC.has(l) && ways.length) ways[ways.length - 1].note = l; else ways.push({ name: l.replace(/\s*—\s*/g, ": ") }); }
  const notOffered = (j.notes ?? []).map((n) => n.match(/do not offer: (.*)\.$/)?.[1]).filter(Boolean).flatMap((s) => s.split(", "));
  const programmes = Object.fromEntries(Object.entries(j.P ?? {}).map(([level, rows]) => [level, rows.split("\n").filter(Boolean).map((r) => { const [name, grads, share, pay] = r.split("|"); return { name, grads: Number(grads.replace(/,/g, "")), share, pay }; })]));
  out[j.slug] = {
    links: { aid: j.aid, apply: j.apply, calc: j.calc, site: j.site, map: j.map },
    finish5: pct(j.finish5), finish6b: pct(j.finish6b), finish6ft: pct(j.finish6ft), finish8: pct(j.finish8), retPart: pct(j.retPart),
    meal: j.meal, fallBehind: pct(j.fallBehind),
    satR: scoreW(j.satR, 3), satM: scoreW(j.satM, 3), act: scoreW(j.act, 2),
    teamMen: j.teamMen ? Number(j.teamMen.replace(/,/g, "")) : null, teamWomen: j.teamWomen ? Number(j.teamWomen.replace(/,/g, "")) : null,
    ways, notOffered, counts: j.counts ?? {}, programmes,
  };
  void score;
}
const ts = `// Generated by scripts/colleges/build-extra.mjs from scripts/colleges/reference/*.json
// (the live reference pages, read logged in on 2026-09-04). Do not edit by hand.
export type ScoreRange = { lo: number; hi: number; sent: number };
export type ProgrammeRow = { name: string; grads: number; share: string; pay: string };
export type CollegeExtra = {
  links: { aid: string | null; apply: string | null; calc: string | null; site: string | null; map: string | null };
  finish5: number | null; finish6b: number | null; finish6ft: number | null; finish8: number | null; retPart: number | null;
  meal: string | null; fallBehind: number | null;
  satR: ScoreRange | null; satM: ScoreRange | null; act: ScoreRange | null;
  teamMen: number | null; teamWomen: number | null;
  ways: { name: string; note?: string }[]; notOffered: string[];
  counts: Record<string, number>; programmes: Record<string, ProgrammeRow[]>;
};
export const EXTRA: Record<string, CollegeExtra> = ${JSON.stringify(out, null, 1)};
`;
writeFileSync("src/components/colleges/extra.ts", ts);
console.log(Object.keys(out).length, "colleges;", Object.entries(out).map(([k, v]) => `${k}: ${Object.keys(v.programmes).length} levels`).join("; "));
