// The team's Browse poster library (BROWSE Images-3, 18 Sept 2026): every
// career we hold a portrait for that is not already in the Figma catalog,
// imported by scripts in the session scratchpad as 840x1188 webp (saliency
// crop for the few landscape sources). Titles normalised to singular and the
// catalog's spellings; worlds mapped to the app's world names. Generated:
// do not hand-edit, re-run the import instead.

import type { CatalogCareer } from "./catalog";

const C = (title: string, world: string, photo: string): CatalogCareer => ({ title, world, photo });

export const BROWSE_LIBRARY: CatalogCareer[] = [
  C("Actor", "Arts, Media & Sport", "/images/app/browse/actor.webp"),
  C("Audio and Video Technician", "Arts, Media & Sport", "/images/app/browse/audio-and-video-technician.webp"),
  C("Broadcast Technician", "Arts, Media & Sport", "/images/app/browse/broadcast-technician.webp"),
  C("Choreographer", "Arts, Media & Sport", "/images/app/browse/choreographer.webp"),
  C("Coach or Scout", "Arts, Media & Sport", "/images/app/browse/coach-or-scout.webp"),
  C("Court Reporter or Captioner", "Arts, Media & Sport", "/images/app/browse/court-reporter-or-captioner.webp"),
  C("Dancer", "Arts, Media & Sport", "/images/app/browse/dancer.webp"),
  C("Fashion Designer", "Arts, Media & Sport", "/images/app/browse/fashion-designer.webp"),
  C("Film and Video Editor", "Arts, Media & Sport", "/images/app/browse/film-and-video-editor.webp"),
  C("Floral Designer", "Arts, Media & Sport", "/images/app/browse/floral-designer.webp"),
  C("Game Producer", "Arts, Media & Sport", "/images/app/browse/game-producer.webp"),
  C("Graphic Designer", "Arts, Media & Sport", "/images/app/browse/graphic-designer.webp"),
  C("Interior Designer", "Arts, Media & Sport", "/images/app/browse/interior-designer.webp"),
  C("Interpreter or Translator", "Arts, Media & Sport", "/images/app/browse/interpreter-or-translator.webp"),
  C("Musician or Singer", "Arts, Media & Sport", "/images/app/browse/musician-or-singer.webp"),
  C("Photographer", "Arts, Media & Sport", "/images/app/browse/photographer.webp"),
  C("Professional Athlete", "Arts, Media & Sport", "/images/app/browse/professional-athlete.webp"),
  C("Public Relations Specialist", "Arts, Media & Sport", "/images/app/browse/public-relations-specialist.webp"),
  C("Set Designer", "Arts, Media & Sport", "/images/app/browse/set-designer.webp"),
  C("Visual Merchandiser", "Arts, Media & Sport", "/images/app/browse/visual-merchandiser.webp"),
  C("Writer or Copywriter", "Arts, Media & Sport", "/images/app/browse/writer-or-copywriter.webp"),
  C("Boilermaker", "Building & Construction", "/images/app/browse/boilermaker.webp"),
  C("Bricklayer", "Building & Construction", "/images/app/browse/bricklayer.webp"),
  C("Building Inspector", "Building & Construction", "/images/app/browse/building-inspector.webp"),
  C("Carpenter", "Building & Construction", "/images/app/browse/carpenter.webp"),
  C("Concrete Finisher", "Building & Construction", "/images/app/browse/concrete-finisher.webp"),
  C("Construction Foreman", "Building & Construction", "/images/app/browse/construction-foreman.webp"),
  C("Construction Laborer", "Building & Construction", "/images/app/browse/construction-laborer.webp"),
  C("Construction Manager", "Building & Construction", "/images/app/browse/construction-manager.webp"),
  C("Drywall Installer", "Building & Construction", "/images/app/browse/drywall-installer.webp"),
  C("Elevator Technician", "Building & Construction", "/images/app/browse/elevator-technician.webp"),
  C("Glazier", "Building & Construction", "/images/app/browse/glazier.webp"),
  C("Hazardous Materials Worker", "Building & Construction", "/images/app/browse/hazardous-materials-worker.webp"),
  C("Heavy Equipment Operator", "Building & Construction", "/images/app/browse/heavy-equipment-operator.webp"),
  C("Highway Maintenance Worker", "Building & Construction", "/images/app/browse/highway-maintenance-worker.webp"),
  C("Iron Worker", "Building & Construction", "/images/app/browse/iron-worker.webp"),
  C("Painter", "Building & Construction", "/images/app/browse/painter.webp"),
  C("Pest Control Technician", "Building & Construction", "/images/app/browse/pest-control-technician.webp"),
  C("Plumber", "Building & Construction", "/images/app/browse/plumber.webp"),
  C("Solar Panel Installer", "Building & Construction", "/images/app/browse/solar-panel-installer.webp"),
  C("Bank Teller", "Business & Finance", "/images/app/browse/bank-teller.webp"),
  C("Claims Adjuster", "Business & Finance", "/images/app/browse/claims-adjuster.webp"),
  C("Customer Service Representative", "Business & Finance", "/images/app/browse/customer-service-representative.webp"),
  C("Entrepreneur", "Business & Finance", "/images/app/browse/entrepreneur.webp"),
  C("Event Director", "Business & Finance", "/images/app/browse/event-director.webp"),
  C("Event Marketing Manager", "Business & Finance", "/images/app/browse/event-marketing-manager.webp"),
  C("Event Operations Manager", "Business & Finance", "/images/app/browse/event-operations-manager.webp"),
  C("Exhibition Sales Manager", "Business & Finance", "/images/app/browse/exhibition-sales-manager.webp"),
  C("Fashion Buyer", "Business & Finance", "/images/app/browse/fashion-buyer.webp"),
  C("Fashion E-Commerce Manager", "Business & Finance", "/images/app/browse/fashion-e-commerce-manager.webp"),
  C("Fashion Merchandiser", "Business & Finance", "/images/app/browse/fashion-merchandiser.webp"),
  C("Financial Advisor", "Business & Finance", "/images/app/browse/financial-advisor.webp"),
  C("Insurance Agent", "Business & Finance", "/images/app/browse/insurance-agent.webp"),
  C("Management Consultant", "Business & Finance", "/images/app/browse/management-consultant.webp"),
  C("Market Research Analyst", "Business & Finance", "/images/app/browse/market-research-analyst.webp"),
  C("Marketing Manager", "Business & Finance", "/images/app/browse/marketing-manager.webp"),
  C("Medical Office Assistant", "Business & Finance", "/images/app/browse/medical-office-assistant.webp"),
  C("Office Clerk", "Business & Finance", "/images/app/browse/office-clerk.webp"),
  C("Operations Manager", "Business & Finance", "/images/app/browse/operations-manager.webp"),
  C("Project Manager", "Business & Finance", "/images/app/browse/project-manager.webp"),
  C("Real Estate Agent", "Business & Finance", "/images/app/browse/real-estate-agent.webp"),
  C("Receptionist", "Business & Finance", "/images/app/browse/receptionist.webp"),
  C("Recruiter", "Business & Finance", "/images/app/browse/recruiter.webp"),
  C("Retail Sales Associate", "Business & Finance", "/images/app/browse/retail-sales-associate.webp"),
  C("Retail Store Supervisor", "Business & Finance", "/images/app/browse/retail-store-supervisor.webp"),
  C("Stockbroker", "Business & Finance", "/images/app/browse/stockbroker.webp"),
  C("Addiction Counselor", "Counseling & Social Work", "/images/app/browse/addiction-counselor.webp"),
  C("Community Health Worker", "Counseling & Social Work", "/images/app/browse/community-health-worker.webp"),
  C("Community Program Manager", "Counseling & Social Work", "/images/app/browse/community-program-manager.webp"),
  C("Family Therapist", "Counseling & Social Work", "/images/app/browse/family-therapist.webp"),
  C("Healthcare Social Worker", "Counseling & Social Work", "/images/app/browse/healthcare-social-worker.webp"),
  C("Human Services Assistant", "Counseling & Social Work", "/images/app/browse/human-services-assistant.webp"),
  C("Mental Health Social Worker", "Counseling & Social Work", "/images/app/browse/mental-health-social-worker.webp"),
  C("Probation Officer", "Counseling & Social Work", "/images/app/browse/probation-officer.webp"),
  C("Rehabilitation Counselor", "Counseling & Social Work", "/images/app/browse/rehabilitation-counselor.webp"),
  C("Social Worker", "Counseling & Social Work", "/images/app/browse/social-worker.webp"),
  C("Ambulance Driver and Attendant", "Driving, Flying & Shipping", "/images/app/browse/ambulance-driver-and-attendant.webp"),
  C("Cargo Handling Supervisor", "Driving, Flying & Shipping", "/images/app/browse/cargo-handling-supervisor.webp"),
  C("Commercial Pilot", "Driving, Flying & Shipping", "/images/app/browse/commercial-pilot.webp"),
  C("Delivery Driver", "Driving, Flying & Shipping", "/images/app/browse/delivery-driver.webp"),
  C("Demand Planner", "Driving, Flying & Shipping", "/images/app/browse/demand-planner.webp"),
  C("Driver and Sales Worker", "Driving, Flying & Shipping", "/images/app/browse/driver-and-sales-worker.webp"),
  C("Flight Attendant", "Driving, Flying & Shipping", "/images/app/browse/flight-attendant.webp"),
  C("Hand Packer", "Driving, Flying & Shipping", "/images/app/browse/hand-packer.webp"),
  C("Parking Attendant", "Driving, Flying & Shipping", "/images/app/browse/parking-attendant.webp"),
  C("Railroad Conductor", "Driving, Flying & Shipping", "/images/app/browse/railroad-conductor.webp"),
  C("Sanitation Worker", "Driving, Flying & Shipping", "/images/app/browse/sanitation-worker.webp"),
  C("Ship Captain or Mate", "Driving, Flying & Shipping", "/images/app/browse/ship-captain-or-mate.webp"),
  C("Shuttle Driver or Chauffeur", "Driving, Flying & Shipping", "/images/app/browse/shuttle-driver-or-chauffeur.webp"),
  C("Stocker and Order Picker", "Driving, Flying & Shipping", "/images/app/browse/stocker-and-order-picker.webp"),
  C("Supply Chain Manager", "Driving, Flying & Shipping", "/images/app/browse/supply-chain-manager.webp"),
  C("Transit Bus Driver", "Driving, Flying & Shipping", "/images/app/browse/transit-bus-driver.webp"),
  C("Vehicle Cleaner", "Driving, Flying & Shipping", "/images/app/browse/vehicle-cleaner.webp"),
  C("Warehouse Worker", "Driving, Flying & Shipping", "/images/app/browse/warehouse-worker.webp"),
  C("Aircraft Assembler", "Factories & Making Things", "/images/app/browse/aircraft-assembler.webp"),
  C("Apparel Production Manager", "Factories & Making Things", "/images/app/browse/apparel-production-manager.webp"),
  C("Assembly Worker", "Factories & Making Things", "/images/app/browse/assembly-worker.webp"),
  C("Cabinetmaker", "Factories & Making Things", "/images/app/browse/cabinetmaker.webp"),
  C("CNC Machinist", "Factories & Making Things", "/images/app/browse/cnc-machinist.webp"),
  C("Engine Assembler", "Factories & Making Things", "/images/app/browse/engine-assembler.webp"),
  C("Gemologist", "Factories & Making Things", "/images/app/browse/gemologist.webp"),
  C("Machinist", "Factories & Making Things", "/images/app/browse/machinist.webp"),
  C("Packaging Machine Operator", "Factories & Making Things", "/images/app/browse/packaging-machine-operator.webp"),
  C("Semiconductor Process Technician", "Factories & Making Things", "/images/app/browse/semiconductor-process-technician.webp"),
  C("Welder", "Factories & Making Things", "/images/app/browse/welder.webp"),
  C("Animal Trainer", "Farming, Animals & Nature", "/images/app/browse/animal-trainer.webp"),
  C("Farmer or Rancher", "Farming, Animals & Nature", "/images/app/browse/farmer-or-rancher.webp"),
  C("Auto Body Technician", "Fixing Machines & Engines", "/images/app/browse/auto-body-technician.webp"),
  C("Auto Mechanic", "Fixing Machines & Engines", "/images/app/browse/auto-mechanic.webp"),
  C("Aviation Maintenance Technician", "Fixing Machines & Engines", "/images/app/browse/aviation-maintenance-technician.webp"),
  C("Avionics Technician", "Fixing Machines & Engines", "/images/app/browse/avionics-technician.webp"),
  C("Biomedical Equipment Technician", "Fixing Machines & Engines", "/images/app/browse/biomedical-equipment-technician.webp"),
  C("Diesel Mechanic", "Fixing Machines & Engines", "/images/app/browse/diesel-mechanic.webp"),
  C("Heavy Equipment Mechanic", "Fixing Machines & Engines", "/images/app/browse/heavy-equipment-mechanic.webp"),
  C("HVAC Technician", "Fixing Machines & Engines", "/images/app/browse/hvac-technician.webp"),
  C("Industrial Maintenance Technician", "Fixing Machines & Engines", "/images/app/browse/industrial-maintenance-technician.webp"),
  C("Locksmith", "Fixing Machines & Engines", "/images/app/browse/locksmith.webp"),
  C("Low Voltage Technician", "Fixing Machines & Engines", "/images/app/browse/low-voltage-technician.webp"),
  C("Millwright", "Fixing Machines & Engines", "/images/app/browse/millwright.webp"),
  C("Motorcycle Mechanic", "Fixing Machines & Engines", "/images/app/browse/motorcycle-mechanic.webp"),
  C("Office Equipment Technician", "Fixing Machines & Engines", "/images/app/browse/office-equipment-technician.webp"),
  C("Power-Line Technician", "Fixing Machines & Engines", "/images/app/browse/power-line-technician.webp"),
  C("Semiconductor Equipment Technician", "Fixing Machines & Engines", "/images/app/browse/semiconductor-equipment-technician.webp"),
  C("Telecom Technician", "Fixing Machines & Engines", "/images/app/browse/telecom-technician.webp"),
  C("Wind Turbine Technician", "Fixing Machines & Engines", "/images/app/browse/wind-turbine-technician.webp"),
  C("Private Chef", "Food & Cooking", "/images/app/browse/private-chef.webp"),
  C("Dental Hygienist", "Health & Medicine", "/images/app/browse/dental-hygienist.webp"),
  C("EMT", "Health & Medicine", "/images/app/browse/emt.webp"),
  C("Family Doctor", "Health & Medicine", "/images/app/browse/family-doctor.webp"),
  C("Licensed Practical Nurse", "Health & Medicine", "/images/app/browse/licensed-practical-nurse.webp"),
  C("Medical Assistant", "Health & Medicine", "/images/app/browse/medical-assistant.webp"),
  C("Nursing Assistant", "Health & Medicine", "/images/app/browse/nursing-assistant.webp"),
  C("Physical Therapist Assistant", "Health & Medicine", "/images/app/browse/physical-therapist-assistant.webp"),
  C("Respiratory Therapist", "Health & Medicine", "/images/app/browse/respiratory-therapist.webp"),
  C("Ultrasound Technician", "Health & Medicine", "/images/app/browse/ultrasound-technician.webp"),
  C("Veterinary Technician", "Health & Medicine", "/images/app/browse/veterinary-technician.webp"),
  C("X-Ray Technologist", "Health & Medicine", "/images/app/browse/x-ray-technologist.webp"),
  C("Airport Security Screener", "Law, Safety & Justice", "/images/app/browse/airport-security-screener.webp"),
  C("Animal Control Officer", "Law, Safety & Justice", "/images/app/browse/animal-control-officer.webp"),
  C("Court Bailiff", "Law, Safety & Justice", "/images/app/browse/court-bailiff.webp"),
  C("Detective", "Law, Safety & Justice", "/images/app/browse/detective.webp"),
  C("Fire Investigator", "Law, Safety & Justice", "/images/app/browse/fire-investigator.webp"),
  C("Firefighter", "Law, Safety & Justice", "/images/app/browse/firefighter.webp"),
  C("Paralegal", "Law, Safety & Justice", "/images/app/browse/paralegal.webp"),
  C("Police Officer", "Law, Safety & Justice", "/images/app/browse/police-officer.webp"),
  C("Private Investigator", "Law, Safety & Justice", "/images/app/browse/private-investigator.webp"),
  C("Security Guard", "Law, Safety & Justice", "/images/app/browse/security-guard.webp"),
  C("Barber", "Personal Care & Community Services", "/images/app/browse/barber.webp"),
  C("Embalmer", "Personal Care & Community Services", "/images/app/browse/embalmer.webp"),
  C("Esthetician", "Personal Care & Community Services", "/images/app/browse/esthetician.webp"),
  C("Funeral Director", "Personal Care & Community Services", "/images/app/browse/funeral-director.webp"),
  C("Makeup Artist", "Personal Care & Community Services", "/images/app/browse/makeup-artist.webp"),
  C("Nail Technician", "Personal Care & Community Services", "/images/app/browse/nail-technician.webp"),
  C("Industrial-Organizational Psychologist", "Science & Research", "/images/app/browse/industrial-organizational-psychologist.webp"),
  C("Architectural & Engineering Manager", "Tech & Engineering", "/images/app/browse/architectural-and-engineering-manager.webp"),
  C("Civil Engineering Technician", "Tech & Engineering", "/images/app/browse/civil-engineering-technician.webp"),
  C("Drafter", "Tech & Engineering", "/images/app/browse/drafter.webp"),
  C("Electronics Engineering Technician", "Tech & Engineering", "/images/app/browse/electronics-engineering-technician.webp"),
  C("Game Programmer", "Tech & Engineering", "/images/app/browse/game-programmer.webp"),
  C("Industrial Engineering Technician", "Tech & Engineering", "/images/app/browse/industrial-engineering-technician.webp"),
  C("Robotics Technician", "Tech & Engineering", "/images/app/browse/robotics-technician.webp"),
];
