import path from "node:path";
import {
  FILES,
  ROOT,
  collectTokens,
  colorToCss,
  mergeTokenMaps,
  readTokenFile,
  resolveToken,
  writeIfChanged,
} from "./token-utils.mjs";

const checkOnly = process.argv.includes("--check");
const primitiveLight = collectTokens(readTokenFile(FILES.primitivesLight));
const primitiveDark = collectTokens(readTokenFile(FILES.primitivesDark));
const semanticLight = collectTokens(readTokenFile(FILES.semanticLight));
const semanticDark = collectTokens(readTokenFile(FILES.semanticDark));

const light = mergeTokenMaps(primitiveLight, semanticLight);
const dark = mergeTokenMaps(primitiveDark, semanticDark);

function colorVariables(tokens) {
  return [...tokens]
    .filter(([, token]) => token.$resolvedType === "color")
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tokenPath]) => `  --${tokenPath.replaceAll(".", "-")}: ${colorToCss(resolveToken(tokenPath, tokens))};`)
    .join("\n");
}

function foundationVariables(tokens) {
  return [...tokens]
    .filter(([, token]) => ["dimension", "duration", "fontWeight", "number"].includes(token.$resolvedType))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tokenPath]) => {
      const value = resolveToken(tokenPath, tokens);
      const cssValue = value && typeof value === "object" && Object.hasOwn(value, "unit") ? `${value.value}${value.unit}` : String(value);
      return `  --${tokenPath.replaceAll(".", "-")}: ${cssValue};`;
    })
    .join("\n");
}

const css = `/* This file is generated by npm run tokens:build. Do not edit directly. */
:root {
${colorVariables(light)}
${foundationVariables(light)}
}

.dark {
${colorVariables(dark)}
${foundationVariables(dark)}
}
`;

const stepPaths = Array.from({ length: 12 }, (_, index) => `color.step.${String(index + 1).padStart(2, "0")}.accent`);
const categoryPaths = ["classes", "skills", "workstyle", "earning-potential", "future-fit"].map((name) => `color.category.${name}`);
const howItWorksPaths = ["color.brand.400", "color.coral.500", "color.purple.400", "color.cyan.500", "color.yellow.500"];
const resolvedHex = (tokenPath) => colorToCss(resolveToken(tokenPath, light));

const typescript = `/* This file is generated by npm run tokens:build. Do not edit directly. */
export const STEP_AURORA_ACCENTS = ${JSON.stringify(stepPaths.map(resolvedHex), null, 2)} as const;

export const MATCH_CATEGORY_COLORS = ${JSON.stringify(categoryPaths.map(resolvedHex), null, 2)} as const;

export const HOW_IT_WORKS_CHAPTER_COLORS = ${JSON.stringify(howItWorksPaths.map(resolvedHex), null, 2)} as const;

export const FUTURE_VALUES_GRADIENT = {
  button: {
    from: "var(--color-step-08-button-from)",
    to: "var(--color-step-08-button-to)",
  },
  progress: {
    from: "var(--color-step-08-progress-from)",
    to: "var(--color-step-08-progress-to)",
  },
} as const;
`;

const changed = [
  writeIfChanged(path.join(ROOT, "src/app/design-tokens.generated.css"), css, checkOnly),
  writeIfChanged(path.join(ROOT, "src/generated/design-tokens.ts"), typescript, checkOnly),
].some(Boolean);

console.log(checkOnly ? "Generated token artifacts are current." : changed ? "Generated token artifacts updated." : "Generated token artifacts already current.");
