import path from "node:path";
import {
  FILES,
  ROOT,
  collectTokens,
  colorToCss,
  mergeTokenMaps,
  readTokenFile,
  resolveToken,
  writeIfChanged,
} from "./token-utils.mjs";

const checkOnly = process.argv.includes("--check");
const primitiveLight = collectTokens(readTokenFile(FILES.primitivesLight));
const primitiveDark = collectTokens(readTokenFile(FILES.primitivesDark));
const semanticLight = collectTokens(readTokenFile(FILES.semanticLight));
const semanticDark = collectTokens(readTokenFile(FILES.semanticDark));
const components = collectTokens(readTokenFile(FILES.components));

const light = mergeTokenMaps(primitiveLight, semanticLight, components);
const dark = mergeTokenMaps(primitiveDark, semanticDark, components);

function colorVariables(tokens) {
  return [...tokens]
    .filter(([, token]) => token.$resolvedType === "color")
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tokenPath]) => `  --${tokenPath.replaceAll(".", "-")}: ${colorToCss(resolveToken(tokenPath, tokens))};`)
    .join("\n");
}

// fontFamily emitted alongside the other foundations — this type previously never
// reached the generated CSS at all (nothing consumed it), but the 15-world token
// layer added for the design-system alignment carries a per-world display typeface
// that Phase 3 component work needs as a var(--font-family-world-*) binding. Array
// values render as a CSS font stack, quoting multi-word family names.
function fontFamilyCss(value) {
  const families = Array.isArray(value) ? value : [value];
  return families.map((name) => (/\s/.test(name) ? `"${name}"` : name)).join(", ");
}

function foundationVariables(tokens) {
  return [...tokens]
    .filter(([, token]) => ["dimension", "duration", "fontWeight", "number", "fontFamily"].includes(token.$resolvedType))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tokenPath]) => {
      const value = resolveToken(tokenPath, tokens);
      const token = tokens.get(tokenPath);
      const cssValue =
        token.$resolvedType === "fontFamily"
          ? fontFamilyCss(value)
          : value && typeof value === "object" && Object.hasOwn(value, "unit")
            ? `${value.value}${value.unit}`
            : String(value);
      return `  --${tokenPath.replaceAll(".", "-")}: ${cssValue};`;
    })
    .join("\n");
}

const css = `/* This file is generated by npm run tokens:build. Do not edit directly. */
:root {
${colorVariables(light)}
${foundationVariables(light)}
}

.dark {
${colorVariables(dark)}
${foundationVariables(dark)}
}
`;

const changed = [writeIfChanged(path.join(ROOT, "src/app/design-tokens.generated.css"), css, checkOnly)].some(Boolean);

console.log(checkOnly ? "Generated token artifacts are current." : changed ? "Generated token artifacts updated." : "Generated token artifacts already current.");
