// Career Detail profiles for the 4 Oct 2026 poster drop, batch 3 (BROWSE Images).
// Sourced: people, openings and change from BLS Employment Projections table
// 1.2 (2025-35), which matches the bls.gov OOH pages; pay from OEWS May 2025
// (national 10th / median / 75th / 90th percentiles, state annual means read
// from the OEWS data tool); degree mix from BLS table 5.3 (2023-24 ACS);
// how-to-become notes from the OOH; tasks, knowledge, skills and software from
// O*NET OnLine; study fields from the NCES CIP 2020 to SOC 2018 crosswalk.
// SOC codes: Anesthesiologist 29-1211, Chiropractor 29-1011, Dentist 29-1021
// (Dentists, general), Healthcare Manager 11-9111, Home Health Aide and
// Personal Care Aide 31-1120, Nutritionist 29-1031, OB-GYN 29-1218,
// Occupational Therapist 29-1122, Optometrist 29-1041, Pediatrician 29-1221,
// Pharmacist 29-1051, Physical Therapist 29-1123, Psychiatrist 29-1223,
// Radiologist 29-1224, Surgeon 29-1249, Border Protection Officer 33-3051,
// Correctional Officer 33-3012, Crossing Guard or Road Flagger 33-9091,
// Emergency Management Director 11-9161. Four are mapped to a broader group.
// Home health aides (O*NET 31-1121.00) and personal care aides (31-1122.00)
// are one group (31-1120) in both OEWS and the projections, so the two pages
// share every BLS figure. Border protection officers have no BLS occupation
// of their own; O*NET files Customs and Border Protection Officers
// (33-3051.04) under police and sheriff's patrol officers (33-3051), so the
// BLS figures are for that whole group. General surgeons are counted in
// Surgeons, all other (29-1249); O*NET has no ratings for that title, so
// tasks and software follow O*NET 29-1242.00 and 29-1243.00, the surgeon
// occupations it does describe. yourStates is South Dakota, like every other
// entry. Where OEWS shows no exact South Dakota figure (Anesthesiologist,
// Surgeon) there is no yourStates row. States with no exact figure (not
// released, or marked at or above the OEWS top wage band) could not rank.
// Ladder pay is OEWS: 10th percentile for a new worker, median for the job,
// 75th percentile for a senior worker, or the median of the matching
// occupation; school and residency rungs have no OEWS figure and show "".
import type { CareerProfile } from "./profiles";

const SOURCES = "Job description and skills from O*NET (USDOL/ETA). Pay and growth from the U.S. Bureau of Labor Statistics.";
const OPENINGS = "Counts every job that needs filling, mostly people moving on rather than brand-new roles.";
const HALF = "Half of the people in this job earn more than the typical figure and half earn less.";

const DOCTORATE_ONLY = [
  { label: "Did not finish high school", pct: 0.0 },
  { label: "Finished high school", pct: 0.0 },
  { label: "Some college, no degree", pct: 0.0 },
  { label: "Associate's degree", pct: 0.0 },
  { label: "Bachelor's degree", pct: 0.0 },
  { label: "Master's degree", pct: 0.0 },
  { label: "Doctorate or professional degree", pct: 100.0 },
];

const AIDES_MIX = [
  { label: "Did not finish high school", pct: 16.7 },
  { label: "Finished high school", pct: 35.7 },
  { label: "Some college, no degree", pct: 23.1 },
  { label: "Associate's degree", pct: 9.4 },
  { label: "Bachelor's degree", pct: 11.4 },
  { label: "Master's degree", pct: 3.1 },
  { label: "Doctorate or professional degree", pct: 0.7 },
];

const MED_SCHOOL = {
  number: "1",
  jobTitle: "Medical Student",
  pay: "",
  description: "Medical school comes after college. You learn in classrooms first, then with real patients.",
  whatYouDo: ["Study the human body", "Learn about medicines", "Take patient histories", "Pass national exams"],
  toGetHere: ["Bachelor's degree", "MCAT", "Accepted to medical school"],
};

const PHYSICIAN_DEGREE_NOTE = "After college you go to medical school, then a residency of 3 to 9 years. All states require a license.";

export const LIB3_PROFILES: Record<string, CareerProfile> = {
  anesthesiologist: {
    slug: "anesthesiologist",
    title: "Anesthesiologist",
    world: "Health & Medicine",
    photo: "/images/app/browse/anesthesiologist.webp",
    summary: "A doctor who puts patients to sleep for surgery and keeps them safe until they wake up.",
    scenario: "Imagine a patient on the table and a surgeon ready to begin. You decide how deep the sleep goes and watch every breath and heartbeat until the last stitch.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$391,490/year" },
      { label: "People doing it", value: "41,500" },
      { label: "Jobs open each year", value: "1,100" },
    ],
    // OEWS shows no exact South Dakota figure, so there is no yourStates row.
    payByState: { title: "Pay by state", best: [{ state: "Washington", pay: "$509K" }, { state: "Minnesota", pay: "$449K" }, { state: "New Hampshire", pay: "$434K" }] },
    knowAbout: ["Biology and the human body", "How medicines work in the body", "Chemistry and physics", "Math", "How people think and feel"],
    goodAt: ["Making good calls fast", "Watching closely for changes", "Solving hard problems", "Reading how patients feel", "Managing your time"],
    software: ["Epic Systems", "MEDITECH", "EDImis Anesthesia Manager", "Microsoft Excel", "Microsoft PowerPoint"],
    ladder: [
      MED_SCHOOL,
      { number: "2", jobTitle: "Anesthesiology Resident", pay: "", description: "You train in a hospital, giving anesthesia while senior doctors guide you.", whatYouDo: ["Give anesthesia with a supervisor", "Manage breathing tubes", "Watch monitors in surgery", "Care for patients after surgery"], toGetHere: ["Medical degree (MD or DO)", "Match into a residency"] },
      { number: "3", jobTitle: "Anesthesiologist", pay: "$391K", description: "You plan and give anesthesia, then keep patients safe until they recover.", whatYouDo: ["Check patients before surgery", "Give anesthesia", "Watch vital signs", "Handle emergencies"], toGetHere: ["Finish residency", "State medical license"] },
    ],
    education: { studies: [{ name: "Medicine" }, { name: "Osteopathic Medicine/Osteopathy" }, { name: "Anesthesiology Residency Program" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. Medical school and residency are the path", trainingAfterHiring: "Residency or fellowship", note: PHYSICIAN_DEGREE_NOTE, noBachelorPct: "0%", distribution: DOCTORATE_ONLY },
      pay: { starting: "$101,460", typical: "$391,490", top: "$557,130", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +1,500 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  chiropractor: {
    slug: "chiropractor",
    title: "Chiropractor",
    world: "Health & Medicine",
    photo: "/images/app/browse/chiropractor.webp",
    summary: "Treats back, neck and joint pain by adjusting the spine and other joints.",
    scenario: "Imagine a mail carrier walks in bent over with back pain. You find what is out of line, adjust it and show her stretches so she can finish her route.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$79,200/year" },
      { label: "People doing it", value: "61,700" },
      { label: "Jobs open each year", value: "2,600" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$84K" }], best: [{ state: "New Jersey", pay: "$126K" }, { state: "New York", pay: "$125K" }, { state: "Alaska", pay: "$120K" }] },
    knowAbout: ["Medicine and the spine", "Biology and the human body", "Helping customers", "Therapy and counseling", "Running a business"],
    goodAt: ["Listening closely to patients", "Explaining care in plain words", "Solving hard problems", "Making good calls", "Teaching healthy habits"],
    software: ["ChiroWrite", "Chiropractic Advantage", "EZClaim medical billing", "Microsoft Office", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Chiropractic Student", pay: "", description: "A Doctor of Chiropractic program usually takes 4 years, with supervised clinic work.", whatYouDo: ["Study anatomy", "Learn spinal exams", "Practice adjustments", "Treat patients with a supervisor"], toGetHere: ["At least 3 years of college", "Science classes"] },
      { number: "2", jobTitle: "Chiropractor", pay: "$79K", description: "You examine patients, adjust the spine and help them move without pain.", whatYouDo: ["Take health histories", "Read x-rays", "Adjust the spine", "Teach exercises"], toGetHere: ["Doctor of Chiropractic degree", "State license"] },
      { number: "3", jobTitle: "Senior Chiropractor", pay: "$105K", description: "You see a full list of patients, may focus on a specialty and may run your own clinic.", whatYouDo: ["Treat complex cases", "Focus on a specialty", "Run a clinic", "Guide newer chiropractors"], toGetHere: ["Years of practice", "A specialty program helps"] },
    ],
    education: { studies: [{ name: "Chiropractic" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "You need a Doctor of Chiropractic degree, which usually takes 4 years. Most people finish a bachelor's in a science first.", noBachelorPct: "4%", distribution: [{ label: "Did not finish high school", pct: 0.5 }, { label: "Finished high school", pct: 1.8 }, { label: "Some college, no degree", pct: 1.1 }, { label: "Associate's degree", pct: 0.5 }, { label: "Bachelor's degree", pct: 6.0 }, { label: "Master's degree", pct: 2.6 }, { label: "Doctorate or professional degree", pct: 87.5 }] },
      pay: { starting: "$43,460", typical: "$79,200", top: "$146,080", note: "About a third of chiropractors work for themselves, and BLS pay figures do not count them." },
      openings: { note: `${OPENINGS} The job itself changes by about +5,300 by 2035. It is growing much faster than most jobs.` },
    },
  },
  dentist: {
    slug: "dentist",
    title: "Dentist",
    world: "Health & Medicine",
    photo: "/images/app/browse/dentist.webp",
    summary: "Finds and treats problems with teeth and gums and helps people keep a healthy smile.",
    scenario: "Imagine a kid comes in with a toothache before a big game. You find the cavity, numb the tooth and fix it so he leaves smiling.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$170,950/year" },
      { label: "People doing it", value: "141,900" },
      { label: "Jobs open each year", value: "4,200" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$164K" }], best: [{ state: "Missouri", pay: "$242K" }, { state: "Oregon", pay: "$240K" }, { state: "Maine", pay: "$237K" }] },
    knowAbout: ["Teeth, gums and medicine", "Biology and the human body", "Helping customers", "Running an office", "Chemistry"],
    goodAt: ["Making good calls", "Steady, careful hand work", "Reading how patients feel", "Solving hard problems", "Leading a small team"],
    software: ["Henry Schein Dentrix", "eClinicalWorks", "AlphaDent", "Microsoft Office", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Dental Student", pay: "", description: "In dental school you study, then treat real patients with a licensed dentist watching.", whatYouDo: ["Study anatomy", "Learn to numb teeth", "Read x-rays", "Treat patients with a supervisor"], toGetHere: ["Bachelor's degree", "Dental school entrance exam"] },
      { number: "2", jobTitle: "Dentist", pay: "$171K", description: "You examine teeth, fix cavities and help patients keep their mouths healthy.", whatYouDo: ["Examine teeth and gums", "Fill cavities", "Fit bridges and crowns", "Teach good brushing habits"], toGetHere: ["DDS or DMD degree", "State license"] },
      { number: "3", jobTitle: "Orthodontist", pay: "$289K", description: "You straighten teeth and jaws after extra years of specialty training.", whatYouDo: ["Plan braces", "Fit aligners", "Track how teeth move", "Lead a team"], toGetHere: ["Dental degree", "A 2 to 4 year specialty residency"] },
    ],
    education: { studies: [{ name: "Dentistry" }, { name: "Advanced General Dentistry" }, { name: "Pediatric Dentistry/Pedodontics" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "You need a dental degree (DDS or DMD). Most people finish a bachelor's in a science like biology first.", noBachelorPct: "0%", distribution: [{ label: "Did not finish high school", pct: 0.0 }, { label: "Finished high school", pct: 0.0 }, { label: "Some college, no degree", pct: 0.0 }, { label: "Associate's degree", pct: 0.0 }, { label: "Bachelor's degree", pct: 0.0 }, { label: "Master's degree", pct: 3.1 }, { label: "Doctorate or professional degree", pct: 96.9 }] },
      pay: { starting: "$86,250", typical: "$170,950", top: "$319,630", note: "These figures are for general dentists. Specialists like orthodontists tend to earn more." },
      openings: { note: `${OPENINGS} The job itself changes by about +8,100 by 2035. It is growing faster than most jobs.` },
    },
  },
  "healthcare-manager": {
    slug: "healthcare-manager",
    title: "Healthcare Manager",
    world: "Health & Medicine",
    photo: "/images/app/browse/healthcare-manager.webp",
    summary: "Runs the business side of a hospital, clinic or care home so doctors and nurses can focus on patients.",
    scenario: "Imagine flu season hits and your clinic is short on nurses. You rework the schedule, move the budget and keep every patient seen on time.",
    facts: [
      { label: "Typical degree", value: "Bachelor's degree" },
      { label: "Typical pay", value: "$123,860/year" },
      { label: "People doing it", value: "640,400" },
      { label: "Jobs open each year", value: "62,300" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$131K" }], best: [{ state: "New York", pay: "$185K" }, { state: "New Jersey", pay: "$178K" }, { state: "Oregon", pay: "$167K" }] },
    knowAbout: ["Running a team or a business", "Clear writing", "Helping patients and families", "Hiring and training people", "Computers"],
    goodAt: ["Leading people", "Making good calls", "Solving hard problems", "Managing your time", "Keeping work on track"],
    software: ["Epic Systems", "MEDITECH", "Tableau", "Microsoft Excel", "Microsoft Project"],
    ladder: [
      { number: "1", jobTitle: "Medical Records Specialist", pay: "$51K", description: "You keep patient records in order and learn how a hospital runs.", whatYouDo: ["Organize patient records", "Code health data", "Check records for errors", "Work with billing"], toGetHere: ["Certificate or associate's degree"] },
      { number: "2", jobTitle: "Healthcare Manager", pay: "$124K", description: "You run a department or a clinic, from staff schedules to the budget.", whatYouDo: ["Set staff schedules", "Plan the budget", "Hire and train staff", "Follow health rules"], toGetHere: ["Bachelor's degree", "Time in a hospital or clinic"] },
      { number: "3", jobTitle: "Hospital Administrator", pay: "$166K", description: "You lead a whole facility and plan where it goes next.", whatYouDo: ["Lead department heads", "Plan for the future", "Manage big budgets", "Work with doctors and the board"], toGetHere: ["Years as a manager", "A master's degree helps"] },
    ],
    education: { studies: [{ name: "Health/Health Care Administration/Management" }, { name: "Hospital and Health Care Facilities Administration/Management" }, { name: "Health Information/Medical Records Administration/Administrator" }, { name: "Public Health, General" }, { name: "Nursing Administration" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "Yes. Usually a few years in a hospital or clinic", trainingAfterHiring: "None required", note: "Most start with a bachelor's in health administration, nursing or business. Some jobs ask for a master's.", noBachelorPct: "36%", distribution: [{ label: "Did not finish high school", pct: 1.4 }, { label: "Finished high school", pct: 9.3 }, { label: "Some college, no degree", pct: 14.1 }, { label: "Associate's degree", pct: 10.7 }, { label: "Bachelor's degree", pct: 32.2 }, { label: "Master's degree", pct: 25.0 }, { label: "Doctorate or professional degree", pct: 7.3 }] },
      pay: { starting: "$73,390", typical: "$123,860", top: "$224,340", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +155,100 by 2035. It is growing much faster than most jobs.` },
    },
  },
  "home-health-aide": {
    slug: "home-health-aide",
    title: "Home Health Aide",
    world: "Health & Medicine",
    photo: "/images/app/browse/home-health-aide.webp",
    summary: "Helps older adults and people with illness or disability live safely at home.",
    scenario: "Imagine a grandfather just home from the hospital. You check his pulse, help him walk to the kitchen and make the lunch his doctor ordered.",
    facts: [
      { label: "Typical degree", value: "High school diploma or equivalent" },
      { label: "Typical pay", value: "$35,800/year" },
      { label: "People doing it", value: "4,677,100" },
      { label: "Jobs open each year", value: "760,500" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$39K" }], best: [{ state: "Washington", pay: "$48K" }, { state: "Oregon", pay: "$45K" }, { state: "District of Columbia", pay: "$43K" }] },
    knowAbout: ["How people think and feel", "Helping clients and families", "Basic health care", "Safety", "Clear speaking and writing"],
    goodAt: ["Caring for people", "Reading how people feel", "Managing your time", "Teaching simple steps", "Noticing changes in a patient"],
    software: ["Microsoft Outlook", "Microsoft SharePoint", "Microsoft Access", "Salesforce", "Mi-Co forms software"],
    ladder: [
      { number: "1", jobTitle: "New Home Health Aide", pay: "$27K", description: "You learn the basics of care while a nurse or supervisor checks in on your work.", whatYouDo: ["Help with bathing and dressing", "Make simple meals", "Keep the home clean", "Write care notes"], toGetHere: ["High school diploma", "Short training"] },
      { number: "2", jobTitle: "Home Health Aide", pay: "$36K", description: "You care for clients on your own and report changes to the nurse.", whatYouDo: ["Check pulse and breathing", "Help clients move safely", "Remind clients about medicine", "Drive to appointments"], toGetHere: ["State certificate where required", "CPR and first aid"] },
      { number: "3", jobTitle: "Licensed Practical Nurse", pay: "$64K", description: "You give basic nursing care in homes, clinics and care centers.", whatYouDo: ["Give medicine", "Change bandages", "Track vital signs", "Work with RNs and doctors"], toGetHere: ["Practical nursing program", "Pass the NCLEX-PN"] },
    ],
    education: { studies: [{ name: "Home Health Aide/Home Attendant" }], where: [{ count: "", credential: "Trade school certificate" }] },
    sources: `${SOURCES} BLS counts home health aides and personal care aides as one group (SOC 31-1120), so pay and job counts are for both.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "Short on-the-job training", note: "Most aides have a high school diploma. Some states ask for a certificate, and agencies paid by Medicare follow federal training rules.", noBachelorPct: "85%", distribution: AIDES_MIX },
      pay: { starting: "$27,040", typical: "$35,800", top: "$45,040", note: "BLS counts home health aides and personal care aides as one group, so these figures are for both." },
      openings: { note: `${OPENINGS} The job itself changes by about +847,300 by 2035. It is growing much faster than most jobs.` },
    },
  },
  nutritionist: {
    slug: "nutritionist",
    title: "Nutritionist",
    world: "Health & Medicine",
    photo: "/images/app/browse/nutritionist.webp",
    summary: "Helps people eat in ways that keep them healthy or help them heal.",
    scenario: "Imagine a teen just found out she has diabetes. You build a meal plan with foods she likes so she can manage it and still eat with her friends.",
    facts: [
      { label: "Typical degree", value: "Bachelor's degree" },
      { label: "Typical pay", value: "$76,400/year" },
      { label: "People doing it", value: "86,300" },
      { label: "Jobs open each year", value: "5,700" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$68K" }], best: [{ state: "California", pay: "$99K" }, { state: "Alaska", pay: "$88K" }, { state: "New Jersey", pay: "$87K" }] },
    knowAbout: ["Biology and the human body", "Food and medicine", "Counseling", "How people think and feel", "Teaching and training"],
    goodAt: ["Listening closely", "Making good calls", "Reading how people feel", "Explaining things in plain words", "Helping people change habits"],
    software: ["Nutritionist Pro", "DietMaster Pro", "FoodWorks", "Microsoft Excel", "Microsoft PowerPoint"],
    ladder: [
      { number: "1", jobTitle: "Dietetic Intern", pay: "", description: "You train under a registered dietitian in a hospital, clinic or school.", whatYouDo: ["Review patient charts", "Plan meals", "Counsel patients with a supervisor", "Teach nutrition classes"], toGetHere: ["Degree in dietetics or nutrition", "Accepted to an internship"] },
      { number: "2", jobTitle: "Dietitian or Nutritionist", pay: "$76K", description: "You plan diets that help people stay healthy or recover from illness.", whatYouDo: ["Check nutrition needs", "Build meal plans", "Counsel clients", "Track progress"], toGetHere: ["Supervised internship", "State license where required"] },
      { number: "3", jobTitle: "Senior Dietitian", pay: "$89K", description: "You handle harder cases, lead programs and train new dietitians.", whatYouDo: ["Treat complex cases", "Lead nutrition programs", "Train interns", "Work with doctors"], toGetHere: ["Years of practice", "RDN credential"] },
    ],
    education: { studies: [{ name: "Dietetics/Dietitian" }, { name: "Clinical Nutrition/Nutritionist" }, { name: "Human Nutrition" }, { name: "Nutrition Sciences" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "Supervised internship", note: "You need a bachelor's or master's in dietetics or nutrition, plus a supervised internship. The RDN credential takes a master's.", noBachelorPct: "21%", distribution: [{ label: "Did not finish high school", pct: 2.1 }, { label: "Finished high school", pct: 8.5 }, { label: "Some college, no degree", pct: 6.4 }, { label: "Associate's degree", pct: 3.6 }, { label: "Bachelor's degree", pct: 37.6 }, { label: "Master's degree", pct: 34.1 }, { label: "Doctorate or professional degree", pct: 7.7 }] },
      pay: { starting: "$49,090", typical: "$76,400", top: "$103,720", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +6,700 by 2035. It is growing much faster than most jobs.` },
    },
  },
  "ob-gyn": {
    slug: "ob-gyn",
    title: "OB-GYN",
    world: "Health & Medicine",
    photo: "/images/app/browse/ob-gyn.webp",
    summary: "A doctor who cares for women's health and delivers babies.",
    scenario: "Imagine it is 3 a.m. and a baby is on the way. You guide the mom through every step and hand her a healthy newborn.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$292,910/year" },
      { label: "People doing it", value: "22,800" },
      { label: "Jobs open each year", value: "500" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$307K" }], best: [{ state: "Louisiana", pay: "$398K" }, { state: "Utah", pay: "$386K" }, { state: "Vermont", pay: "$377K" }] },
    knowAbout: ["Medicine and treatments", "Biology and the human body", "Clear speaking and writing", "How people think and feel", "Counseling"],
    goodAt: ["Solving hard problems", "Making good calls", "Working well with a team", "Reading how patients feel", "Managing your time"],
    software: ["Epic Systems", "eClinicalWorks", "MEDITECH", "Microsoft Office", "Microsoft Excel"],
    ladder: [
      MED_SCHOOL,
      { number: "2", jobTitle: "OB-GYN Resident", pay: "", description: "You train in a hospital, delivering babies and doing surgery with senior doctors.", whatYouDo: ["Deliver babies", "Assist in surgery", "See clinic patients", "Take night call"], toGetHere: ["Medical degree (MD or DO)", "Match into a residency"] },
      { number: "3", jobTitle: "OB-GYN", pay: "$293K", description: "You care for women through pregnancy, birth and every stage of health.", whatYouDo: ["Check on pregnancies", "Deliver babies", "Do surgery like C-sections", "Treat health problems"], toGetHere: ["Finish residency", "State medical license"] },
    ],
    education: { studies: [{ name: "Medicine" }, { name: "Osteopathic Medicine/Osteopathy" }, { name: "Obstetrics and Gynecology Residency Program" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. Medical school and residency are the path", trainingAfterHiring: "Residency or fellowship", note: PHYSICIAN_DEGREE_NOTE, noBachelorPct: "0%", distribution: DOCTORATE_ONLY },
      pay: { starting: "$94,680", typical: "$292,910", top: "$437,300", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +400 by 2035. It is growing, but more slowly than most jobs.` },
    },
  },
  "occupational-therapist": {
    slug: "occupational-therapist",
    title: "Occupational Therapist",
    world: "Health & Medicine",
    photo: "/images/app/browse/occupational-therapist.webp",
    summary: "Helps people of all ages do everyday tasks after an injury, illness or disability.",
    scenario: "Imagine a chef who hurt his hand and cannot hold a knife. You plan the exercises and tools that get him back in the kitchen.",
    facts: [
      { label: "Typical degree", value: "Master's degree" },
      { label: "Typical pay", value: "$100,330/year" },
      { label: "People doing it", value: "169,600" },
      { label: "Jobs open each year", value: "10,000" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$88K" }], best: [{ state: "California", pay: "$122K" }, { state: "Nevada", pay: "$112K" }, { state: "Oregon", pay: "$112K" }] },
    knowAbout: ["Therapy and counseling", "How people think and feel", "Helping clients and families", "Medicine and the human body", "Teaching and training"],
    goodAt: ["Helping people", "Teaching new skills", "Making good calls", "Reading how people feel", "Watching progress closely"],
    software: ["eClinicalWorks", "Boardmaker", "Text-to-speech software", "Microsoft Office", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "OT Student", pay: "", description: "A master's program of 2 to 3 years, with supervised fieldwork in real clinics.", whatYouDo: ["Study anatomy", "Learn therapy methods", "Work with clients in fieldwork", "Write care plans"], toGetHere: ["Bachelor's degree", "Biology and psychology classes"] },
      { number: "2", jobTitle: "Occupational Therapist", pay: "$100K", description: "You test what clients can do and plan therapy that builds daily skills.", whatYouDo: ["Test clients' abilities", "Plan therapy", "Fit special tools", "Train family caregivers"], toGetHere: ["Master's in occupational therapy", "State license"] },
      { number: "3", jobTitle: "Senior Occupational Therapist", pay: "$117K", description: "You take harder cases, focus on a specialty and guide newer therapists.", whatYouDo: ["Treat complex cases", "Focus on a specialty", "Guide new OTs", "Lead programs"], toGetHere: ["Years of practice", "Continuing education"] },
    ],
    education: { studies: [{ name: "Occupational Therapy/Therapist" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Master's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "You need a master's in occupational therapy, which takes 2 to 3 years. All states require a license.", noBachelorPct: "5%", distribution: [{ label: "Did not finish high school", pct: 0.8 }, { label: "Finished high school", pct: 0.9 }, { label: "Some college, no degree", pct: 0.9 }, { label: "Associate's degree", pct: 2.8 }, { label: "Bachelor's degree", pct: 27.9 }, { label: "Master's degree", pct: 54.9 }, { label: "Doctorate or professional degree", pct: 11.8 }] },
      pay: { starting: "$71,690", typical: "$100,330", top: "$131,950", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +25,200 by 2035. It is growing much faster than most jobs.` },
    },
  },
  optometrist: {
    slug: "optometrist",
    title: "Optometrist",
    world: "Health & Medicine",
    photo: "/images/app/browse/optometrist.webp",
    summary: "Checks people's eyes, treats eye problems and prescribes glasses and contacts.",
    scenario: "Imagine a fourth grader who keeps squinting at the board. You find the problem, fit his first glasses and watch him read the far wall.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$136,570/year" },
      { label: "People doing it", value: "45,100" },
      { label: "Jobs open each year", value: "2,000" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$118K" }], best: [{ state: "Alaska", pay: "$165K" }, { state: "New Jersey", pay: "$161K" }, { state: "North Carolina", pay: "$161K" }] },
    knowAbout: ["Eyes and medicine", "Biology and the human body", "Helping patients", "Math", "Teaching patients"],
    goodAt: ["Listening closely to patients", "Solving hard problems", "Reading how patients feel", "Making good calls", "Explaining care in plain words"],
    software: ["MaximEyes", "Eyecom", "Acuity Pro", "Intuit QuickBooks", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Optometry Student", pay: "", description: "A Doctor of Optometry program takes 4 years, with classes and clinic work.", whatYouDo: ["Study the eye", "Learn eye exams", "Treat patients with a supervisor", "Pass national boards"], toGetHere: ["At least 3 years of college", "Entrance exam"] },
      { number: "2", jobTitle: "Optometrist", pay: "$137K", description: "You run eye exams, prescribe lenses and treat eye diseases.", whatYouDo: ["Test vision", "Prescribe glasses and contacts", "Treat eye diseases", "Refer patients to surgeons"], toGetHere: ["Doctor of Optometry degree", "State license"] },
      { number: "3", jobTitle: "Senior Optometrist", pay: "$165K", description: "You take on a specialty like contact lenses or eye disease, or run a practice.", whatYouDo: ["Treat complex cases", "Focus on a specialty", "Run a practice", "Guide newer optometrists"], toGetHere: ["Years of practice", "A 1 year residency helps"] },
    ],
    education: { studies: [{ name: "Optometry" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "You need a Doctor of Optometry degree, which takes 4 years. Most people finish a bachelor's in a science first.", noBachelorPct: "0%", distribution: [{ label: "Did not finish high school", pct: 0.0 }, { label: "Finished high school", pct: 0.0 }, { label: "Some college, no degree", pct: 0.0 }, { label: "Associate's degree", pct: 0.0 }, { label: "Bachelor's degree", pct: 0.0 }, { label: "Master's degree", pct: 2.6 }, { label: "Doctorate or professional degree", pct: 97.4 }] },
      pay: { starting: "$74,870", typical: "$136,570", top: "$202,180", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +4,300 by 2035. It is growing much faster than most jobs.` },
    },
  },
  pediatrician: {
    slug: "pediatrician",
    title: "Pediatrician",
    world: "Health & Medicine",
    photo: "/images/app/browse/pediatrician.webp",
    summary: "A doctor who keeps babies, kids and teens healthy and treats them when they are sick.",
    scenario: "Imagine a worried parent carries in a toddler with a high fever. You find the cause, calm the family and send them home with a plan.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$210,040/year" },
      { label: "People doing it", value: "42,200" },
      { label: "Jobs open each year", value: "1,000" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$288K" }], best: [{ state: "Louisiana", pay: "$378K" }, { state: "South Dakota", pay: "$288K" }, { state: "Montana", pay: "$285K" }] },
    knowAbout: ["Medicine and treatments", "Therapy and counseling", "Biology and the human body", "How kids think and feel", "Helping families"],
    goodAt: ["Making good calls", "Solving hard problems", "Reading how people feel", "Explaining care to parents", "Teaching healthy habits"],
    software: ["Epic Systems", "eClinicalWorks", "MEDITECH", "Drug reference software", "Microsoft Access"],
    ladder: [
      MED_SCHOOL,
      { number: "2", jobTitle: "Pediatric Resident", pay: "", description: "You train in a children's hospital and clinic while senior doctors guide you.", whatYouDo: ["Examine kids", "Order tests", "Care for newborns", "Take night call"], toGetHere: ["Medical degree (MD or DO)", "Match into a residency"] },
      { number: "3", jobTitle: "Pediatrician", pay: "$210K", description: "You track how kids grow, give checkups and shots, and treat illness.", whatYouDo: ["Give checkups", "Give vaccines", "Treat illness", "Advise parents"], toGetHere: ["Finish residency", "State medical license"] },
    ],
    education: { studies: [{ name: "Medicine" }, { name: "Osteopathic Medicine/Osteopathy" }, { name: "Pediatrics Residency Program" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. Medical school and residency are the path", trainingAfterHiring: "Residency or fellowship", note: PHYSICIAN_DEGREE_NOTE, noBachelorPct: "0%", distribution: DOCTORATE_ONLY },
      pay: { starting: "$91,470", typical: "$210,040", top: "$338,500", note: "These figures are for general pediatricians." },
      openings: { note: `${OPENINGS} The job itself changes by about +600 by 2035. It is growing, but more slowly than most jobs.` },
    },
  },
  "personal-care-aide": {
    slug: "personal-care-aide",
    title: "Personal Care Aide",
    world: "Health & Medicine",
    photo: "/images/app/browse/personal-care-aide.webp",
    summary: "Helps people who are older or have a disability with daily life, like meals, cleaning and errands.",
    scenario: "Imagine a woman who uses a wheelchair wants to get to her grandson's game. You help her get ready, drive her there and get her home safe.",
    facts: [
      { label: "Typical degree", value: "High school diploma or equivalent" },
      { label: "Typical pay", value: "$35,800/year" },
      { label: "People doing it", value: "4,677,100" },
      { label: "Jobs open each year", value: "760,500" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$39K" }], best: [{ state: "Washington", pay: "$48K" }, { state: "Oregon", pay: "$45K" }, { state: "District of Columbia", pay: "$43K" }] },
    knowAbout: ["Helping clients and families", "Clear speaking and writing", "Getting around town", "Teaching simple tasks", "How people think and feel"],
    goodAt: ["Caring for people", "Reading how people feel", "Working with a care team", "Teaching simple steps", "Managing your time"],
    software: ["MEDITECH", "Visit Wizard scheduling", "Mi-Forms", "Appletree training software", "Email"],
    ladder: [
      { number: "1", jobTitle: "New Personal Care Aide", pay: "$27K", description: "You learn how to help clients at home while a supervisor checks in.", whatYouDo: ["Help with bathing and dressing", "Cook and clean", "Run errands", "Keep care notes"], toGetHere: ["High school diploma", "Short training"] },
      { number: "2", jobTitle: "Personal Care Aide", pay: "$36K", description: "You care for your own clients and tell the team when something changes.", whatYouDo: ["Help clients move", "Plan meals", "Give company and support", "Join care meetings"], toGetHere: ["Time as an aide", "CPR and first aid"] },
      { number: "3", jobTitle: "Nursing Assistant", pay: "$42K", description: "You give hands-on care in hospitals and care centers with nurses.", whatYouDo: ["Take vital signs", "Help patients eat", "Turn and move patients", "Report to nurses"], toGetHere: ["State-approved training", "Pass a state exam"] },
    ],
    education: { studies: [{ name: "Home Health Aide/Home Attendant" }], where: [{ count: "", credential: "Trade school certificate" }] },
    sources: `${SOURCES} BLS counts personal care aides and home health aides as one group (SOC 31-1120), so pay and job counts are for both.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "Short on-the-job training", note: "Most aides have a high school diploma, and some jobs need none. Some states ask for training or a certificate.", noBachelorPct: "85%", distribution: AIDES_MIX },
      pay: { starting: "$27,040", typical: "$35,800", top: "$45,040", note: "BLS counts personal care aides and home health aides as one group, so these figures are for both." },
      openings: { note: `${OPENINGS} The job itself changes by about +847,300 by 2035. It is growing much faster than most jobs.` },
    },
  },
  pharmacist: {
    slug: "pharmacist",
    title: "Pharmacist",
    world: "Health & Medicine",
    photo: "/images/app/browse/pharmacist.webp",
    summary: "Fills prescriptions and makes sure each medicine is safe and right for the patient.",
    scenario: "Imagine a new prescription comes in that could clash with a patient's heart medicine. You catch it, call the doctor and fix it before it reaches her.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$140,910/year" },
      { label: "People doing it", value: "325,200" },
      { label: "Jobs open each year", value: "12,500" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$142K" }], best: [{ state: "California", pay: "$162K" }, { state: "Alaska", pay: "$161K" }, { state: "Oregon", pay: "$159K" }] },
    knowAbout: ["Medicine and how drugs work", "Clear speaking and writing", "Biology", "Math", "Chemistry"],
    goodAt: ["Checking details carefully", "Solving hard problems", "Making good calls", "Helping customers", "Managing your time"],
    software: ["Epic Systems", "Pyxis MedStation", "MEDITECH", "eClinicalWorks", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Pharmacy Technician", pay: "$46K", description: "You count, label and package medicine while a pharmacist checks your work.", whatYouDo: ["Fill prescriptions", "Label bottles", "Track stock", "Help customers"], toGetHere: ["High school diploma", "Training or certificate"] },
      { number: "2", jobTitle: "Pharmacist", pay: "$141K", description: "You check every prescription and teach patients how to take their medicine.", whatYouDo: ["Review prescriptions", "Check for drug clashes", "Explain side effects", "Give flu shots"], toGetHere: ["Doctor of Pharmacy degree", "State license"] },
      { number: "3", jobTitle: "Clinical Pharmacist", pay: "$162K", description: "You work with hospital teams to choose the right medicine for each patient.", whatYouDo: ["Join patient rounds", "Advise doctors", "Mix IV medicines", "Watch drug results"], toGetHere: ["Years as a pharmacist", "A residency helps"] },
    ],
    education: { studies: [{ name: "Pharmacy" }, { name: "Clinical, Hospital, and Managed Care Pharmacy" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "You need a Doctor of Pharmacy degree, which usually takes 4 years. All states require a license.", noBachelorPct: "2%", distribution: [{ label: "Did not finish high school", pct: 0.0 }, { label: "Finished high school", pct: 0.0 }, { label: "Some college, no degree", pct: 0.9 }, { label: "Associate's degree", pct: 0.6 }, { label: "Bachelor's degree", pct: 21.1 }, { label: "Master's degree", pct: 5.4 }, { label: "Doctorate or professional degree", pct: 72.0 }] },
      pay: { starting: "$99,290", typical: "$140,910", top: "$174,230", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +17,100 by 2035. It is growing faster than most jobs.` },
    },
  },
  "physical-therapist": {
    slug: "physical-therapist",
    title: "Physical Therapist",
    world: "Health & Medicine",
    photo: "/images/app/browse/physical-therapist.webp",
    summary: "Helps people move better and hurt less after an injury, surgery or illness.",
    scenario: "Imagine a runner six weeks after knee surgery who wants to race again. You plan each exercise and cheer her through her first jog back.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$102,760/year" },
      { label: "People doing it", value: "283,700" },
      { label: "Jobs open each year", value: "13,400" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$93K" }], best: [{ state: "California", pay: "$123K" }, { state: "Nevada", pay: "$121K" }, { state: "Alaska", pay: "$116K" }] },
    knowAbout: ["Helping patients", "Therapy and counseling", "Medicine and the human body", "How people think and feel", "Teaching and training"],
    goodAt: ["Helping people", "Reading how people feel", "Making good calls", "Managing your time", "Teaching exercises"],
    software: ["eClinicalWorks", "MEDITECH", "Clinicient Insight", "Microsoft Outlook", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Physical Therapy Aide", pay: "$35K", description: "You set up equipment and help patients while a therapist leads the session.", whatYouDo: ["Set up equipment", "Clean treatment areas", "Help patients move", "Schedule visits"], toGetHere: ["High school diploma", "On-the-job training"] },
      { number: "2", jobTitle: "Physical Therapist", pay: "$103K", description: "You test how patients move and build plans that cut pain and build strength.", whatYouDo: ["Examine patients", "Plan treatment", "Guide exercises", "Track progress"], toGetHere: ["Doctor of Physical Therapy degree", "State license"] },
      { number: "3", jobTitle: "Senior Physical Therapist", pay: "$121K", description: "You focus on a specialty like sports or older adults and guide newer therapists.", whatYouDo: ["Treat complex cases", "Focus on a specialty", "Guide new PTs", "Lead a clinic"], toGetHere: ["Years of practice", "A residency helps"] },
    ],
    education: { studies: [{ name: "Physical Therapy/Therapist" }, { name: "Kinesiotherapy/Kinesiotherapist" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "You need a Doctor of Physical Therapy degree, which usually takes 3 years. All states require a license.", noBachelorPct: "5%", distribution: [{ label: "Did not finish high school", pct: 0.4 }, { label: "Finished high school", pct: 1.3 }, { label: "Some college, no degree", pct: 1.0 }, { label: "Associate's degree", pct: 2.6 }, { label: "Bachelor's degree", pct: 22.0 }, { label: "Master's degree", pct: 17.3 }, { label: "Doctorate or professional degree", pct: 55.5 }] },
      pay: { starting: "$77,140", typical: "$102,760", top: "$135,140", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +33,800 by 2035. It is growing much faster than most jobs.` },
    },
  },
  psychiatrist: {
    slug: "psychiatrist",
    title: "Psychiatrist",
    world: "Health & Medicine",
    photo: "/images/app/browse/psychiatrist.webp",
    summary: "A doctor who finds and treats mental health conditions with therapy and medicine.",
    scenario: "Imagine a college student who cannot sleep or focus before finals. You listen, find what is going on and build a plan that helps him feel like himself again.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$281,870/year" },
      { label: "People doing it", value: "30,000" },
      { label: "Jobs open each year", value: "900" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$270K" }], best: [{ state: "Missouri", pay: "$346K" }, { state: "Minnesota", pay: "$333K" }, { state: "Florida", pay: "$328K" }] },
    knowAbout: ["Medicine and treatments", "Therapy and counseling", "How people think and feel", "Biology and the human body", "Clear speaking and writing"],
    goodAt: ["Listening closely", "Reading how people feel", "Making good calls", "Solving hard problems", "Working with a care team"],
    software: ["Epic Systems", "eClinicalWorks", "MEDITECH", "Microsoft Office", "Microsoft Outlook"],
    ladder: [
      MED_SCHOOL,
      { number: "2", jobTitle: "Psychiatry Resident", pay: "", description: "You train in hospitals and clinics, treating patients while senior doctors guide you.", whatYouDo: ["Talk with patients", "Prescribe medicine with a supervisor", "Lead therapy sessions", "Work with care teams"], toGetHere: ["Medical degree (MD or DO)", "Match into a residency"] },
      { number: "3", jobTitle: "Psychiatrist", pay: "$282K", description: "You diagnose mental health conditions and treat them with therapy and medicine.", whatYouDo: ["Assess patients", "Prescribe medicine", "Lead therapy", "Work with counselors"], toGetHere: ["Finish residency", "State medical license"] },
    ],
    education: { studies: [{ name: "Medicine" }, { name: "Osteopathic Medicine/Osteopathy" }, { name: "Psychiatry Residency Program" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. Medical school and residency are the path", trainingAfterHiring: "Residency or fellowship", note: PHYSICIAN_DEGREE_NOTE, noBachelorPct: "0%", distribution: DOCTORATE_ONLY },
      pay: { starting: "$84,060", typical: "$281,870", top: "$446,520", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +2,100 by 2035. It is growing much faster than most jobs.` },
    },
  },
  radiologist: {
    slug: "radiologist",
    title: "Radiologist",
    world: "Health & Medicine",
    photo: "/images/app/browse/radiologist.webp",
    summary: "A doctor who reads x-rays, MRIs and other scans to find what is wrong inside the body.",
    scenario: "Imagine an ER doctor sends you a scan of a car crash patient. You spot the hidden bleed in minutes so the surgeons know where to go.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$420,860/year" },
      { label: "People doing it", value: "28,700" },
      { label: "Jobs open each year", value: "700" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$535K" }], best: [{ state: "North Dakota", pay: "$556K" }, { state: "South Dakota", pay: "$535K" }, { state: "Minnesota", pay: "$528K" }] },
    knowAbout: ["Medicine and imaging", "Biology and the human body", "Clear speaking and writing", "Computers", "Physics"],
    goodAt: ["Making good calls", "Solving hard problems", "Spotting small details", "Explaining results to doctors", "Managing your time"],
    software: ["Epic Systems", "GE Healthcare Centricity", "MEDITECH", "eClinicalWorks", "Image processing software"],
    ladder: [
      MED_SCHOOL,
      { number: "2", jobTitle: "Radiology Resident", pay: "", description: "You train in a hospital, reading scans that senior radiologists check.", whatYouDo: ["Read scans", "Write reports", "Assist with procedures", "Present cases"], toGetHere: ["Medical degree (MD or DO)", "Match into a residency"] },
      { number: "3", jobTitle: "Radiologist", pay: "$421K", description: "You read medical images and tell other doctors what you find.", whatYouDo: ["Read x-rays, CT and MRI", "Write reports", "Guide some procedures", "Talk with care teams"], toGetHere: ["Finish residency", "State medical license"] },
    ],
    education: { studies: [{ name: "Medicine" }, { name: "Osteopathic Medicine/Osteopathy" }, { name: "Diagnostic Radiology Residency Program" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. Medical school and residency are the path", trainingAfterHiring: "Residency or fellowship", note: PHYSICIAN_DEGREE_NOTE, noBachelorPct: "0%", distribution: DOCTORATE_ONLY },
      pay: { starting: "$89,010", typical: "$420,860", top: "$594,410", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +1,000 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  // General surgeons sit in Surgeons, all other (29-1249). O*NET has no
  // ratings for that title, so knowledge, skills and software follow its
  // surgeon occupations with data (29-1242.00, 29-1243.00). OEWS shows no
  // exact South Dakota figure, so there is no yourStates row.
  surgeon: {
    slug: "surgeon",
    title: "Surgeon",
    world: "Health & Medicine",
    photo: "/images/app/browse/surgeon.webp",
    summary: "A doctor who operates on the body to fix injuries and treat disease.",
    scenario: "Imagine a teen rushed in with a burst appendix. You scrub in, lead the team and take it out before the infection spreads.",
    facts: [
      { label: "Typical degree", value: "Doctoral or professional degree" },
      { label: "Typical pay", value: "$414,010/year" },
      { label: "People doing it", value: "27,500" },
      { label: "Jobs open each year", value: "700" },
    ],
    payByState: { title: "Pay by state", best: [{ state: "North Dakota", pay: "$527K" }, { state: "New Jersey", pay: "$503K" }, { state: "Iowa", pay: "$489K" }] },
    knowAbout: ["Anatomy and surgery", "Medicine and treatments", "Keeping tools and rooms germ free", "Biology and the human body", "Leading a medical team"],
    goodAt: ["Steady, careful hand work", "Making good calls under pressure", "Leading a team", "Explaining surgery to patients", "Solving hard problems"],
    software: ["Epic Systems", "MEDITECH", "3D virtual surgery software", "Computer imaging software", "Microsoft Windows"],
    ladder: [
      MED_SCHOOL,
      { number: "2", jobTitle: "Surgical Resident", pay: "", description: "You train in a hospital, operating side by side with senior surgeons.", whatYouDo: ["Assist in surgery", "Check on patients after surgery", "Take night call", "Learn new procedures"], toGetHere: ["Medical degree (MD or DO)", "Match into a residency"] },
      { number: "3", jobTitle: "Surgeon", pay: "$414K", description: "You decide if surgery is needed, then lead the operating team.", whatYouDo: ["Examine patients", "Plan each operation", "Operate", "Guide recovery"], toGetHere: ["Finish residency", "State medical license"] },
    ],
    education: { studies: [{ name: "Medicine" }, { name: "Osteopathic Medicine/Osteopathy" }, { name: "General Surgery Residency Program" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: `${SOURCES} BLS counts general surgeons in Surgeons, all other (SOC 29-1249), so pay and job counts are for that group.`,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. Medical school and residency are the path", trainingAfterHiring: "Residency or fellowship", note: PHYSICIAN_DEGREE_NOTE, noBachelorPct: "0%", distribution: DOCTORATE_ONLY },
      pay: { starting: "$80,320", typical: "$414,010", top: "$655,320", note: "BLS counts general surgeons with other surgeons not listed on their own, so these figures are for that whole group." },
      openings: { note: `${OPENINGS} The job itself changes by about +1,100 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  // BLS has no separate border officer occupation. O*NET files Customs and
  // Border Protection Officers (33-3051.04) under Police and Sheriff's Patrol
  // Officers (33-3051), so every BLS figure here is for that whole group;
  // tasks, skills and software follow O*NET 33-3051.04.
  "border-protection-officer": {
    slug: "border-protection-officer",
    title: "Border Protection Officer",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/border-protection-officer.webp",
    summary: "Checks the people and goods that come into the country at airports, seaports and border crossings.",
    scenario: "Imagine a full flight lands from overseas. You check passports, ask the right questions and spot the one bag that needs a closer look.",
    facts: [
      { label: "Typical degree", value: "High school diploma or equivalent" },
      { label: "Typical pay", value: "$76,210/year" },
      { label: "People doing it", value: "693,200" },
      { label: "Jobs open each year", value: "51,500" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$64K" }], best: [{ state: "California", pay: "$113K" }, { state: "Washington", pay: "$104K" }, { state: "Alaska", pay: "$102K" }] },
    knowAbout: ["Laws and government", "Public safety", "Clear speaking and writing", "Helping travelers", "How people think and act"],
    goodAt: ["Reading people", "Making good calls", "Working with a team", "Staying calm under pressure", "Asking clear questions"],
    software: ["TECS (Treasury Enforcement Communications System)", "NCIC database", "Automated Manifest System", "Microsoft Office", "GPS software"],
    ladder: [
      { number: "1", jobTitle: "Officer Trainee", pay: "$48K", description: "You train at the agency academy, then work beside experienced officers.", whatYouDo: ["Learn customs and immigration law", "Practice inspections", "Train in self-defense", "Shadow senior officers"], toGetHere: ["High school diploma", "Pass background and fitness checks"] },
      { number: "2", jobTitle: "Border Protection Officer", pay: "$76K", description: "You inspect travelers, bags and cargo and enforce customs and immigration law.", whatYouDo: ["Check passports and visas", "Inspect cargo", "Find hidden goods", "Write reports"], toGetHere: ["Finish the academy", "Time on the job"] },
      { number: "3", jobTitle: "Supervisory Officer", pay: "$106K", description: "You lead a team of officers at a port or crossing.", whatYouDo: ["Lead a shift", "Train new officers", "Handle hard cases", "Work with other agencies"], toGetHere: ["Years as an officer", "Strong job reviews"] },
    ],
    education: { studies: [{ name: "Criminal Justice/Police Science" }, { name: "Criminal Justice and Corrections, General" }, { name: "Law Enforcement Investigation and Interviewing" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: `${SOURCES} BLS counts border officers inside police and sheriff's patrol officers (SOC 33-3051), so pay and job counts are for that whole group.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "Training academy, then on-the-job training", note: "A high school diploma is the usual minimum. New officers train at an agency academy and must meet physical and background checks.", noBachelorPct: "58%", distribution: [{ label: "Did not finish high school", pct: 0.6 }, { label: "Finished high school", pct: 13.4 }, { label: "Some college, no degree", pct: 27.4 }, { label: "Associate's degree", pct: 16.3 }, { label: "Bachelor's degree", pct: 34.2 }, { label: "Master's degree", pct: 7.0 }, { label: "Doctorate or professional degree", pct: 1.0 }] },
      pay: { starting: "$47,510", typical: "$76,210", top: "$115,120", note: "BLS counts border officers inside the larger group of police and sheriff's patrol officers, so these figures are for that whole group." },
      openings: { note: `${OPENINGS} The job itself changes by about +24,200 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  "correctional-officer": {
    slug: "correctional-officer",
    title: "Correctional Officer",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/correctional-officer.webp",
    summary: "Keeps jails and prisons safe and orderly for the people who live and work there.",
    scenario: "Imagine you start your shift with a head count of 80 people. You keep the unit calm, check every door and step in early when tempers rise.",
    facts: [
      { label: "Typical degree", value: "High school diploma or equivalent" },
      { label: "Typical pay", value: "$58,940/year" },
      { label: "People doing it", value: "397,800" },
      { label: "Jobs open each year", value: "28,400" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$53K" }], best: [{ state: "California", pay: "$92K" }, { state: "New Jersey", pay: "$88K" }, { state: "Massachusetts", pay: "$83K" }] },
    knowAbout: ["Public safety", "Clear speaking and writing", "Laws and rules", "Running a team", "How people think and act"],
    goodAt: ["Reading people", "Watching closely", "Calming people down", "Working with a team", "Making good calls"],
    software: ["Jail management software", "Guardian RFID", "3M Electronic Monitoring", "Microsoft Office", "Adobe Acrobat"],
    ladder: [
      { number: "1", jobTitle: "Correctional Officer Trainee", pay: "$43K", description: "You train at an academy, then shadow experienced officers.", whatYouDo: ["Learn facility rules", "Train in self-defense", "Practice security checks", "Shadow senior officers"], toGetHere: ["High school diploma", "Pass background checks"] },
      { number: "2", jobTitle: "Correctional Officer", pay: "$59K", description: "You supervise people in custody and keep the facility secure.", whatYouDo: ["Do head counts", "Inspect cells and doors", "Search for contraband", "Write daily logs"], toGetHere: ["Finish the academy", "State certification where required"] },
      { number: "3", jobTitle: "Correctional Sergeant", pay: "$78K", description: "You lead a team of officers and run a unit or a shift.", whatYouDo: ["Lead a shift", "Train officers", "Handle incidents", "Review reports"], toGetHere: ["Years as an officer", "Promotion exam"] },
    ],
    education: { studies: [{ name: "Corrections" }, { name: "Criminal Justice and Corrections, General" }, { name: "Juvenile Corrections" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "Training academy, then on-the-job training", note: "A high school diploma is the usual minimum. Federal prisons ask for a bachelor's or related work. Every new officer trains at an academy.", noBachelorPct: "81%", distribution: [{ label: "Did not finish high school", pct: 1.8 }, { label: "Finished high school", pct: 31.7 }, { label: "Some college, no degree", pct: 32.5 }, { label: "Associate's degree", pct: 14.7 }, { label: "Bachelor's degree", pct: 15.7 }, { label: "Master's degree", pct: 3.3 }, { label: "Doctorate or professional degree", pct: 0.3 }] },
      pay: { starting: "$42,760", typical: "$58,940", top: "$93,220", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about -29,500 by 2035. Even so, about 28,400 jobs open every year as officers move on or retire.` },
    },
  },
  // No OOH profile of its own; the figures come from projections table 1.2
  // and OEWS for 33-9091. The CIP to SOC crosswalk lists no study program.
  "crossing-guard-or-road-flagger": {
    slug: "crossing-guard-or-road-flagger",
    title: "Crossing Guard or Road Flagger",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/crossing-guard-or-road-flagger.webp",
    summary: "Keeps people safe where they cross busy streets or drive through work zones.",
    scenario: "Imagine school lets out and 200 kids head for the crosswalk. You step out with your sign, stop the traffic and get every one of them across safely.",
    facts: [
      { label: "Typical degree", value: "No formal educational credential" },
      { label: "Typical pay", value: "$38,100/year" },
      { label: "People doing it", value: "94,800" },
      { label: "Jobs open each year", value: "17,300" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$42K" }], best: [{ state: "North Dakota", pay: "$57K" }, { state: "Washington", pay: "$56K" }, { state: "Connecticut", pay: "$56K" }] },
    knowAbout: ["Public safety", "Helping people", "Clear speaking", "Traffic laws", "How people act in a hurry"],
    goodAt: ["Reading people", "Working with a crew", "Making good calls", "Staying calm", "Speaking up clearly"],
    software: ["Crossing guard scheduling software", "Payroll software", "Microsoft Word"],
    ladder: [
      { number: "1", jobTitle: "New Flagger or Crossing Guard", pay: "$31K", description: "You learn hand signals and safety rules on a short training.", whatYouDo: ["Learn hand signals", "Set out cones and signs", "Watch traffic", "Report hazards"], toGetHere: ["Short training", "Flagger card where required"] },
      { number: "2", jobTitle: "Crossing Guard or Road Flagger", pay: "$38K", description: "You stop and guide traffic so walkers and road crews stay safe.", whatYouDo: ["Stop traffic", "Guide people across", "Signal drivers", "Report unsafe drivers"], toGetHere: ["Time on the job"] },
      { number: "3", jobTitle: "Lead Flagger", pay: "$48K", description: "You plan traffic control for a work zone and lead the other flaggers.", whatYouDo: ["Plan work zone setup", "Place signs and markers", "Lead other flaggers", "Talk with the crew boss"], toGetHere: ["Years of flagging", "Traffic control training"] },
    ],
    education: { studies: [{ name: "No program needed. Training happens on the job" }], where: [] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "No formal educational credential", experienceFirst: "No. You can start without it", trainingAfterHiring: "Short on-the-job training", note: "No diploma is required. You learn the job in a short training, and some states ask flaggers for a safety card.", noBachelorPct: "89%", distribution: [{ label: "Did not finish high school", pct: 12.2 }, { label: "Finished high school", pct: 47.2 }, { label: "Some college, no degree", pct: 22.5 }, { label: "Associate's degree", pct: 7.2 }, { label: "Bachelor's degree", pct: 9.5 }, { label: "Master's degree", pct: 1.3 }, { label: "Doctorate or professional degree", pct: 0.1 }] },
      pay: { starting: "$30,840", typical: "$38,100", top: "$61,690", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +3,300 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  "emergency-management-director": {
    slug: "emergency-management-director",
    title: "Emergency Management Director",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/emergency-management-director.webp",
    summary: "Plans how a city, school or company gets ready for disasters and leads the response when one hits.",
    scenario: "Imagine a hurricane is two days out. You open the shelters, plan the evacuation routes and keep every agency working from the same plan.",
    facts: [
      { label: "Typical degree", value: "Bachelor's degree" },
      { label: "Typical pay", value: "$93,330/year" },
      { label: "People doing it", value: "14,000" },
      { label: "Jobs open each year", value: "1,100" },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: "South Dakota", pay: "$70K" }], best: [{ state: "District of Columbia", pay: "$165K" }, { state: "New Mexico", pay: "$141K" }, { state: "California", pay: "$138K" }] },
    knowAbout: ["Public safety", "Running a team or a business", "Laws and government", "Communications and media", "Clear writing"],
    goodAt: ["Helping people", "Solving hard problems", "Getting teams to work together", "Making good calls", "Teaching others what to do"],
    software: ["WebEOC", "Esri ArcGIS", "FEMIS", "Microsoft SharePoint", "Microsoft Word"],
    ladder: [
      { number: "1", jobTitle: "Firefighter", pay: "$59K", description: "Many directors start in fire, police, EMS or the military, where they learn to act fast in a crisis.", whatYouDo: ["Respond to emergencies", "Give first aid", "Inspect for hazards", "Teach fire safety"], toGetHere: ["High school diploma", "EMT training"] },
      { number: "2", jobTitle: "Emergency Management Director", pay: "$93K", description: "You write disaster plans and lead the response when something big happens.", whatYouDo: ["Write emergency plans", "Run drills", "Coordinate agencies", "Report on damage"], toGetHere: ["Bachelor's degree", "Years of emergency work"] },
      { number: "3", jobTitle: "Senior Emergency Management Director", pay: "$126K", description: "You lead emergency planning for a large city, state or company.", whatYouDo: ["Lead a large team", "Plan for many risks", "Work with state and federal leaders", "Manage the budget"], toGetHere: ["Years as a director", "Certification like CEM helps"] },
    ],
    education: { studies: [{ name: "Crisis/Emergency/Disaster Management" }, { name: "Homeland Security" }, { name: "Critical Infrastructure Protection" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }] },
    sources: SOURCES,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "Yes. Usually 5 years or more in emergency work", trainingAfterHiring: "None required", note: "Most directors have a bachelor's. Nearly all spend years in emergency work first, such as the military, police or fire service.", noBachelorPct: "37%", distribution: [{ label: "Did not finish high school", pct: 1.1 }, { label: "Finished high school", pct: 4.8 }, { label: "Some college, no degree", pct: 18.9 }, { label: "Associate's degree", pct: 12.1 }, { label: "Bachelor's degree", pct: 30.8 }, { label: "Master's degree", pct: 28.5 }, { label: "Doctorate or professional degree", pct: 3.9 }] },
      pay: { starting: "$54,210", typical: "$93,330", top: "$166,430", note: HALF },
      openings: { note: `${OPENINGS} The job itself changes by about +500 by 2035. It is growing about as fast as most jobs.` },
    },
  },
};
