// Career Detail profiles for the 4 Oct 2026 poster drop, batch 4 (BROWSE Images).
// Sourced: people, openings and change from BLS Employment Projections table 1.2
// (2025-35); typical degree, related work and training from the same table;
// starting / typical / top pay from OEWS May 2025 national 10th / 50th / 90th
// percentiles; state rows from OEWS May 2025 state annual means (South Dakota
// for yourStates, like every other entry; best is the top 3 of the 50 states
// plus DC); degree mix from BLS table 5.3; growth wording follows the OOH
// 2025-35 categories; tasks, knowledge, skills and software from O*NET OnLine;
// study fields from the NCES CIP 2020 to SOC 2018 crosswalk. Ladder rungs use
// the same occupation's 10th / 50th / 75th percentile, or the median of the
// OEWS occupation the rung names (Lawyers 23-1011, Police and Sheriff's Patrol
// Officers 33-3051, First-Line Supervisors of Police 33-1012, First-Line
// Supervisors of Entertainment and Recreation Workers 39-1014, Preschool
// Teachers 25-2011, Preschool and Daycare Administrators 11-9031, Natural
// Sciences Managers 11-9121, Biological Technicians 19-4021, Exercise Trainers
// 39-9031, Entertainment and Recreation Managers 11-9072). SOC per career:
// Fish and Game Warden 33-3031; Hearing Officer 23-1021; Intelligence Analyst
// 33-3021 (O*NET 33-3021.06); Judge 23-1023; Lifeguard or Ski Patrol 33-9092;
// Police Sergeant 33-1012; Transit Police Officer 33-3052; Childcare Worker
// 39-9011; Fitness Trainer 39-9031; Fitness and Wellness Coordinator 11-9179
// (O*NET 11-9179.01); Nanny 39-9011 (O*NET 39-9011.01); Recreation Manager
// 11-9072; Recreation Worker 39-9032; Tour Guide 39-7010 (O*NET 39-7011.00);
// Travel Agent 41-3041; Anthropologist or Archaeologist 19-3091; Astronomer
// 19-2011; Bioinformatics Scientist 19-1029 (O*NET 19-1029.01); Biologist
// 19-1029 (O*NET 19-1029.04); Cell Therapy Manufacturing Associate 19-4021.
// Mapped to a broader BLS occupation, because BLS publishes none of their own:
// Intelligence Analyst (O*NET files it under Detectives and Criminal
// Investigators), Fitness and Wellness Coordinator (under Personal Service
// Managers, All Other), Nanny (under Childcare Workers), Bioinformatics
// Scientist and Biologist (both under Biological Scientists, All Other), Tour
// Guide (BLS projections and OEWS publish only the combined Tour and Travel
// Guides group), and Cell Therapy Manufacturing Associate (no BLS or O*NET
// occupation; Biological Technicians is O*NET's closest match for
// biomanufacturing associates). Each of those entries says so in "sources".
// OEWS released no South Dakota wage for 11-9179, 19-2011, 23-1021, 23-1023
// or 33-3052, so those entries have no yourStates row (same as Robotics
// Technician). Table 5.3 gives Judges and Hearing Officers one shared mix.
import type { CareerProfile } from "./profiles";

const S = "Job description and skills from O*NET (USDOL/ETA). Pay and growth from the U.S. Bureau of Labor Statistics.";
const OPEN = "Counts every job that needs filling, mostly people moving on rather than brand-new roles.";
const MIX = (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [
  { label: "Did not finish high school", pct: a },
  { label: "Finished high school", pct: b },
  { label: "Some college, no degree", pct: c },
  { label: "Associate's degree", pct: d },
  { label: "Bachelor's degree", pct: e },
  { label: "Master's degree", pct: f },
  { label: "Doctorate or professional degree", pct: g },
];
const K = (state: string, pay: string) => ({ state, pay });
const FACTS = (degree: string, pay: string, people: string, openings: string) => [
  { label: "Typical degree", value: degree },
  { label: "Typical pay", value: pay },
  { label: "People doing it", value: people },
  { label: "Jobs open each year", value: openings },
];

export const LIB4_PROFILES: Record<string, CareerProfile> = {
  "fish-and-game-warden": {
    slug: "fish-and-game-warden",
    title: "Fish and Game Warden",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/fish-and-game-warden.webp",
    summary: "Patrols lakes, woods and fields to protect wildlife and enforce hunting, fishing and boating laws.",
    scenario: "Imagine a call about shots fired at dawn on a closed hunting ground. You head out by truck and boat, find the hunters and check every license.",
    facts: FACTS("Bachelor's degree", "$74,060/year", "6,200", "500"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$67K")], best: [K("California", "$96K"), K("Indiana", "$92K"), K("Maryland", "$91K")] },
    knowAbout: ["Public safety and security", "Laws and government", "Helping the public", "Animals and plants", "Maps and land"],
    goodAt: ["Talking clearly with people", "Listening closely", "Making good calls", "Spotting what is wrong", "Getting people to follow the rules"],
    software: ["Microsoft Office", "Microsoft Excel", "Microsoft PowerPoint", "GPS software", "Mapping software"],
    ladder: [
      { number: "1", jobTitle: "Game Warden Trainee", pay: "$51K", description: "You finish the academy and patrol with an experienced warden.", whatYouDo: ["Patrol by truck and boat", "Check licenses", "Write reports", "Learn the wildlife laws"], toGetHere: ["Bachelor's degree", "Pass the academy"] },
      { number: "2", jobTitle: "Fish and Game Warden", pay: "$74K", description: "You patrol your own area, look into tips and protect the wildlife that lives there.", whatYouDo: ["Investigate hunting accidents", "Issue citations", "Help with search and rescue", "Teach hunter safety"], toGetHere: ["Academy training", "Time on patrol"] },
      { number: "3", jobTitle: "Warden Sergeant", pay: "$89K", description: "You lead a team of wardens and plan patrols across a bigger region.", whatYouDo: ["Lead a team", "Plan patrols", "Work with other police", "Present cases in court"], toGetHere: ["Years as a warden", "Promotion exam"] },
    ],
    education: { studies: [{ name: "Environmental/Natural Resources Law Enforcement and Protective Services" }], where: [{ count: "", credential: "Bachelor's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "A bachelor's degree is the usual way in. New wardens then finish a training academy and learn on the job.", noBachelorPct: "59%", distribution: MIX(3.2, 20.3, 23.4, 12.2, 30.2, 8.4, 2.2) },
      pay: { starting: "$50,990", typical: "$74,060", top: "$100,980", note: "Almost all wardens work for state governments." },
      openings: { note: `${OPEN} The job itself changes by about -400 by 2035. Most openings come from wardens who retire or move on.` },
    },
  },
  "hearing-officer": {
    slug: "hearing-officer",
    title: "Hearing Officer",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/hearing-officer.webp",
    summary: "Runs hearings on government claims and rules who is right under the law.",
    scenario: "Imagine a worker who was hurt on the job asks why her claim was turned down. You hear both sides, read the records and write a fair decision.",
    facts: FACTS("Doctoral or professional degree", "$117,860/year", "17,400", "500"),
    payByState: { title: "Pay by state", best: [K("District of Columbia", "$172K"), K("Indiana", "$155K"), K("Alabama", "$150K")] },
    knowAbout: ["Laws and government", "Clear reading and writing", "Office records and paperwork"],
    goodAt: ["Listening closely", "Thinking through hard choices", "Reading long documents", "Writing clear decisions", "Reading how people feel"],
    software: ["Thomson Reuters Westlaw", "LexisNexis", "Adobe Acrobat", "Microsoft Word", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Claims Adjudicator or Appeals Examiner", pay: "$61K", description: "You review claims and smaller appeals while senior officers check your work.", whatYouDo: ["Review claim files", "Check the facts", "Schedule hearings", "Draft decisions"], toGetHere: ["Law degree", "Some legal work first"] },
      { number: "2", jobTitle: "Hearing Officer", pay: "$118K", description: "You run hearings on your own and decide claims for a government agency.", whatYouDo: ["Run hearings", "Rule on evidence", "Research the law", "Write decisions"], toGetHere: ["Law degree", "Years as a lawyer"] },
      { number: "3", jobTitle: "Administrative Law Judge", pay: "$160K", description: "You decide the hardest cases and your rulings set the path for others.", whatYouDo: ["Hear complex cases", "Issue subpoenas", "Write formal opinions", "Guide newer officers"], toGetHere: ["Years of hearing work", "Agency selection"] },
    ],
    education: { studies: [{ name: "Law" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Law degree (J.D.)" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "Yes. Usually 5 years or more as a lawyer", trainingAfterHiring: "On-the-job training", note: "Hearing officers usually need a law degree and work experience as a lawyer.", noBachelorPct: "2%", distribution: MIX(0.4, 0.7, 0.8, 0.4, 6.6, 4.6, 86.5) },
      pay: { starting: "$61,110", typical: "$117,860", top: "$207,480", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself stays about the same size through 2035. It is holding about steady.` },
    },
  },
  "intelligence-analyst": {
    slug: "intelligence-analyst",
    title: "Intelligence Analyst",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/intelligence-analyst.webp",
    summary: "Studies data and tips to find patterns in crime and help stop it before it happens.",
    scenario: "Imagine phone records, maps and tips that do not seem to connect. You chart them side by side until a crime ring's whole network shows up.",
    facts: FACTS("High school diploma or equivalent", "$93,790/year", "120,500", "7,800"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$91K")], best: [K("District of Columbia", "$148K"), K("Maryland", "$130K"), K("Alaska", "$125K")] },
    knowAbout: ["Clear reading and writing", "Laws and government", "Public safety and security", "Computers and data", "Office records and paperwork"],
    goodAt: ["Reading closely", "Spotting patterns", "Thinking through hard choices", "Writing clear reports", "Solving tricky problems"],
    software: ["ESRI ArcGIS", "Tableau", "SQL", "Splunk Enterprise", "Microsoft Access"],
    ladder: [
      { number: "1", jobTitle: "Crime Analyst", pay: "$55K", description: "You pull data from police records and map where and when crimes happen.", whatYouDo: ["Search databases", "Map crime trends", "Build charts", "Write short reports"], toGetHere: ["Degree in criminal justice or a related field helps"] },
      { number: "2", jobTitle: "Intelligence Analyst", pay: "$94K", description: "You link people, places and events to show investigators what is really going on.", whatYouDo: ["Check facts across sources", "Link suspects to groups", "Brief investigators", "Share findings with other agencies"], toGetHere: ["Time as an analyst", "Security clearance for some jobs"] },
      { number: "3", jobTitle: "Senior Intelligence Analyst", pay: "$121K", description: "You lead the biggest cases, set the team's priorities and train new analysts.", whatYouDo: ["Lead major cases", "Find gaps in what is known", "Train analysts", "Brief leaders"], toGetHere: ["Years of analysis work", "Advanced training"] },
    ],
    education: { studies: [{ name: "Law Enforcement Intelligence Analysis" }, { name: "Geospatial Intelligence" }, { name: "Criminal Justice/Police Science" }, { name: "Cyber/Computer Forensics and Counterterrorism" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: `${S} BLS has no separate intelligence analyst job, so pay, growth and the degree mix are for all detectives and criminal investigators.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "Usually a few years of related work first", trainingAfterHiring: "On-the-job training", note: "BLS counts this job with detectives, where a diploma can open the door. Most people in the group have a college degree.", noBachelorPct: "36%", distribution: MIX(0.4, 8.2, 19.0, 8.8, 44.1, 17.5, 2.1) },
      pay: { starting: "$55,390", typical: "$93,790", top: "$160,540", note: "BLS counts intelligence analysts inside the larger group of detectives and criminal investigators, so these figures are for that whole group." },
      openings: { note: `${OPEN} The job itself changes by about +200 by 2035. It is holding about steady.` },
    },
  },
  judge: {
    slug: "judge",
    title: "Judge",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/judge.webp",
    summary: "Runs a courtroom, makes sure trials are fair and decides cases under the law.",
    scenario: "Imagine a packed courtroom waiting on your ruling. Both lawyers have made their case, and now you explain the law to the jury.",
    facts: FACTS("Doctoral or professional degree", "$153,990/year", "25,300", "800"),
    payByState: { title: "Pay by state", best: [K("Rhode Island", "$214K"), K("Hawaii", "$213K"), K("Massachusetts", "$201K")] },
    knowAbout: ["Laws and government", "Clear reading and writing", "Running an office", "How people think and feel", "Public safety and security"],
    goodAt: ["Listening closely", "Thinking through hard choices", "Reading long documents", "Writing clear decisions", "Staying fair and calm"],
    software: ["Thomson Reuters Westlaw", "LexisNexis", "Hyland OnBase", "Adobe Acrobat", "Microsoft Word"],
    ladder: [
      { number: "1", jobTitle: "Lawyer", pay: "$160K", description: "You argue cases in court and learn how judges think.", whatYouDo: ["Advise clients", "Research the law", "Argue in court", "Write legal papers"], toGetHere: ["Law degree", "Pass the bar exam"] },
      { number: "2", jobTitle: "Judge", pay: "$154K", description: "You run trials and hearings, rule on evidence and hand down decisions.", whatYouDo: ["Run trials", "Rule on evidence", "Instruct juries", "Write decisions"], toGetHere: ["Years as a lawyer", "Elected or appointed"] },
      { number: "3", jobTitle: "Appeals Court Judge", pay: "$195K", description: "You review other courts' rulings and your opinions guide future cases.", whatYouDo: ["Review lower court rulings", "Hear arguments", "Research legal issues", "Write opinions"], toGetHere: ["Years on the bench", "Elected or appointed"] },
    ],
    education: { studies: [{ name: "Law" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Law degree (J.D.)" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "Yes. Usually 5 years or more as a lawyer", trainingAfterHiring: "On-the-job training", note: "Judges usually need a law degree and work experience as a lawyer. Most are elected or appointed.", noBachelorPct: "2%", distribution: MIX(0.4, 0.7, 0.8, 0.4, 6.6, 4.6, 86.5) },
      pay: { starting: "$46,950", typical: "$153,990", top: "$221,710", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +700 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  "lifeguard-or-ski-patrol": {
    slug: "lifeguard-or-ski-patrol",
    title: "Lifeguard or Ski Patrol",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/lifeguard-or-ski-patrol.webp",
    summary: "Watches over pools, beaches and ski slopes and rescues people who need help.",
    scenario: "Imagine a crowded beach on a windy day. You spot a swimmer pulled out by a rip current and reach them before anyone else sees.",
    facts: FACTS("No formal education required", "$33,580/year", "162,000", "45,400"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$31K")], best: [K("District of Columbia", "$58K"), K("Hawaii", "$55K"), K("California", "$44K")] },
    knowAbout: ["Helping the public", "Public safety and security", "Teaching and training", "First aid", "Clear speaking"],
    goodAt: ["Watching closely", "Staying calm in an emergency", "Talking clearly", "Swimming or skiing well", "Teaching safety"],
    software: ["Microsoft Excel", "Microsoft Word", "Microsoft PowerPoint", "Microsoft Outlook", "GroupMe"],
    ladder: [
      { number: "1", jobTitle: "New Lifeguard", pay: "$26K", description: "You watch your area, give first aid and learn rescues from senior guards.", whatYouDo: ["Watch swimmers", "Give first aid", "Test pool water", "Warn about danger"], toGetHere: ["Lifeguard certification", "CPR and first aid"] },
      { number: "2", jobTitle: "Lifeguard or Ski Patroller", pay: "$34K", description: "You lead rescues, keep records and teach people how to stay safe.", whatYouDo: ["Make rescues", "Check equipment", "Keep safety records", "Teach safety rules"], toGetHere: ["Time on the job", "Advanced rescue training"] },
      { number: "3", jobTitle: "Aquatics Manager", pay: "$80K", description: "You run a pool, beach or ski safety program and lead the whole team.", whatYouDo: ["Hire and train guards", "Plan programs", "Set budgets", "Handle safety plans"], toGetHere: ["Years of guard work", "A degree in recreation helps"] },
    ],
    education: { studies: [{ name: "Environmental/Natural Resources Law Enforcement and Protective Services" }], where: [{ count: "", credential: "Certificate, under a year" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "No formal education required", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "You usually need strong skills in a sport like swimming or skiing. Certification is often required.", noBachelorPct: "53%", distribution: MIX(4.1, 15.7, 21.9, 11.3, 37.2, 7.8, 1.9) },
      pay: { starting: "$25,780", typical: "$33,580", top: "$43,970", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +8,900 by 2035. It is growing faster than most jobs.` },
    },
  },
  "police-sergeant": {
    slug: "police-sergeant",
    title: "Police Sergeant",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/police-sergeant.webp",
    summary: "Leads a team of police officers, plans their shifts and guides their cases.",
    scenario: "Imagine a storm knocks out traffic lights across town. You send your officers to the busiest corners and keep every call covered.",
    facts: FACTS("High school diploma or equivalent", "$106,040/year", "160,200", "10,600"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$97K")], best: [K("California", "$163K"), K("District of Columbia", "$148K"), K("New Jersey", "$145K")] },
    knowAbout: ["Public safety and security", "Laws and government", "Helping the public", "Running a team", "How people think and feel"],
    goodAt: ["Leading a team", "Listening closely", "Reading how people feel", "Teaching others", "Making good calls"],
    software: ["NCIC database", "Computer aided dispatch software", "Crime mapping software", "Microsoft Excel", "Microsoft Visio"],
    ladder: [
      { number: "1", jobTitle: "Police Officer", pay: "$76K", description: "You patrol, answer calls and learn how your department works.", whatYouDo: ["Patrol an area", "Answer calls", "Write reports", "Make arrests"], toGetHere: ["High school diploma", "Police academy"] },
      { number: "2", jobTitle: "Police Sergeant", pay: "$106K", description: "You lead a squad of officers, check their work and guide investigations.", whatYouDo: ["Assign shifts", "Guide investigations", "Train officers", "Review reports"], toGetHere: ["Years as an officer", "Promotion exam"] },
      { number: "3", jobTitle: "Police Lieutenant", pay: "$133K", description: "You lead several squads and help set how the department runs.", whatYouDo: ["Lead sergeants", "Plan operations", "Handle staff issues", "Explain new laws to officers"], toGetHere: ["Years as a sergeant", "Promotion exam"] },
    ],
    education: { studies: [{ name: "Criminal Justice and Corrections, General" }, { name: "Criminal Justice/Law Enforcement Administration" }, { name: "Homeland Security" }, { name: "Crisis/Emergency/Disaster Management" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "Yes. A few years as a police officer first", trainingAfterHiring: "On-the-job training", note: "Sergeants start as police officers and move up. Many have some college, and a degree can help with promotion.", noBachelorPct: "53%", distribution: MIX(1.4, 11.6, 24.7, 14.9, 33.3, 12.8, 1.3) },
      pay: { starting: "$63,350", typical: "$106,040", top: "$165,110", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +5,200 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  "transit-police-officer": {
    slug: "transit-police-officer",
    title: "Transit Police Officer",
    world: "Law, Safety & Justice",
    photo: "/images/app/browse/transit-police-officer.webp",
    summary: "Keeps riders, workers and property safe on trains, buses and rail lines.",
    scenario: "Imagine a rush-hour subway station packed with riders. You spot someone in a locked tunnel area and step in before anyone gets hurt.",
    facts: FACTS("High school diploma or equivalent", "$90,230/year", "4,400", "300"),
    payByState: { title: "Pay by state", best: [K("New Jersey", "$103K"), K("California", "$100K"), K("New York", "$98K")] },
    knowAbout: ["Public safety and security", "Laws and government", "Clear reading and writing", "Helping the public", "How transit works"],
    goodAt: ["Listening closely", "Talking clearly", "Solving tricky problems", "Reading how people feel", "Watching closely"],
    software: ["NCIC database", "IAFIS fingerprint system", "Crime mapping software", "Microsoft Office", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Transit Police Recruit", pay: "$58K", description: "You finish the academy and patrol stations with a field training officer.", whatYouDo: ["Patrol stations", "Check secure areas", "Help riders", "Write reports"], toGetHere: ["High school diploma", "Police academy"] },
      { number: "2", jobTitle: "Transit Police Officer", pay: "$90K", description: "You patrol trains, stations and rail yards and look into crimes on the system.", whatYouDo: ["Patrol trains and yards", "Investigate thefts", "Enforce transit laws", "Teach rail safety"], toGetHere: ["Academy training", "Time on patrol"] },
      { number: "3", jobTitle: "Transit Police Sergeant", pay: "$106K", description: "You lead a squad and plan how to keep a whole line or station safe.", whatYouDo: ["Lead a squad", "Plan safety programs", "Direct emergency scenes", "Review reports"], toGetHere: ["Years as an officer", "Promotion exam"] },
    ],
    education: { studies: [{ name: "Security and Loss Prevention Services" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "Most officers graduate from a training academy, then learn on the job with a senior officer.", noBachelorPct: "58%", distribution: MIX(0.6, 13.4, 27.4, 16.3, 34.2, 7.0, 1.0) },
      pay: { starting: "$57,690", typical: "$90,230", top: "$125,910", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +100 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  "childcare-worker": {
    slug: "childcare-worker",
    title: "Childcare Worker",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/childcare-worker.webp",
    summary: "Cares for young children, keeps them safe and helps them learn through play.",
    scenario: "Imagine a room of toddlers just waking up from naps. You get snacks out, start a song and turn a hard afternoon into a happy one.",
    facts: FACTS("High school diploma or equivalent", "$34,980/year", "1,010,300", "150,300"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$30K")], best: [K("District of Columbia", "$48K"), K("California", "$43K"), K("Massachusetts", "$43K")] },
    knowAbout: ["Caring for people", "Teaching and training", "Keeping kids safe", "How children grow and feel", "Clear speaking"],
    goodAt: ["Watching closely", "Listening to kids and parents", "Staying patient", "Teaching through play", "Spotting when a child needs help"],
    software: ["Tadpoles", "Seesaw", "Google Classroom", "Scheduling software", "Microsoft Word"],
    ladder: [
      { number: "1", jobTitle: "Childcare Assistant", pay: "$24K", description: "You help in a classroom, keep kids safe and learn the daily routine.", whatYouDo: ["Watch kids at play", "Serve meals", "Change diapers", "Clean toys"], toGetHere: ["High school diploma", "Background check"] },
      { number: "2", jobTitle: "Preschool Teacher", pay: "$38K", description: "You plan lessons and help young kids get ready for school.", whatYouDo: ["Plan lessons", "Track how kids grow", "Talk with parents", "Lead the room"], toGetHere: ["Early childhood credential or degree"] },
      { number: "3", jobTitle: "Childcare Center Director", pay: "$59K", description: "You run the whole center, lead the staff and keep it meeting state rules.", whatYouDo: ["Hire and train staff", "Set budgets", "Meet state rules", "Work with families"], toGetHere: ["Years in childcare", "A degree in early childhood helps"] },
    ],
    education: { studies: [{ name: "Child Care Provider/Assistant" }, { name: "Child Development" }, { name: "Early Childhood and Family Studies" }], where: [{ count: "", credential: "Certificate, under a year" }, { count: "", credential: "Associate's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "Rules vary by state and setting. They range from no formal education to a certificate in early childhood education.", noBachelorPct: "78%", distribution: MIX(11.6, 31.6, 23.1, 11.2, 17.7, 4.2, 0.7) },
      pay: { starting: "$24,260", typical: "$34,980", top: "$46,010", note: "24% work for themselves, so this describes the ones with a boss." },
      openings: { note: `${OPEN} The job itself changes by about -19,900 by 2035. Even so, about 150,300 spots open each year as people move on.` },
    },
  },
  "fitness-trainer": {
    slug: "fitness-trainer",
    title: "Fitness Trainer",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/fitness-trainer.webp",
    summary: "Coaches people one on one or in classes to help them get stronger and healthier.",
    scenario: "Imagine a client who could not run a mile in January. You build her plan week by week, and in June she crosses her first 5K finish line.",
    facts: FACTS("High school diploma or equivalent", "$47,160/year", "388,400", "68,000"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$43K")], best: [K("Massachusetts", "$72K"), K("Connecticut", "$67K"), K("New Jersey", "$65K")] },
    knowAbout: ["Helping clients", "Teaching and training", "How people think and feel", "How the body moves", "Clear speaking"],
    goodAt: ["Teaching and showing how", "Cheering people on", "Watching form closely", "Listening to what clients need", "Planning workouts"],
    software: ["Personal Trainer Pro", "BioEx Fitness Maker", "Appointment scheduling software", "Intuit QuickBooks", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "New Fitness Trainer", pay: "$29K", description: "You lead classes and train new clients while you build your skills.", whatYouDo: ["Lead group classes", "Show safe form", "Keep equipment ready", "Sign up clients"], toGetHere: ["High school diploma", "Trainer certification", "CPR"] },
      { number: "2", jobTitle: "Fitness Trainer", pay: "$47K", description: "You test what each client can do and build plans that fit their goals.", whatYouDo: ["Check fitness levels", "Build training plans", "Track progress", "Teach safe breathing"], toGetHere: ["Certification", "A loyal client list"] },
      { number: "3", jobTitle: "Senior or Master Trainer", pay: "$62K", description: "You train harder cases, coach other trainers and may run your own business.", whatYouDo: ["Coach other trainers", "Train special groups", "Plan programs", "Grow your client list"], toGetHere: ["Years of training", "Advanced certifications or a degree"] },
    ],
    education: { studies: [{ name: "Sports, Kinesiology, and Physical Education/Fitness, General" }, { name: "Physical Fitness Technician" }, { name: "Sport and Fitness Administration/Management" }, { name: "Yoga Teacher Training/Yoga Therapy" }], where: [{ count: "", credential: "Certificate, under a year" }, { count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "Most trainers earn a fitness certification. Many also have a degree in a field like kinesiology.", noBachelorPct: "41%", distribution: MIX(1.8, 10.3, 19.6, 9.6, 42.7, 13.4, 2.6) },
      pay: { starting: "$28,800", typical: "$47,160", top: "$83,100", note: "15% work for themselves, so this describes the ones with a boss." },
      openings: { note: `${OPEN} The job itself changes by about +28,500 by 2035. It is growing much faster than most jobs.` },
    },
  },
  "fitness-and-wellness-coordinator": {
    slug: "fitness-and-wellness-coordinator",
    title: "Fitness and Wellness Coordinator",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/fitness-and-wellness-coordinator.webp",
    summary: "Plans and runs fitness and wellness programs and leads the trainers who teach them.",
    scenario: "Imagine a company asks you to help 500 workers get moving. You plan the classes, pick the coaches and track who shows up.",
    facts: FACTS("High school diploma or equivalent", "$69,770/year", "25,500", "2,000"),
    payByState: { title: "Pay by state", best: [K("Colorado", "$104K"), K("Wisconsin", "$99K"), K("Vermont", "$98K")] },
    knowAbout: ["Helping clients", "Teaching and training", "Running a team or a business", "Office records and paperwork", "Sales and marketing"],
    goodAt: ["Leading a team", "Planning schedules", "Listening closely", "Teaching others", "Checking what works"],
    software: ["Google Workspace", "Microsoft Excel", "Microsoft PowerPoint", "Work scheduling software", "Payroll software"],
    ladder: [
      { number: "1", jobTitle: "Fitness Trainer", pay: "$47K", description: "You coach clients and lead classes, learning what makes a program work.", whatYouDo: ["Lead classes", "Build workout plans", "Track progress", "Keep equipment safe"], toGetHere: ["Trainer certification", "CPR"] },
      { number: "2", jobTitle: "Fitness and Wellness Coordinator", pay: "$70K", description: "You plan programs, schedule staff and keep the gym or wellness center running.", whatYouDo: ["Plan programs", "Schedule staff", "Track attendance", "Train instructors"], toGetHere: ["Years as a trainer", "A degree helps"] },
      { number: "3", jobTitle: "Wellness Director", pay: "$94K", description: "You lead all wellness services, set the budget and decide what to offer next.", whatYouDo: ["Set budgets", "Pick new programs", "Lead managers", "Measure results"], toGetHere: ["Years as a coordinator", "A bachelor's or master's helps"] },
    ],
    education: { studies: [{ name: "Sport and Fitness Administration/Management" }, { name: "Sports, Kinesiology, and Physical Education/Fitness, General" }, { name: "Business Administration and Management, General" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: `${S} BLS has no separate fitness and wellness coordinator job, so pay, growth and the degree mix are for all personal service managers not listed elsewhere.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "Yes. A few years of related work first", trainingAfterHiring: "None required", note: "Most coordinators start as trainers or instructors. Many have a bachelor's degree.", noBachelorPct: "42%", distribution: MIX(3.2, 14.0, 16.7, 7.7, 35.9, 18.6, 3.9) },
      pay: { starting: "$44,910", typical: "$69,770", top: "$118,710", note: "BLS counts this job inside a larger group of personal service managers, so these figures are for that whole group." },
      openings: { note: `${OPEN} The job itself changes by about +1,600 by 2035. It is growing faster than most jobs.` },
    },
  },
  nanny: {
    slug: "nanny",
    title: "Nanny",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/nanny.webp",
    summary: "Cares for a family's children in their home and helps them grow, learn and stay safe.",
    scenario: "Imagine two kids, one school pickup and a rainy afternoon. You plan a snack, a craft and a story so the day ends calm and happy.",
    facts: FACTS("High school diploma or equivalent", "$34,980/year", "1,010,300", "150,300"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$30K")], best: [K("District of Columbia", "$48K"), K("California", "$43K"), K("Massachusetts", "$43K")] },
    knowAbout: ["Clear speaking", "Caring for people", "How children grow and feel", "Teaching and training", "Keeping kids safe"],
    goodAt: ["Listening to kids and parents", "Watching closely", "Staying patient", "Setting kind rules", "Planning the day"],
    software: ["Scheduling software", "Educational software", "Microsoft Excel", "Microsoft Word", "Web browser software"],
    ladder: [
      { number: "1", jobTitle: "New Nanny", pay: "$24K", description: "You care for children part time and learn each family's routine.", whatYouDo: ["Watch kids at play", "Make snacks", "Help with naps", "Keep the house safe"], toGetHere: ["Babysitting experience", "CPR and first aid"] },
      { number: "2", jobTitle: "Nanny", pay: "$35K", description: "You care for a family's kids full time and help them learn and grow.", whatYouDo: ["Plan activities", "Help with homework", "Make meals", "Teach good habits"], toGetHere: ["Years of childcare", "Good references"] },
      { number: "3", jobTitle: "Household Manager", pay: "$39K", description: "You run the family's daily life, from kids' schedules to meals and errands.", whatYouDo: ["Run schedules", "Plan meals", "Handle errands", "Guide other helpers"], toGetHere: ["Years as a nanny", "Strong references"] },
    ],
    education: { studies: [{ name: "Child Care Provider/Assistant" }, { name: "Child Development" }, { name: "Early Childhood and Family Studies" }], where: [{ count: "", credential: "Certificate, under a year" }, { count: "", credential: "Associate's degree" }] },
    sources: `${S} BLS has no separate nanny job, so pay, growth and the degree mix are for all childcare workers.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "Families often look for childcare experience and CPR training. A certificate in early childhood can help.", noBachelorPct: "78%", distribution: MIX(11.6, 31.6, 23.1, 11.2, 17.7, 4.2, 0.7) },
      pay: { starting: "$24,260", typical: "$34,980", top: "$46,010", note: "BLS counts nannies inside the larger group of childcare workers. 24% of that group work for themselves, so this describes the ones with a boss." },
      openings: { note: `${OPEN} The job itself changes by about -19,900 by 2035. Even so, about 150,300 spots open each year as people move on.` },
    },
  },
  "recreation-manager": {
    slug: "recreation-manager",
    title: "Recreation Manager",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/recreation-manager.webp",
    summary: "Plans and runs parks, camps, pools and other places where people play and relax.",
    scenario: "Imagine a city park with summer camp, a pool and a concert all on one Saturday. You plan the staff, the budget and the schedule so it all runs smoothly.",
    facts: FACTS("Bachelor's degree", "$79,520/year", "43,900", "5,100"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$80K")], best: [K("District of Columbia", "$115K"), K("Washington", "$114K"), K("Minnesota", "$113K")] },
    knowAbout: ["Helping the public", "Teaching and training", "Clear speaking", "Public safety", "Running a team or a business"],
    goodAt: ["Reading how people feel", "Planning events", "Making good calls", "Managing time", "Leading a team"],
    software: ["Salesforce", "Intuit QuickBooks", "ADP Workforce Now", "Slack", "Microsoft Outlook"],
    ladder: [
      { number: "1", jobTitle: "Recreation Worker", pay: "$37K", description: "You lead games, sports and crafts and learn how programs run.", whatYouDo: ["Lead activities", "Keep people safe", "Set up events", "Track attendance"], toGetHere: ["High school diploma", "CPR and first aid"] },
      { number: "2", jobTitle: "Recreation Supervisor", pay: "$49K", description: "You lead a team of recreation workers and run day-to-day programs.", whatYouDo: ["Schedule staff", "Plan programs", "Train new workers", "Handle questions"], toGetHere: ["Years in recreation", "A degree helps"] },
      { number: "3", jobTitle: "Recreation Manager", pay: "$80K", description: "You run a whole facility or department, from budgets to hiring.", whatYouDo: ["Write budgets", "Hire staff", "Plan seasons", "Track spending"], toGetHere: ["Bachelor's degree", "Years as a supervisor"] },
    ],
    education: { studies: [{ name: "Parks, Recreation, and Leisure Facilities Management, General" }, { name: "Sport and Fitness Administration/Management" }, { name: "Environmental/Natural Resource Recreation and Tourism" }, { name: "Hospitality Administration/Management, General" }], where: [{ count: "", credential: "Bachelor's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "Yes. A few years in recreation work first", trainingAfterHiring: "None required", note: "Some jobs ask for a bachelor's degree, while others hire with a high school diploma. Work experience matters too.", noBachelorPct: "57%", distribution: MIX(2.9, 17.9, 24.3, 11.6, 34.4, 7.9, 1.0) },
      pay: { starting: "$46,270", typical: "$79,520", top: "$139,110", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +2,700 by 2035. It is growing faster than most jobs.` },
    },
  },
  "recreation-worker": {
    slug: "recreation-worker",
    title: "Recreation Worker",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/recreation-worker.webp",
    summary: "Leads games, sports, crafts and outings for kids and adults at parks, camps and centers.",
    scenario: "Imagine 30 campers and a cloudy morning. You turn a rained-out hike into a team scavenger hunt that everyone talks about at pickup.",
    facts: FACTS("High school diploma or equivalent", "$36,560/year", "346,900", "67,000"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$44K")], best: [K("District of Columbia", "$50K"), K("Washington", "$46K"), K("Alaska", "$46K")] },
    knowAbout: ["Clear speaking", "Public safety", "Helping the public", "Teaching and training", "Rules and laws"],
    goodAt: ["Listening closely", "Talking clearly", "Watching over a group", "Planning activities", "Teaching new skills"],
    software: ["Scheduling software", "Microsoft Publisher", "Microsoft Excel", "Microsoft PowerPoint", "YouTube"],
    ladder: [
      { number: "1", jobTitle: "Recreation Aide", pay: "$28K", description: "You help run activities and keep everyone safe while you learn.", whatYouDo: ["Set up games", "Watch over groups", "Give first aid", "Clean up after events"], toGetHere: ["High school diploma", "CPR and first aid"] },
      { number: "2", jobTitle: "Recreation Worker", pay: "$37K", description: "You plan and lead your own activities for kids, teens or adults.", whatYouDo: ["Plan activities", "Lead sports and crafts", "Explain safety rules", "Keep attendance"], toGetHere: ["Time on the job", "Skills in sports or the arts"] },
      { number: "3", jobTitle: "Recreation Supervisor", pay: "$49K", description: "You lead a team of workers and run programs at a park or center.", whatYouDo: ["Train staff", "Assign duties", "Run special events", "Check how programs are going"], toGetHere: ["Years of recreation work", "A degree helps"] },
    ],
    education: { studies: [{ name: "Outdoor Education" }], where: [{ count: "", credential: "Certificate, under a year" }, { count: "", credential: "Bachelor's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "Most recreation workers need a high school diploma. A short period of training on the job follows.", noBachelorPct: "63%", distribution: MIX(4.1, 21.8, 26.1, 11.0, 26.7, 8.8, 1.5) },
      pay: { starting: "$27,600", typical: "$36,560", top: "$50,410", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +15,000 by 2035. It is growing about as fast as most jobs.` },
    },
  },
  "tour-guide": {
    slug: "tour-guide",
    title: "Tour Guide",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/tour-guide.webp",
    summary: "Leads groups through cities, parks, museums and historic sites and brings their stories to life.",
    scenario: "Imagine 25 visitors on a historic street. You stop at an old doorway and tell a story that makes everyone pull out their phones.",
    facts: FACTS("High school diploma or equivalent", "$38,120/year", "62,200", "11,900"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$38K")], best: [K("Arizona", "$71K"), K("Washington", "$57K"), K("District of Columbia", "$52K")] },
    knowAbout: ["Helping visitors", "Clear speaking", "History", "Telling stories well", "Teaching and training"],
    goodAt: ["Talking to a crowd", "Listening to questions", "Keeping a group together", "Reading how people feel", "Keeping on time"],
    software: ["TourTech TourTools", "GPS software", "Zoom", "Microsoft PowerPoint", "Facebook"],
    ladder: [
      { number: "1", jobTitle: "New Tour Guide", pay: "$29K", description: "You learn the route and the stories and lead your first tours.", whatYouDo: ["Greet visitors", "Learn the route", "Answer questions", "Keep groups safe"], toGetHere: ["High school diploma", "Company training"] },
      { number: "2", jobTitle: "Tour Guide", pay: "$38K", description: "You lead tours on your own and plan stops that fit each group.", whatYouDo: ["Lead tours", "Research site history", "Pick routes", "Run school programs"], toGetHere: ["Time leading tours", "Strong speaking skills"] },
      { number: "3", jobTitle: "Lead Guide or Tour Director", pay: "$48K", description: "You run longer trips, train other guides and handle problems on the road.", whatYouDo: ["Lead multi-day trips", "Train guides", "Check supplies", "Handle emergencies"], toGetHere: ["Years of guiding", "First aid training"] },
    ],
    education: { studies: [{ name: "History, General" }, { name: "Archeology" }, { name: "Tourism and Travel Services Management" }], where: [{ count: "", credential: "Certificate, under a year" }, { count: "", credential: "Bachelor's degree" }] },
    sources: `${S} BLS reports tour guides and travel guides as one group, so pay, growth and the degree mix are for that whole group.`,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "Most guides learn on the job. A love of history or the outdoors and strong speaking skills help most.", noBachelorPct: "53%", distribution: MIX(5.7, 18.9, 21.1, 7.1, 32.2, 13.8, 1.2) },
      pay: { starting: "$28,520", typical: "$38,120", top: "$60,930", note: "BLS counts tour guides together with travel guides, so these figures are for that whole group." },
      openings: { note: `${OPEN} The job itself changes by about +3,900 by 2035. It is growing faster than most jobs.` },
    },
  },
  "travel-agent": {
    slug: "travel-agent",
    title: "Travel Agent",
    world: "Personal Care & Community Services",
    photo: "/images/app/browse/travel-agent.webp",
    summary: "Plans and books trips for people, from flights and hotels to full tour packages.",
    scenario: "Imagine a family dreaming of a beach trip on a tight budget. You find the flights, the hotel and the tours, and the whole trip fits.",
    facts: FACTS("High school diploma or equivalent", "$50,160/year", "61,500", "5,900"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$48K")], best: [K("Nevada", "$65K"), K("Connecticut", "$64K"), K("District of Columbia", "$64K")] },
    knowAbout: ["Helping customers", "Clear speaking", "Sales and marketing", "Geography", "Computers"],
    goodAt: ["Helping people", "Listening to what clients want", "Selling an idea", "Comparing prices", "Fixing travel problems"],
    software: ["Amadeus CRS", "Sabre", "SAP Concur", "Rezdy booking software", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Travel Agent Trainee", pay: "$35K", description: "You learn the booking systems and help senior agents plan trips.", whatYouDo: ["Book flights and hotels", "Answer client calls", "Compare prices", "Keep client records"], toGetHere: ["High school diploma", "Agency training"] },
      { number: "2", jobTitle: "Travel Agent", pay: "$50K", description: "You plan whole trips for your own clients and solve problems when plans change.", whatYouDo: ["Plan trips", "Sell tour packages", "Collect payments", "Fix travel problems"], toGetHere: ["Time booking trips", "Certification helps"] },
      { number: "3", jobTitle: "Senior Travel Advisor", pay: "$63K", description: "You focus on a kind of travel, like cruises or business trips, and build a loyal client list.", whatYouDo: ["Plan complex trips", "Run group travel", "Work with suppliers", "Guide newer agents"], toGetHere: ["Years as an agent", "A specialty"] },
    ],
    education: { studies: [{ name: "Tourism and Travel Services Marketing Operations" }, { name: "Selling Skills and Sales Operations" }], where: [{ count: "", credential: "Certificate, under a year" }, { count: "", credential: "Associate's degree" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "High school diploma or equivalent", experienceFirst: "No. You can start without it", trainingAfterHiring: "On-the-job training", note: "A high school diploma is the usual way in. Agencies train new agents on their booking systems.", noBachelorPct: "57%", distribution: MIX(1.4, 16.1, 26.4, 12.6, 32.2, 10.3, 1.0) },
      pay: { starting: "$34,610", typical: "$50,160", top: "$76,660", note: "12% work for themselves, so this describes the ones with a boss." },
      openings: { note: `${OPEN} The job itself changes by about +100 by 2035. It is holding about steady.` },
    },
  },
  "anthropologist-or-archaeologist": {
    slug: "anthropologist-or-archaeologist",
    title: "Anthropologist or Archaeologist",
    world: "Science & Research",
    photo: "/images/app/browse/anthropologist-or-archaeologist.webp",
    summary: "Studies how people live and lived, from cultures today to clues dug up from the past.",
    scenario: "Imagine brushing dirt off a clay pot that no one has touched in 800 years. You log where it sat, and it helps tell how a whole village lived.",
    facts: FACTS("Master's degree", "$70,770/year", "10,200", "800"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$69K")], best: [K("Massachusetts", "$108K"), K("Hawaii", "$96K"), K("Alaska", "$93K")] },
    knowAbout: ["People and cultures", "History and archaeology", "Clear reading and writing", "Other languages", "Maps and land"],
    goodAt: ["Writing up what you find", "Talking with people", "Listening closely", "Thinking through evidence", "Teaching others"],
    software: ["ESRI ArcGIS", "Autodesk AutoCAD", "IBM SPSS Statistics", "Adobe Illustrator", "GPS software"],
    ladder: [
      { number: "1", jobTitle: "Field Archaeologist", pay: "$49K", description: "You dig, record and sort finds on site with a field team.", whatYouDo: ["Dig test pits", "Record finds", "Map the site", "Take photos"], toGetHere: ["Bachelor's in anthropology or archaeology", "Field school"] },
      { number: "2", jobTitle: "Anthropologist or Archaeologist", pay: "$71K", description: "You plan research, study people or sites and write up what it means.", whatYouDo: ["Plan research", "Interview people", "Study artifacts", "Write reports"], toGetHere: ["Master's degree", "Field experience"] },
      { number: "3", jobTitle: "Research Archaeologist", pay: "$90K", description: "You lead whole projects, run field sites and train the next field team.", whatYouDo: ["Lead projects", "Run field sites", "Train staff and students", "Share findings"], toGetHere: ["Years of research", "A Ph.D. helps"] },
    ],
    education: { studies: [{ name: "Anthropology, General" }, { name: "Archeology" }, { name: "Cultural Anthropology" }, { name: "Physical and Biological Anthropology" }, { name: "Forensic Anthropology" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }, { count: "", credential: "Doctorate" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "Master's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "A master's degree and field work are the usual way in. Some research and teaching jobs ask for a Ph.D.", noBachelorPct: "10%", distribution: MIX(0.0, 3.8, 3.9, 2.1, 33.4, 37.6, 19.2) },
      pay: { starting: "$49,050", typical: "$70,770", top: "$108,060", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +600 by 2035. It is growing faster than most jobs.` },
    },
  },
  astronomer: {
    slug: "astronomer",
    title: "Astronomer",
    world: "Science & Research",
    photo: "/images/app/browse/astronomer.webp",
    summary: "Studies stars, planets and galaxies to learn how the universe works.",
    scenario: "Imagine data from a space telescope landing in your inbox at midnight. You find a faint dip in a star's light that could be a brand-new planet.",
    facts: FACTS("Doctoral or professional degree", "$128,820/year", "2,400", "100"),
    payByState: { title: "Pay by state", best: [K("Maryland", "$145K"), K("Virginia", "$133K"), K("California", "$128K")] },
    knowAbout: ["Physics", "Math", "Computers and coding", "Clear reading and writing", "Teaching and training"],
    goodAt: ["Reading science papers", "Working with numbers", "Solving tricky problems", "Writing up results", "Coding to study data"],
    software: ["Python", "MATLAB", "R", "C++", "Linux"],
    ladder: [
      { number: "1", jobTitle: "Postdoctoral Researcher", pay: "", description: "After your Ph.D., you do research for a few years under a senior scientist.", whatYouDo: ["Analyze telescope data", "Write papers", "Present at conferences", "Help mentor students"], toGetHere: ["Ph.D. in astronomy or physics"] },
      { number: "2", jobTitle: "Astronomer", pay: "$129K", description: "You lead your own research and share it with scientists around the world.", whatYouDo: ["Plan observations", "Analyze data", "Build theories", "Publish findings"], toGetHere: ["Postdoctoral research", "A strong record of papers"] },
      { number: "3", jobTitle: "Senior Astronomer", pay: "$166K", description: "You lead big projects, build new instruments and guide younger scientists.", whatYouDo: ["Lead research teams", "Design instruments", "Win research funding", "Mentor scientists"], toGetHere: ["Years of research", "Leading major projects"] },
    ],
    education: { studies: [{ name: "Astronomy" }, { name: "Astrophysics" }, { name: "Physics and Astronomy" }, { name: "Planetary Astronomy and Science" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Doctorate" }] },
    sources: S,
    factDetails: {
      degree: { doorAsksFor: "Doctoral or professional degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "Astronomers typically need a Ph.D. for jobs in research and teaching at colleges.", noBachelorPct: "0%", distribution: MIX(0.0, 0.0, 0.0, 0.0, 23.4, 24.8, 51.8) },
      pay: { starting: "$78,010", typical: "$128,820", top: "$195,190", note: "Half of the people in this job earn more than the typical figure and half earn less." },
      openings: { note: `${OPEN} The job itself changes by about +200 by 2035. It is growing much faster than most jobs.` },
    },
  },
  "bioinformatics-scientist": {
    slug: "bioinformatics-scientist",
    title: "Bioinformatics Scientist",
    world: "Science & Research",
    photo: "/images/app/browse/bioinformatics-scientist.webp",
    summary: "Uses computers and code to find meaning in huge sets of DNA and other biology data.",
    scenario: "Imagine a lab sends you the DNA of 1,000 patients. You write the code that spots the one gene change they all share.",
    facts: FACTS("Bachelor's degree", "$98,920/year", "59,600", "4,300"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$76K")], best: [K("Maryland", "$126K"), K("California", "$124K"), K("Massachusetts", "$123K")] },
    knowAbout: ["Biology", "Computers and coding", "How things get engineered and built", "Math", "Chemistry"],
    goodAt: ["Reading science papers", "Thinking through data", "Writing code", "Solving tricky problems", "Explaining results"],
    software: ["SQL", "MATLAB", "Linux", "Git", "Amazon Web Services"],
    ladder: [
      { number: "1", jobTitle: "Bioinformatics Research Associate", pay: "$60K", description: "You run data tools and clean up results for the scientists on your team.", whatYouDo: ["Run analysis tools", "Clean up data", "Build databases", "Test new software"], toGetHere: ["Bachelor's in biology, computer science or bioinformatics"] },
      { number: "2", jobTitle: "Bioinformatics Scientist", pay: "$99K", description: "You build new ways to study genes and proteins and help guide research.", whatYouDo: ["Analyze DNA data", "Write new code", "Advise researchers", "Publish results"], toGetHere: ["Master's or Ph.D.", "Coding and biology skills"] },
      { number: "3", jobTitle: "Bioinformatics Lab Director", pay: "$167K", description: "You lead a team of scientists and decide which research to chase next.", whatYouDo: ["Lead the team", "Set research goals", "Manage budgets", "Work with partners"], toGetHere: ["Years of research", "Leading projects"] },
    ],
    education: { studies: [{ name: "Computational Biology" }, { name: "Biomathematics, Bioinformatics, and Computational Biology, Other" }, { name: "Genome Sciences/Genomics" }, { name: "Biostatistics" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }, { count: "", credential: "Doctorate" }] },
    sources: `${S} BLS has no separate bioinformatics scientist job, so pay, growth and the degree mix are for all biological scientists not listed elsewhere.`,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "A bachelor's can get you in the door. Most people in this group go on to a master's or Ph.D.", noBachelorPct: "0%", distribution: MIX(0.0, 0.0, 0.0, 0.0, 46.2, 31.9, 21.9) },
      pay: { starting: "$60,430", typical: "$98,920", top: "$168,010", note: "BLS counts bioinformatics scientists inside the larger group of biological scientists, so these figures are for that whole group." },
      openings: { note: `${OPEN} The job itself changes by about +2,800 by 2035. It is growing faster than most jobs.` },
    },
  },
  biologist: {
    slug: "biologist",
    title: "Biologist",
    world: "Science & Research",
    photo: "/images/app/browse/biologist.webp",
    summary: "Studies living things, from tiny cells to whole forests, to learn how life works.",
    scenario: "Imagine wading into a cold river at sunrise to count young salmon. Your numbers help decide how the river gets protected.",
    facts: FACTS("Bachelor's degree", "$98,920/year", "59,600", "4,300"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$76K")], best: [K("Maryland", "$126K"), K("California", "$124K"), K("Massachusetts", "$123K")] },
    knowAbout: ["Biology", "Teaching and training", "Clear reading and writing", "Math", "Chemistry"],
    goodAt: ["Reading science papers", "Writing up results", "Thinking through data", "Listening closely", "Solving tricky problems"],
    software: ["R", "ESRI ArcGIS", "Minitab", "SQL", "Microsoft Excel"],
    ladder: [
      { number: "1", jobTitle: "Biological Technician", pay: "$58K", description: "You collect samples, run lab tests and record data for scientists.", whatYouDo: ["Collect samples", "Run lab tests", "Record data", "Care for lab gear"], toGetHere: ["Bachelor's in biology"] },
      { number: "2", jobTitle: "Biologist", pay: "$99K", description: "You plan studies, collect data on plants or animals and report what you find.", whatYouDo: ["Plan studies", "Study plants and animals", "Analyze data", "Write reports"], toGetHere: ["Bachelor's or master's", "Lab or field experience"] },
      { number: "3", jobTitle: "Senior Biologist", pay: "$128K", description: "You lead research, write grants and supervise technicians and other scientists.", whatYouDo: ["Lead research", "Write grant proposals", "Supervise staff", "Work with agencies"], toGetHere: ["Years of research", "A Ph.D. helps"] },
    ],
    education: { studies: [{ name: "Biology/Biological Sciences, General" }, { name: "Ecology" }, { name: "Marine Biology and Biological Oceanography" }, { name: "Molecular Biology" }, { name: "Conservation Biology" }], where: [{ count: "", credential: "Bachelor's degree" }, { count: "", credential: "Master's degree" }, { count: "", credential: "Doctorate" }] },
    sources: `${S} BLS has no separate biologist job, so pay, growth and the degree mix are for all biological scientists not listed elsewhere.`,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "A bachelor's in biology opens the door. Most people in this group also earn a master's or Ph.D.", noBachelorPct: "0%", distribution: MIX(0.0, 0.0, 0.0, 0.0, 46.2, 31.9, 21.9) },
      pay: { starting: "$60,430", typical: "$98,920", top: "$168,010", note: "BLS counts biologists inside the larger group of biological scientists, so these figures are for that whole group." },
      openings: { note: `${OPEN} The job itself changes by about +2,800 by 2035. It is growing faster than most jobs.` },
    },
  },
  "cell-therapy-manufacturing-associate": {
    slug: "cell-therapy-manufacturing-associate",
    title: "Cell Therapy Manufacturing Associate",
    world: "Science & Research",
    photo: "/images/app/browse/cell-therapy-manufacturing-associate.webp",
    summary: "Grows and prepares living cells in a clean lab so they can be made into medicine for patients.",
    scenario: "Imagine a bag of cells that will become one patient's cancer treatment. You follow every step exactly, because there is only one batch.",
    facts: FACTS("Bachelor's degree", "$57,510/year", "74,400", "9,400"),
    payByState: { title: "Pay by state", yourStates: [K("South Dakota", "$46K")], best: [K("California", "$78K"), K("New Jersey", "$70K"), K("Massachusetts", "$67K")] },
    knowAbout: ["Biology", "Clear reading and writing", "Computers and lab equipment", "Chemistry", "Math"],
    goodAt: ["Following steps exactly", "Checking quality", "Keeping careful records", "Watching how a process runs", "Reading instructions closely"],
    software: ["LIMS", "Microsoft Excel", "SAS", "Microsoft Access", "Microsoft Project"],
    ladder: [
      { number: "1", jobTitle: "Manufacturing Associate I", pay: "$40K", description: "You prepare supplies and help run each step while a lead checks your work.", whatYouDo: ["Prepare supplies", "Clean work areas", "Log every step", "Weigh and mix solutions"], toGetHere: ["Bachelor's in biology or a related field", "Lab experience in school"] },
      { number: "2", jobTitle: "Cell Therapy Manufacturing Associate", pay: "$58K", description: "You grow and process cells on your own and make sure each batch meets the rules.", whatYouDo: ["Grow and process cells", "Run lab equipment", "Record test data", "Check that work meets standards"], toGetHere: ["Time on the production floor", "Clean room training"] },
      { number: "3", jobTitle: "Senior Manufacturing Associate", pay: "$72K", description: "You lead a shift, train new associates and fix problems in the process.", whatYouDo: ["Lead a shift", "Train new staff", "Fix process problems", "Review batch records"], toGetHere: ["Years in production", "Strong safety record"] },
    ],
    education: { studies: [{ name: "Biology/Biotechnology Technology/Technician" }, { name: "Cell/Cellular and Molecular Biology" }, { name: "Biology/Biological Sciences, General" }, { name: "Microbiology, General" }], where: [{ count: "", credential: "Associate's degree" }, { count: "", credential: "Bachelor's degree" }] },
    sources: `${S} BLS has no separate cell therapy manufacturing job, so pay, growth, the degree mix, tasks and skills are for biological technicians, the closest match.`,
    factDetails: {
      degree: { doorAsksFor: "Bachelor's degree", experienceFirst: "No. You can start without it", trainingAfterHiring: "None required", note: "Most biological technicians need a bachelor's in biology or a related field. Some jobs hire with less.", noBachelorPct: "52%", distribution: MIX(2.1, 16.8, 21.3, 11.6, 39.1, 6.7, 2.4) },
      pay: { starting: "$40,330", typical: "$57,510", top: "$84,940", note: "BLS counts this job inside the larger group of biological technicians, so these figures are for that whole group." },
      openings: { note: `${OPEN} The job itself changes by about +5,500 by 2035. It is growing much faster than most jobs.` },
    },
  },
};
