// ARTS, MEDIA & SPORT PROFILES (2026-09-19). The 24 arts careers the team's
// poster library added on 19 Sept get the same page shape as every other
// career (summary, "imagine" line, four quick facts, pay by state, know
// about / good at / software, a three-rung ladder, education, fact details).
// United States context throughout: job descriptions, knowledge and skills
// follow O*NET's framing for the matching SOC occupation; pay, employment
// and openings are rounded from the BLS Occupational Outlook Handbook and
// OEWS (May 2024) for that occupation. Where BLS publishes only an hourly
// wage (actors, dancers, musicians) the page says so instead of inventing an
// annual figure. Figures are approximate prototype data, not sourced to the
// dollar; replace with production data when it is available.
import { ALL_CATALOG_CAREERS } from "@/components/app/catalog";
import type { CareerProfile, ProfileRung } from "./profiles";
import { careerSlug } from "./slug";

const SOURCES = "Job description and skills from O*NET (USDOL/ETA). Pay and growth from the U.S. Bureau of Labor Statistics.";
/** the demo student's state, the same one every generated profile uses */
const HOME_STATE = "South Dakota";

type Dist = [number, number, number, number, number, number, number]; // no HS, HS, some college, associate's, bachelor's, master's, doctorate

type Compact = {
  title: string;
  summary: string;
  scenario: string;
  degree: string;
  pay: string;
  people: string;
  openings: string;
  homePay: string;
  best: [string, string][];
  knowAbout: string[];
  goodAt: string[];
  software: string[];
  ladder: [string, string, string, string[], string[]][];
  studies: string[];
  where: [string, string][];
  degreeNote: string;
  experienceFirst: string;
  dist: Dist;
  payRange: [string, string, string];
  payNote?: string;
  outlook: string;
};

const LABELS = ["Did not finish high school", "Finished high school", "Some college, no degree", "Associate's degree", "Bachelor's degree", "Master's degree", "Doctorate or professional degree"];

function build(c: Compact): CareerProfile {
  const slug = careerSlug(c.title);
  const catalog = ALL_CATALOG_CAREERS.find((k) => k.title === c.title);
  const noBachelor = c.dist[0] + c.dist[1] + c.dist[2] + c.dist[3];
  const ladder: ProfileRung[] = c.ladder.map(([jobTitle, pay, description, whatYouDo, toGetHere], i) => ({ number: String(i + 1), jobTitle, pay, description, whatYouDo, toGetHere }));
  return {
    slug,
    title: c.title,
    world: "Arts, Media & Sport",
    photo: catalog?.photo ?? `/images/app/browse/${slug}.webp`,
    summary: c.summary,
    scenario: c.scenario,
    facts: [
      { label: "Typical degree", value: c.degree },
      { label: "Typical pay", value: c.pay },
      { label: "People doing it", value: c.people },
      { label: "Jobs open each year", value: c.openings },
    ],
    payByState: { title: "Pay by state", yourStates: [{ state: HOME_STATE, pay: c.homePay }], best: c.best.map(([state, pay]) => ({ state, pay })) },
    knowAbout: c.knowAbout,
    goodAt: c.goodAt,
    software: c.software,
    ladder,
    education: { studies: c.studies.map((name) => ({ name })), where: c.where.map(([count, credential]) => ({ count, credential })) },
    sources: SOURCES,
    factDetails: {
      degree: {
        doorAsksFor: c.degree,
        experienceFirst: c.experienceFirst,
        trainingAfterHiring: "On the job",
        note: c.degreeNote,
        noBachelorPct: `${noBachelor}%`,
        distribution: LABELS.map((label, i) => ({ label, pct: c.dist[i] })),
      },
      pay: { starting: c.payRange[0], typical: c.payRange[1], top: c.payRange[2], note: c.payNote },
      openings: { note: `Counts every job that needs filling, mostly people moving on rather than brand-new roles. ${c.outlook}` },
    },
  };
}

const LIST: Compact[] = [
  {
    title: "Actor",
    summary: "Plays a character on stage, on screen or in a voice booth so a story feels real.",
    scenario: "Imagine your third audition this week. You have two pages, one shot, and a casting director who has seen forty people before lunch.",
    degree: "No set degree; training through theater programs, classes and experience",
    pay: "$23.33/hour",
    people: "63,800",
    openings: "7,500",
    homePay: "$16/hr",
    best: [["New York", "$34/hr"], ["California", "$31/hr"], ["Georgia", "$27/hr"]],
    knowAbout: ["Acting technique and scene study", "Scripts, story and character", "Voice, speech and movement", "How film, TV and theater are made", "Auditions, agents and unions"],
    goodAt: ["Memorizing lines fast", "Taking direction", "Listening and reacting", "Handling rejection and staying ready", "Being on time, every time"],
    software: ["Actors Access", "Backstage", "Casting Networks", "Final Draft", "Zoom"],
    ladder: [
      ["Background or Student Actor", "$15/hr", "You take classes, do student films and community theater, and learn how a set runs.", ["Take classes", "Do student films", "Build a reel", "Learn set etiquette"], ["Acting classes or a theater program", "Headshots and a short reel"]],
      ["Working Actor", "$23/hr", "You audition weekly, book commercials, regional theater and small roles, and join a union when you qualify.", ["Audition weekly", "Book commercials and small roles", "Work with an agent", "Keep training"], ["An agent or manager", "SAG-AFTRA or Actors' Equity eligibility"]],
      ["Series Regular or Lead", "$60/hr+", "You carry a show, a play or a film and pick the roles you want.", ["Lead a cast", "Develop projects", "Press and promotion", "Mentor newer actors"], ["Years of credits", "A reputation directors trust"]],
    ],
    studies: ["Drama and Dramatics/Theatre Arts", "Acting", "Musical Theatre"],
    where: [["120", "Certificate or conservatory program"], ["90", "Associate's degree"], ["450", "Bachelor's degree"]],
    degreeNote: "Casting is on the audition, not the diploma. A theater degree or conservatory training builds the craft and the network.",
    experienceFirst: "No. You can start without it",
    dist: [3, 14, 22, 8, 43, 9, 1],
    payRange: ["$12/hr", "$23.33/hr", "$100/hr+"],
    payNote: "BLS reports actors by the hour because most work is short contracts. Union scale, residuals and star salaries sit far above the median.",
    outlook: "The job itself changes by about +2,000 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Audio and Video Technician",
    summary: "Sets up and runs the sound, video and projection gear for events, studios and venues.",
    scenario: "Imagine a keynote for 3,000 people. The CEO walks on in ten minutes and the wireless mic just dropped out.",
    degree: "Postsecondary certificate or associate's degree",
    pay: "$54,200/year",
    people: "82,600",
    openings: "9,000",
    homePay: "$44K",
    best: [["Washington", "$72K"], ["California", "$68K"], ["New York", "$66K"]],
    knowAbout: ["Sound, signal flow and acoustics", "Video, projection and LED walls", "Networking and streaming", "Electricity and power", "Live event production"],
    goodAt: ["Troubleshooting under pressure", "Cable management and setup", "Mixing a live room", "Reading a run of show", "Working long, odd hours"],
    software: ["QLab", "Dante Controller", "OBS Studio", "Barco Event Master", "Yamaha CL/QL editors"],
    ladder: [
      ["A/V Assistant", "$38K", "You load in, run cable and build stages, learning the gear one event at a time.", ["Set up gear", "Run cable", "Test signal", "Strike the show"], ["High school diploma", "An A/V certificate or venue training"]],
      ["Audio and Video Technician", "$54K", "You run sound and video for events, meetings and shows on your own.", ["Mix audio", "Run video and projection", "Stream the event", "Fix problems live"], ["2 to 4 years on crews", "AVIXA CTS certification helps"]],
      ["Technical Director", "$85K", "You design the whole system for a venue or a tour and lead the crew that runs it.", ["Design systems", "Lead the crew", "Budget the gear", "Work with producers"], ["Years of shows", "CTS-D or CTS-I certification"]],
    ],
    studies: ["Recording Arts Technology", "Audiovisual Communications Technologies", "Radio and Television"],
    where: [["210", "Certificate, under a year"], ["330", "Associate's degree"], ["190", "Bachelor's degree"]],
    degreeNote: "Most hires come from certificate and associate's programs plus hands-on time; venues care that you can make the show work.",
    experienceFirst: "No. You can start without it",
    dist: [3, 20, 26, 20, 27, 3, 1],
    payRange: ["$31,900", "$54,200", "$94,800"],
    outlook: "The job itself changes by about +2,600 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Broadcast Technician",
    summary: "Keeps TV and radio signals on the air, from studio cameras to transmitters and streams.",
    scenario: "Imagine the 6 p.m. news in a live break. A camera feed goes black and the anchor has 20 seconds of script left.",
    degree: "Associate's degree or postsecondary certificate",
    pay: "$56,100/year",
    people: "25,000",
    openings: "2,600",
    homePay: "$42K",
    best: [["New York", "$78K"], ["California", "$74K"], ["Washington", "$69K"]],
    knowAbout: ["Broadcast signal flow", "Video switching and playout", "Transmitters and FCC rules", "IP video and streaming", "Studio and remote production"],
    goodAt: ["Staying calm on live TV", "Fixing gear fast", "Following a rundown", "Careful, repeatable setups", "Working nights, weekends and elections"],
    software: ["Ross Xpression", "Grass Valley switchers", "Avid iNEWS", "Dalet", "vMix"],
    ladder: [
      ["Production Assistant", "$36K", "You run camera, audio and playback in the studio and learn how a broadcast is built.", ["Run studio camera", "Playback and graphics", "Set up for shows", "Log tapes and files"], ["High school diploma", "A broadcasting or electronics program"]],
      ["Broadcast Technician", "$56K", "You switch, transmit and maintain the systems that keep the station on air.", ["Operate the control room", "Maintain transmitters", "Route signals", "Troubleshoot live"], ["2 to 4 years in a station", "SBE certification helps"]],
      ["Chief Engineer", "$95K", "You own the station's whole technical plant and plan the upgrades.", ["Plan systems", "Lead engineers", "Manage FCC compliance", "Budget the plant"], ["Years in broadcast", "SBE Certified Broadcast Engineer"]],
    ],
    studies: ["Radio and Television Broadcasting Technology", "Electronics Engineering Technology", "Communications Technology"],
    where: [["140", "Certificate, under a year"], ["260", "Associate's degree"], ["180", "Bachelor's degree"]],
    degreeNote: "Stations hire from two-year broadcasting and electronics programs; a bachelor's helps for network and engineering leadership roles.",
    experienceFirst: "No. You can start without it",
    dist: [2, 17, 25, 22, 30, 3, 1],
    payRange: ["$31,200", "$56,100", "$110,000"],
    outlook: "The job itself changes by about -700 by 2034 as stations automate. It is declining slightly.",
  },
  {
    title: "Choreographer",
    summary: "Creates the dance moves for shows, music videos, musicals and dance companies.",
    scenario: "Imagine a music video shoot tomorrow. Eight dancers, one chorus, and the artist wants the hook to be something nobody has done.",
    degree: "No set degree; years of dance training, often a bachelor's in dance",
    pay: "$52,000/year",
    people: "6,000",
    openings: "800",
    homePay: "$38K",
    best: [["New York", "$74K"], ["California", "$70K"], ["Nevada", "$62K"]],
    knowAbout: ["Dance styles and technique", "Music, rhythm and counts", "Staging and how a stage reads", "Anatomy and injury prevention", "How shows and videos are produced"],
    goodAt: ["Inventing movement fast", "Teaching a room of dancers", "Giving clear notes", "Fitting dance to a camera or stage", "Leading rehearsals"],
    software: ["Spotify or Apple Music", "Adobe Premiere Pro", "Instagram and TikTok", "Google Workspace", "Rehearsal apps like Countz"],
    ladder: [
      ["Dancer and Assistant Choreographer", "$32K", "You perform, learn the choreographer's style and teach counts to the rest of the cast.", ["Perform", "Teach counts", "Run warmups", "Film rehearsals"], ["Years of dance training", "A company or studio that trusts you"]],
      ["Choreographer", "$52K", "You create routines for studios, videos, competitions and regional shows.", ["Create routines", "Cast dancers", "Run rehearsals", "Work with directors"], ["Credits on shows or videos", "A reel and a following"]],
      ["Resident or Lead Choreographer", "$90K", "You set the movement for tours, Broadway shows or a dance company and lead a team of assistants.", ["Lead a creative team", "Set a whole show", "Hire and mentor", "Restage productions"], ["Major credits", "A name directors and artists ask for"]],
    ],
    studies: ["Dance", "Musical Theatre", "Kinesiology"],
    where: [["60", "Certificate or conservatory program"], ["40", "Associate's degree"], ["190", "Bachelor's degree"]],
    degreeNote: "Choreographers rise from dancing. A dance degree deepens technique and teaching; the credits and the reel open the doors.",
    experienceFirst: "Yes. Years as a dancer first",
    dist: [2, 14, 20, 9, 45, 9, 1],
    payRange: ["$27,600", "$52,000", "$100,000+"],
    payNote: "Much of the work is project based, paid per show or per day; touring and Broadway sit at the top.",
    outlook: "The job itself changes by about +200 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Coach or Scout",
    summary: "Trains athletes and teams, or finds the next ones worth signing.",
    scenario: "Imagine a Friday night game, down by three, ninety seconds left. Forty kids look at you for the call.",
    degree: "Bachelor's degree for most school and college jobs",
    pay: "$45,910/year",
    people: "300,000",
    openings: "42,000",
    homePay: "$37K",
    best: [["New York", "$64K"], ["Nevada", "$60K"], ["Massachusetts", "$58K"]],
    knowAbout: ["The sport, inside and out", "Training, conditioning and nutrition", "Teaching and motivation", "Game strategy and film study", "Recruiting rules and eligibility"],
    goodAt: ["Leading a team", "Teaching a skill step by step", "Reading a game live", "Communicating with athletes and parents", "Evaluating talent"],
    software: ["Hudl", "TeamSnap", "Catapult", "Microsoft Excel", "Synergy Sports"],
    ladder: [
      ["Assistant or Youth Coach", "$28K", "You run drills, coach a position or an age group and learn how a program works.", ["Run drills", "Coach a position", "Break down film", "Manage practice"], ["Playing experience", "First aid, CPR and safety certifications"]],
      ["Head Coach or Scout", "$46K", "You run a high school or club program, or scout players for a college or pro team.", ["Plan the season", "Call the games", "Recruit or scout", "Mentor athletes"], ["Bachelor's degree for schools", "Years as an assistant"]],
      ["College or Professional Coach", "$100K+", "You lead a college program or a professional staff and are judged on wins and player development.", ["Lead a staff", "Recruit nationally", "Manage a budget", "Represent the program"], ["A winning record", "A network across the sport"]],
    ],
    studies: ["Kinesiology and Exercise Science", "Sport and Fitness Administration", "Physical Education Teaching and Coaching"],
    where: [["90", "Certificate, under a year"], ["160", "Associate's degree"], ["620", "Bachelor's degree"]],
    degreeNote: "Schools and colleges want a bachelor's, often with a teaching license. Club, youth and pro scouting jobs hire on experience and results.",
    experienceFirst: "Yes. Playing or assisting first",
    dist: [1, 8, 14, 7, 50, 18, 2],
    payRange: ["$23,000", "$45,910", "$99,000+"],
    payNote: "Many coaches are part time or paid a stipend on top of a teaching job; college and pro head coaches earn far above the median.",
    outlook: "The job itself changes by about +27,000 by 2034. It is growing faster than most jobs.",
  },
  {
    title: "Court Reporter or Captioner",
    summary: "Types every word of a trial, deposition or live broadcast in real time so nothing is lost.",
    scenario: "Imagine a witness talking at 220 words a minute. Your fingers are the official record and there is no rewind.",
    degree: "Postsecondary certificate or associate's degree",
    pay: "$63,940/year",
    people: "15,000",
    openings: "1,300",
    homePay: "$52K",
    best: [["New York", "$96K"], ["California", "$90K"], ["Texas", "$78K"]],
    knowAbout: ["Stenography and realtime writing", "Legal procedure and vocabulary", "English grammar and spelling", "Medical and technical terms", "Broadcast captioning standards"],
    goodAt: ["Typing 225 words a minute", "Deep focus for hours", "Accuracy under pressure", "Confidentiality", "Editing transcripts fast"],
    software: ["Case CATalyst", "Eclipse", "StenoCAT", "Microsoft Word", "Zoom"],
    ladder: [
      ["Steno Student or Scopist", "$35K", "You build speed on the steno machine and edit other reporters' transcripts.", ["Practice speed", "Edit transcripts", "Learn legal terms", "Shadow reporters"], ["A court reporting program", "Speed tests passed"]],
      ["Court Reporter or Captioner", "$64K", "You take the record in depositions and courtrooms, or caption live TV and events.", ["Take the record", "Caption live", "Certify transcripts", "Manage exhibits"], ["State license or RPR certification", "225 words a minute"]],
      ["Official Reporter or CART Provider", "$95K", "You hold a courtroom appointment or provide realtime access for deaf and hard of hearing clients at top rates.", ["Realtime in court", "CART for clients", "Train newer reporters", "Run a reporting firm"], ["RMR or CRR certification", "Years of realtime work"]],
    ],
    studies: ["Court Reporting/Court Reporter", "Legal Administrative Assistant", "Communication Disorders"],
    where: [["70", "Certificate, one to two years"], ["60", "Associate's degree"], ["20", "Bachelor's degree"]],
    degreeNote: "Nearly everyone trains in a court reporting program and passes a speed and accuracy test; many states license the job.",
    experienceFirst: "No. You can start without it",
    dist: [1, 10, 26, 34, 24, 4, 1],
    payRange: ["$36,700", "$63,940", "$120,000+"],
    payNote: "Freelance deposition reporters bill per page, so busy reporters in big legal markets earn well above the median.",
    outlook: "The job itself changes by about +300 by 2034. It is growing more slowly than most jobs, but retirements keep openings steady.",
  },
  {
    title: "Dancer",
    summary: "Performs choreography on stage, on tour, in videos and at theme parks and shows.",
    scenario: "Imagine opening night of a tour. Two hours of choreography in your body, a stadium in front of you, and one shot at the count.",
    degree: "No set degree; years of training, often a bachelor's in dance",
    pay: "$24.95/hour",
    people: "11,000",
    openings: "1,700",
    homePay: "$17/hr",
    best: [["New York", "$36/hr"], ["Nevada", "$33/hr"], ["California", "$31/hr"]],
    knowAbout: ["Ballet, jazz, hip hop and contemporary technique", "Music and counts", "Anatomy, stretching and injury care", "Auditions and casting", "How shows and tours are run"],
    goodAt: ["Picking up choreography fast", "Stamina and strength", "Performing with presence", "Taking notes without ego", "Staying healthy on the road"],
    software: ["Spotify or Apple Music", "Instagram and TikTok", "Backstage", "Casting Networks", "Google Calendar"],
    ladder: [
      ["Company Apprentice or Ensemble", "$17/hr", "You train daily, audition constantly and take ensemble spots, cruise ships and theme park shows.", ["Train daily", "Audition", "Learn ensemble parts", "Perform"], ["Years of studio training", "A dance program or conservatory"]],
      ["Professional Dancer", "$25/hr", "You work regularly in a company, a touring show, music videos or Broadway ensembles.", ["Perform nightly", "Rehearse new work", "Tour", "Keep your body ready"], ["Credits and a reel", "An agent or company contract"]],
      ["Principal Dancer or Dance Captain", "$45/hr+", "You dance lead roles or run the cast's rehearsals and keep the show clean on the road.", ["Dance lead roles", "Run rehearsals", "Teach the show", "Work with the choreographer"], ["Years in a company or show", "Trust of the creative team"]],
    ],
    studies: ["Dance", "Ballet", "Musical Theatre"],
    where: [["80", "Certificate or conservatory program"], ["40", "Associate's degree"], ["190", "Bachelor's degree"]],
    degreeNote: "Companies hire at the audition. A dance degree adds technique, teaching skills and a plan for the years after performing.",
    experienceFirst: "Yes. Years of training first",
    dist: [3, 18, 24, 8, 40, 6, 1],
    payRange: ["$14/hr", "$24.95/hr", "$50/hr+"],
    payNote: "BLS reports dancers by the hour because most contracts are short. Union contracts, Broadway and major tours pay the most.",
    outlook: "The job itself changes by about +500 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Fashion Designer",
    summary: "Designs the clothes, shoes and accessories people wear, from sketch to sample to store.",
    scenario: "Imagine a buyer in front of your rack. She has four minutes and one open slot for spring, and she just picked up your jacket.",
    degree: "Bachelor's degree",
    pay: "$79,290/year",
    people: "28,300",
    openings: "2,300",
    homePay: "$55K",
    best: [["New York", "$96K"], ["California", "$90K"], ["Washington", "$86K"]],
    knowAbout: ["Fabric, fit and construction", "Trends and fashion history", "Sketching and technical drawing", "Sourcing, costing and production", "Sustainability and materials"],
    goodAt: ["Drawing and visual thinking", "Sewing and draping", "Editing a collection", "Presenting a vision", "Working to a deadline and a budget"],
    software: ["Adobe Illustrator", "Adobe Photoshop", "CLO 3D", "Gerber AccuMark", "Procreate"],
    ladder: [
      ["Design Assistant", "$48K", "You sketch flats, source fabric, track samples and keep the designer's line sheet current.", ["Sketch flats", "Source fabric", "Track samples", "Prepare presentations"], ["Bachelor's degree in fashion design", "Internships and a portfolio"]],
      ["Fashion Designer", "$79K", "You design a category or a collection, fit samples and hand off tech packs to production.", ["Design collections", "Fit samples", "Build tech packs", "Present to buyers"], ["3 to 5 years assisting", "A portfolio of produced work"]],
      ["Design Director or Own Label", "$130K+", "You set the creative direction for a brand or run your own label.", ["Set the vision", "Lead a design team", "Manage the calendar", "Run the business"], ["Years of collections", "A name in the industry"]],
    ],
    studies: ["Fashion/Apparel Design", "Apparel and Textiles", "Fashion Merchandising"],
    where: [["60", "Certificate or associate's degree"], ["150", "Bachelor's degree"], ["30", "Master's degree"]],
    degreeNote: "Brands hire from fashion programs and on the portfolio; the degree gives you the technical skills and the internships.",
    experienceFirst: "No. You can start without it",
    dist: [1, 8, 14, 12, 55, 9, 1],
    payRange: ["$40,700", "$79,290", "$160,000+"],
    outlook: "The job itself changes by about +800 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Film and Video Editor",
    summary: "Cuts raw footage into the film, show, ad or video people actually watch.",
    scenario: "Imagine 40 hours of footage, a 90 second trailer due Friday, and a director who wants it to feel like a heartbeat.",
    degree: "Bachelor's degree",
    pay: "$66,600/year",
    people: "35,000",
    openings: "3,700",
    homePay: "$46K",
    best: [["California", "$94K"], ["New York", "$88K"], ["Georgia", "$70K"]],
    knowAbout: ["Story structure and pacing", "Video codecs, formats and workflows", "Sound design and music", "Color and visual effects basics", "How a production is organized"],
    goodAt: ["Finding the story in the footage", "Rhythm and timing", "Taking notes from directors and clients", "Staying organized across thousands of clips", "Long focused sessions"],
    software: ["Adobe Premiere Pro", "Avid Media Composer", "DaVinci Resolve", "Adobe After Effects", "Frame.io"],
    ladder: [
      ["Assistant Editor", "$45K", "You ingest, sync and organize footage, build rough assemblies and keep the project clean.", ["Ingest and sync", "Organize media", "Build assemblies", "Export cuts for review"], ["Bachelor's degree or a strong reel", "Internships or post house experience"]],
      ["Editor", "$67K", "You cut the piece, shape the story and work directly with the director or client.", ["Cut the story", "Sound and music passes", "Review with clients", "Deliver finals"], ["3 to 5 years assisting", "A reel of finished work"]],
      ["Senior Editor or Post Supervisor", "$115K", "You lead the cutting room on features, series or a brand's whole output.", ["Lead the edit", "Manage assistants", "Own the schedule", "Guide color and sound"], ["Credits on released work", "Trust of directors and producers"]],
    ],
    studies: ["Cinematography and Film/Video Production", "Digital Communication and Media", "Film/Cinema/Media Studies"],
    where: [["110", "Certificate or associate's degree"], ["390", "Bachelor's degree"], ["60", "Master's degree"]],
    degreeNote: "Most editors hold a film or media bachelor's, but the reel gets the job; many start as assistants at post houses.",
    experienceFirst: "No. You can start without it",
    dist: [1, 6, 14, 8, 62, 8, 1],
    payRange: ["$36,400", "$66,600", "$150,000+"],
    outlook: "The job itself changes by about +2,800 by 2034. It is growing faster than most jobs as streaming and online video keep expanding.",
  },
  {
    title: "Floral Designer",
    summary: "Designs bouquets, arrangements and event florals for weddings, shops and celebrations.",
    scenario: "Imagine a 200 guest wedding. Six hundred stems arrived this morning, the ceremony is at four, and the bride changed her mind about peonies.",
    degree: "High school diploma or equivalent",
    pay: "$35,950/year",
    people: "43,000",
    openings: "5,900",
    homePay: "$32K",
    best: [["Washington", "$46K"], ["New York", "$45K"], ["California", "$44K"]],
    knowAbout: ["Flowers, foliage and seasons", "Color and composition", "Care and handling of cut flowers", "Event and wedding planning", "Pricing and ordering"],
    goodAt: ["Working with your hands", "Customer conversations", "Quick, clean design", "Early mornings and event days", "Staying calm when stems wilt"],
    software: ["Square", "Curate", "Details Flowers", "Instagram", "Canva"],
    ladder: [
      ["Shop Assistant", "$28K", "You process flowers, build everyday arrangements and take orders at the counter.", ["Process stems", "Build arrangements", "Take orders", "Deliver"], ["High school diploma", "Shop training or a floral certificate"]],
      ["Floral Designer", "$36K", "You design custom work, consult with couples and clients, and run events.", ["Design custom pieces", "Consult clients", "Set up events", "Order stock"], ["2 to 3 years in a shop", "AIFD certification helps"]],
      ["Head Designer or Studio Owner", "$60K+", "You run a studio, book weddings and events, and lead a team of designers.", ["Run the studio", "Book events", "Lead designers", "Manage the money"], ["A portfolio of events", "Business skills"]],
    ],
    studies: ["Floriculture/Floristry Operations", "Horticulture", "Event Planning"],
    where: [["120", "Certificate, under a year"], ["60", "Associate's degree"], ["20", "Bachelor's degree"]],
    degreeNote: "Shops train on the job; a floral certificate or design classes help you start faster. Wedding studios hire on the portfolio.",
    experienceFirst: "No. You can start without it",
    dist: [5, 34, 25, 12, 21, 2, 1],
    payRange: ["$25,900", "$35,950", "$55,600"],
    payNote: "Wedding and event studios earn the most; grocery store floral counters the least.",
    outlook: "The job itself changes by about -5,000 by 2034 as supermarkets take more of the business. It is declining, but events keep hiring.",
  },
  {
    title: "Game Producer",
    summary: "Runs the team and the schedule that ships a video game on time.",
    scenario: "Imagine a launch date in eleven weeks, 60 people on the team, and a boss fight that still crashes on console.",
    degree: "Bachelor's degree",
    pay: "$85,320/year",
    people: "178,000",
    openings: "16,600",
    homePay: "$62K",
    best: [["California", "$126K"], ["Washington", "$118K"], ["New York", "$102K"]],
    knowAbout: ["How games are built, from design to QA", "Project management and scheduling", "Budgets and publishing", "Game engines and pipelines", "Player communities and live service"],
    goodAt: ["Keeping many people moving", "Clear writing and meetings", "Making trade-offs", "Spotting risk early", "Staying steady near launch"],
    software: ["Jira", "Confluence", "Perforce", "Unreal Engine or Unity", "Slack"],
    ladder: [
      ["Associate Producer or QA Lead", "$55K", "You track tasks, run standups and keep bugs and builds organized for a feature team.", ["Track tasks", "Run standups", "Triage bugs", "Write status reports"], ["Bachelor's degree", "QA or internship experience in games"]],
      ["Game Producer", "$85K", "You own a team's schedule, scope and delivery from prototype to ship.", ["Own the schedule", "Manage scope", "Coordinate departments", "Ship milestones"], ["3 to 5 years in production", "At least one shipped title"]],
      ["Executive Producer", "$160K+", "You run a whole game or franchise, its budget and its studio relationships.", ["Run the project", "Manage the budget", "Work with publishers", "Lead producers"], ["Multiple shipped games", "A track record of launches"]],
    ],
    studies: ["Game and Interactive Media Design", "Computer Science", "Business Administration and Management"],
    where: [["70", "Certificate or associate's degree"], ["260", "Bachelor's degree"], ["50", "Master's degree"]],
    degreeNote: "Studios hire producers with a bachelor's and shipped experience; many start in QA or as associate producers. BLS groups the job with producers and directors.",
    experienceFirst: "Yes. QA or associate roles first",
    dist: [1, 5, 12, 7, 60, 14, 1],
    payRange: ["$42,300", "$85,320", "$180,000+"],
    payNote: "Figures follow the BLS producers and directors occupation; large studios in California and Washington pay well above it.",
    outlook: "The job itself changes by about +14,000 by 2034 across producers and directors. It is growing faster than most jobs.",
  },
  {
    title: "Graphic Designer",
    summary: "Designs the logos, layouts, posters and screens that make a brand or message land.",
    scenario: "Imagine a rebrand pitch tomorrow. Three logo directions, one deck, and a client who said the word 'bold' nine times.",
    degree: "Bachelor's degree",
    pay: "$61,300/year",
    people: "259,000",
    openings: "20,900",
    homePay: "$47K",
    best: [["Washington", "$78K"], ["New York", "$76K"], ["California", "$74K"]],
    knowAbout: ["Typography, color and layout", "Branding and identity systems", "Print production and digital formats", "Design history and trends", "Accessibility basics"],
    goodAt: ["Visual problem solving", "Sketching ideas fast", "Taking feedback well", "Consistency across a system", "Presenting your work"],
    software: ["Adobe Illustrator", "Adobe Photoshop", "Adobe InDesign", "Figma", "Canva"],
    ladder: [
      ["Junior Designer", "$44K", "You produce layouts, resize assets and learn a brand's system inside out.", ["Produce layouts", "Resize assets", "Prep files for print", "Follow the brand guide"], ["Bachelor's degree or a strong portfolio", "Internships"]],
      ["Graphic Designer", "$61K", "You design campaigns, identities and packaging from brief to final files.", ["Design campaigns", "Build identities", "Present to clients", "Manage production"], ["2 to 4 years of work", "A portfolio of shipped projects"]],
      ["Senior Designer or Art Director", "$95K", "You lead design on major accounts and guide junior designers.", ["Lead accounts", "Set visual direction", "Mentor designers", "Pitch new work"], ["5+ years", "A recognized body of work"]],
    ],
    studies: ["Graphic Design", "Visual Communication", "Digital Arts"],
    where: [["190", "Certificate or associate's degree"], ["610", "Bachelor's degree"], ["90", "Master's degree"]],
    degreeNote: "Most designers hold a bachelor's in design; the portfolio decides the hire, and freelance is common.",
    experienceFirst: "No. You can start without it",
    dist: [1, 6, 14, 12, 60, 6, 1],
    payRange: ["$37,300", "$61,300", "$104,000"],
    outlook: "The job itself changes by about +5,000 by 2034. It is growing about as fast as most jobs; digital and motion work grows fastest.",
  },
  {
    title: "Interior Designer",
    summary: "Plans how the inside of a space looks, feels and works, from homes to hospitals.",
    scenario: "Imagine a new pediatric clinic. The floor plan has to calm a scared six year old, pass fire code, and stay under budget.",
    degree: "Bachelor's degree",
    pay: "$64,100/year",
    people: "96,000",
    openings: "8,500",
    homePay: "$49K",
    best: [["District of Columbia", "$84K"], ["New York", "$78K"], ["California", "$76K"]],
    knowAbout: ["Space planning and human scale", "Materials, finishes and furniture", "Building codes and accessibility", "Lighting and color", "Drafting and construction documents"],
    goodAt: ["Visualizing a room before it exists", "Listening to what clients need", "Drawing and modeling", "Managing vendors and budgets", "Attention to detail"],
    software: ["AutoCAD", "Revit", "SketchUp", "Adobe Photoshop", "Enscape"],
    ladder: [
      ["Design Assistant", "$45K", "You draft plans, pull samples and build presentation boards for the design team.", ["Draft plans", "Pull materials", "Build boards", "Track orders"], ["Bachelor's degree in interior design", "Internships"]],
      ["Interior Designer", "$64K", "You run projects from concept to installation and meet code on every one.", ["Design spaces", "Specify materials", "Coordinate contractors", "Present to clients"], ["NCIDQ certification", "3 to 5 years in a firm"]],
      ["Senior Designer or Principal", "$110K", "You lead a studio's projects and clients, or run your own firm.", ["Lead projects", "Win clients", "Mentor designers", "Run the business"], ["Years of built projects", "A recognized portfolio"]],
    ],
    studies: ["Interior Design", "Interior Architecture", "Architecture"],
    where: [["90", "Certificate or associate's degree"], ["190", "Bachelor's degree"], ["50", "Master's degree"]],
    degreeNote: "Most states expect a bachelor's from an accredited program plus the NCIDQ exam to use the title; decorators do not need either.",
    experienceFirst: "No. You can start without it",
    dist: [1, 5, 13, 10, 60, 10, 1],
    payRange: ["$38,600", "$64,100", "$107,000"],
    outlook: "The job itself changes by about +3,600 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Interpreter or Translator",
    summary: "Carries meaning between languages, live in a room or on the page.",
    scenario: "Imagine a hospital at 2 a.m. A family speaks only Spanish, the surgeon speaks only English, and every word you choose matters.",
    degree: "Bachelor's degree",
    pay: "$59,440/year",
    people: "76,000",
    openings: "7,500",
    homePay: "$47K",
    best: [["Virginia", "$82K"], ["District of Columbia", "$80K"], ["New Jersey", "$74K"]],
    knowAbout: ["Two or more languages at a native level", "Cultures and idioms", "Medical, legal or technical vocabulary", "Interpreting ethics and confidentiality", "Translation memory tools"],
    goodAt: ["Listening and speaking at once", "Precise writing", "Staying neutral", "Concentration for long sessions", "Research and terminology"],
    software: ["SDL Trados", "memoQ", "Zoom and remote interpreting platforms", "Microsoft Word", "Google Workspace"],
    ladder: [
      ["Community Interpreter or Junior Translator", "$40K", "You interpret for schools, clinics and agencies, or translate documents under review.", ["Interpret appointments", "Translate documents", "Build glossaries", "Learn the ethics"], ["Bachelor's degree or proven fluency", "A 40 hour interpreter training"]],
      ["Certified Interpreter or Translator", "$59K", "You work in courts, hospitals, conferences or for translation agencies with certification behind you.", ["Interpret in court or medicine", "Translate at speed", "Manage clients", "Keep certifications"], ["State court or CCHI/NBCMI medical certification", "ATA certification for translators"]],
      ["Conference Interpreter or Localization Lead", "$100K+", "You interpret simultaneously at international meetings or lead a company's translation program.", ["Simultaneous interpreting", "Lead translators", "Manage vendors", "Set quality standards"], ["Years of professional work", "A specialty and a network"]],
    ],
    studies: ["Foreign Languages and Literatures", "Translation and Interpretation", "Linguistics"],
    where: [["110", "Certificate, under a year"], ["50", "Associate's degree"], ["380", "Bachelor's degree"]],
    degreeNote: "Employers want fluency proven by certification; a bachelor's is the norm and a specialty like legal or medical raises pay.",
    experienceFirst: "No. You can start without it",
    dist: [2, 8, 14, 8, 48, 18, 2],
    payRange: ["$34,600", "$59,440", "$101,000"],
    outlook: "The job itself changes by about +1,500 by 2034. It is growing about as fast as most jobs; medical and legal interpreting grow fastest.",
  },
  {
    title: "Musician or Singer",
    summary: "Performs and records music, live and in the studio, solo or with a band, orchestra or choir.",
    scenario: "Imagine a 45 minute set at a festival side stage. Sound check ran late, the crowd is drifting, and your first chord has to pull them in.",
    degree: "No set degree; years of training, often a bachelor's in music",
    pay: "$39.14/hour",
    people: "180,000",
    openings: "21,500",
    homePay: "$24/hr",
    best: [["New York", "$52/hr"], ["California", "$48/hr"], ["Tennessee", "$41/hr"]],
    knowAbout: ["Music theory and ear training", "Your instrument or voice", "Recording, mixing and home studios", "The music business, royalties and streaming", "Performance and stagecraft"],
    goodAt: ["Practicing every day", "Playing with others", "Performing under pressure", "Promoting your own work", "Reading a room"],
    software: ["Ableton Live", "Logic Pro", "Pro Tools", "Spotify for Artists", "DistroKid"],
    ladder: [
      ["Student or Gigging Musician", "$20/hr", "You play weddings, churches, bars and school events and release your first tracks.", ["Play gigs", "Teach lessons", "Record demos", "Build a following"], ["Years of lessons or a music program", "A live set and a few recordings"]],
      ["Working Musician", "$39/hr", "You tour, do session work, play in an orchestra or a pit, or write for others.", ["Tour", "Session work", "Write and release", "Manage your business"], ["A reputation among players", "Union membership helps for orchestras and sessions"]],
      ["Headliner, Principal or Music Director", "$80/hr+", "You lead a band or an orchestra section, headline rooms, or direct the music for shows and worship.", ["Lead a group", "Headline", "Direct musicians", "Produce records"], ["Years of performing", "A name that sells tickets"]],
    ],
    studies: ["Music Performance", "Music Production and Technology", "Music Education"],
    where: [["120", "Certificate or conservatory program"], ["90", "Associate's degree"], ["600", "Bachelor's degree"]],
    degreeNote: "Bands and labels do not check diplomas; orchestras, teaching and music direction usually do. A music degree builds theory, ears and connections.",
    experienceFirst: "Yes. Years of playing first",
    dist: [2, 12, 20, 7, 44, 13, 2],
    payRange: ["$14/hr", "$39.14/hr", "$100/hr+"],
    payNote: "BLS reports musicians by the hour because most work is per gig or per session; many combine performing with teaching.",
    outlook: "The job itself changes by about +3,000 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Photographer",
    summary: "Makes the photos brands, families, news and artists actually use.",
    scenario: "Imagine a wedding at golden hour. Twelve minutes of perfect light, forty portraits on the list, and the groom's grandmother just arrived.",
    degree: "High school diploma; many hold a bachelor's in photography",
    pay: "$40,760/year",
    people: "130,000",
    openings: "13,600",
    homePay: "$34K",
    best: [["District of Columbia", "$70K"], ["New York", "$58K"], ["California", "$54K"]],
    knowAbout: ["Light, exposure and composition", "Cameras, lenses and lighting gear", "Editing and color", "Copyright and licensing", "Running a small business"],
    goodAt: ["Seeing a picture before you take it", "Directing people so they relax", "Fast, consistent editing", "Marketing yourself", "Working odd hours"],
    software: ["Adobe Lightroom", "Adobe Photoshop", "Capture One", "Pixieset", "Instagram"],
    ladder: [
      ["Photo Assistant or Second Shooter", "$30K", "You carry and set up gear, hold lights, shoot the second angle and learn how pros run a set.", ["Set up lights", "Second shoot", "Cull and back up files", "Learn the workflow"], ["High school diploma", "A portfolio and your own camera"]],
      ["Photographer", "$41K", "You shoot weddings, portraits, products, events or news on your own name.", ["Book and shoot clients", "Edit and deliver", "License images", "Run the business"], ["2 to 4 years assisting", "A strong, focused portfolio"]],
      ["Commercial or Staff Photographer", "$75K+", "You shoot campaigns for brands and agencies, or hold a staff job at a company, newsroom or university.", ["Shoot campaigns", "Lead crews", "Negotiate rates", "Direct retouching"], ["A commercial portfolio", "Agency or brand relationships"]],
    ],
    studies: ["Photography", "Commercial Photography", "Digital Arts"],
    where: [["150", "Certificate or associate's degree"], ["300", "Bachelor's degree"], ["40", "Master's degree"]],
    degreeNote: "No degree is required and most photographers are self employed; a photography program sharpens the eye and the business skills.",
    experienceFirst: "No. You can start without it",
    dist: [3, 20, 22, 9, 40, 5, 1],
    payRange: ["$28,000", "$40,760", "$90,000+"],
    payNote: "Salaried photographers earn the median; commercial and wedding photographers who run a business can earn far more or far less.",
    outlook: "The job itself changes by about +5,000 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Professional Athlete",
    summary: "Competes in a sport for a living, from minor leagues and pro tours to the top leagues.",
    scenario: "Imagine a tryout with 80 players and three roster spots. Everything you have trained for since you were eight comes down to two days.",
    degree: "No set degree; most come through college or academy programs",
    pay: "$70,280/year",
    people: "16,000",
    openings: "1,900",
    homePay: "$45K",
    best: [["California", "$120K"], ["New York", "$110K"], ["Florida", "$96K"]],
    knowAbout: ["Your sport's rules, tactics and film", "Training, recovery and nutrition", "Sports medicine basics", "Contracts, agents and unions", "Media and sponsorship"],
    goodAt: ["Elite conditioning", "Competing under pressure", "Coachability", "Discipline every day", "Handling injuries and setbacks"],
    software: ["Hudl", "WHOOP or Garmin", "TeamBuildr", "Instagram and TikTok", "Zoom"],
    ladder: [
      ["College or Academy Athlete", "Scholarship or NIL", "You compete for a school or academy, train year round and get seen by scouts.", ["Train and compete", "Study film", "Stay eligible", "Build your name"], ["Years in youth and high school sport", "Recruitment to a program"]],
      ["Professional Athlete", "$70K", "You sign with a minor league, a pro tour or a lower division and compete for a spot at the top.", ["Compete", "Travel", "Train and recover", "Work with agents and sponsors"], ["A draft pick, tryout or contract", "An agent"]],
      ["Top League Athlete", "$1M+", "You compete in a major league or on a top tour, with endorsements and a team around you.", ["Compete at the top", "Endorsements", "Community work", "Plan the next career"], ["Years of performance", "Staying healthy"]],
    ],
    studies: ["Kinesiology and Exercise Science", "Sport and Fitness Administration", "Communication"],
    where: [["60", "Certificate or associate's degree"], ["520", "Bachelor's degree"], ["40", "Master's degree"]],
    degreeNote: "No diploma is checked at the tryout. Most American pros come through college sports, so the degree comes with the path, and matters when the career ends.",
    experienceFirst: "Yes. Years of competing first",
    dist: [2, 20, 30, 8, 37, 2, 1],
    payRange: ["$27,900", "$70,280", "$1,000,000+"],
    payNote: "The median hides a huge spread: minor league players earn near the bottom, top league stars earn tens of millions. Careers are short, so the plan after sport matters.",
    outlook: "The job itself changes by about +1,500 by 2034. It is growing faster than most jobs, but spots at the top stay very few.",
  },
  {
    title: "Public Relations Specialist",
    summary: "Shapes what the public hears about a company, a person or a cause.",
    scenario: "Imagine a product recall hitting the news at 7 a.m. Reporters are calling, the CEO wants a statement, and you have an hour.",
    degree: "Bachelor's degree",
    pay: "$69,780/year",
    people: "292,000",
    openings: "26,700",
    homePay: "$55K",
    best: [["District of Columbia", "$98K"], ["New York", "$88K"], ["Virginia", "$84K"]],
    knowAbout: ["Writing for press and social", "How newsrooms and reporters work", "Brand and reputation", "Social media and analytics", "Crisis communication"],
    goodAt: ["Writing fast and clean", "Building relationships with journalists", "Staying calm in a crisis", "Turning complex news into plain words", "Juggling many clients or projects"],
    software: ["Cision", "Muck Rack", "Meltwater", "Google Workspace", "Sprout Social"],
    ladder: [
      ["PR Coordinator", "$48K", "You build media lists, draft releases, monitor coverage and support the account team.", ["Build media lists", "Draft releases", "Monitor coverage", "Run social posts"], ["Bachelor's degree", "Internships at an agency or in-house"]],
      ["Public Relations Specialist", "$70K", "You pitch stories, manage press for clients or a company, and handle the tough days.", ["Pitch reporters", "Write statements", "Run campaigns", "Report results"], ["2 to 4 years in PR", "A record of placements"]],
      ["PR Manager or Director", "$115K", "You lead a company's communications or an agency's accounts and its team.", ["Set strategy", "Lead the team", "Advise executives", "Own the crisis plan"], ["5+ years", "Trusted by leadership"]],
    ],
    studies: ["Public Relations", "Communication and Media Studies", "Journalism"],
    where: [["40", "Associate's degree"], ["480", "Bachelor's degree"], ["120", "Master's degree"]],
    degreeNote: "Nearly every PR hire holds a bachelor's in communication, PR or journalism, with internships and writing samples doing the rest.",
    experienceFirst: "No. You can start without it",
    dist: [1, 4, 8, 6, 65, 15, 1],
    payRange: ["$39,600", "$69,780", "$130,000+"],
    outlook: "The job itself changes by about +17,000 by 2034. It is growing faster than most jobs.",
  },
  {
    title: "Set Designer",
    summary: "Designs the physical world a play, film, show or exhibit lives in.",
    scenario: "Imagine a musical that jumps from a 1920s train station to a rooftop in eight seconds. Your set has to make that change in the dark.",
    degree: "Bachelor's degree; many hold an MFA",
    pay: "$61,900/year",
    people: "13,000",
    openings: "1,300",
    homePay: "$45K",
    best: [["New York", "$84K"], ["California", "$80K"], ["Nevada", "$70K"]],
    knowAbout: ["Drafting, scale and model making", "Materials, construction and scenic painting", "Theater history and style", "How scripts and shows are staged", "Budgets and shop capacity"],
    goodAt: ["Drawing and 3D modeling", "Reading a script for its world", "Collaborating with directors and shops", "Solving space and sightline problems", "Working to a build deadline"],
    software: ["Vectorworks", "SketchUp", "AutoCAD", "Adobe Photoshop", "Rhino"],
    ladder: [
      ["Scenic Assistant or Draftsperson", "$40K", "You draft the designer's plans, build models and track the shop's progress.", ["Draft plans", "Build models", "Source materials", "Attend rehearsals"], ["Bachelor's degree in theater design", "Assisting credits"]],
      ["Set Designer", "$62K", "You design sets for regional theater, TV, events and exhibits.", ["Design the set", "Present to directors", "Work with shops", "Attend tech"], ["A portfolio of produced designs", "MFA helps for larger houses"]],
      ["Production Designer", "$110K+", "You design whole films, series or Broadway productions and lead an art department.", ["Lead the art department", "Design the world", "Manage budgets", "Work with cinematographers"], ["Major credits", "Union membership (USA 829 or IATSE)"]],
    ],
    studies: ["Technical Theatre/Theatre Design and Technology", "Set Design", "Architecture"],
    where: [["30", "Associate's degree"], ["170", "Bachelor's degree"], ["60", "Master's degree"]],
    degreeNote: "Designers train in theater design programs and often an MFA; the portfolio and the directors who trust you decide the work.",
    experienceFirst: "No. You can start without it",
    dist: [1, 6, 12, 7, 50, 23, 1],
    payRange: ["$34,700", "$61,900", "$120,000+"],
    payNote: "Most work is by the production; film and Broadway rates sit well above regional theater.",
    outlook: "The job itself changes by about +500 by 2034 across set and exhibit designers. It is growing about as fast as most jobs.",
  },
  {
    title: "Visual Merchandiser",
    summary: "Designs store displays, windows and layouts that make people stop, look and buy.",
    scenario: "Imagine a flagship window on Fifth Avenue. New collection lands Monday, the window resets Sunday night, and the whole city walks past.",
    degree: "High school diploma; many hold an associate's or bachelor's in merchandising",
    pay: "$38,000/year",
    people: "108,000",
    openings: "13,000",
    homePay: "$33K",
    best: [["New York", "$52K"], ["California", "$47K"], ["Washington", "$46K"]],
    knowAbout: ["Retail design and store layout", "Color, lighting and props", "Fashion and product trends", "Brand standards and planograms", "Sales data and traffic"],
    goodAt: ["Styling and composition", "Building and installing displays", "Working overnight resets", "Reading what sells", "Coordinating with store teams"],
    software: ["Adobe Photoshop", "SketchUp", "Canva", "Microsoft Excel", "Planogram tools like JDA"],
    ladder: [
      ["Merchandising Associate", "$30K", "You set floors to the planogram, dress mannequins and install window changes.", ["Set the floor", "Dress mannequins", "Install windows", "Keep standards"], ["High school diploma", "Retail experience"]],
      ["Visual Merchandiser", "$38K", "You design and lead the displays for a store or a district.", ["Design displays", "Lead resets", "Train store teams", "Report on results"], ["2 to 3 years on the floor", "A portfolio of displays"]],
      ["Visual Merchandising Manager", "$70K", "You set visual direction for a region or a brand and manage the merchandisers.", ["Set direction", "Manage a team", "Plan seasonal launches", "Own the budget"], ["Years of retail visual work", "Associate's or bachelor's in merchandising"]],
    ],
    studies: ["Fashion Merchandising", "Visual Merchandising", "Retail Management"],
    where: [["70", "Certificate, under a year"], ["120", "Associate's degree"], ["150", "Bachelor's degree"]],
    degreeNote: "Stores promote from the floor; a merchandising program helps you move into corporate visual roles faster.",
    experienceFirst: "No. You can start without it",
    dist: [4, 30, 26, 12, 25, 2, 1],
    payRange: ["$28,300", "$38,000", "$62,000"],
    outlook: "The job itself changes by about +2,000 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Writer or Copywriter",
    summary: "Writes the words for ads, websites, brands, books and scripts.",
    scenario: "Imagine one line for a billboard. Seven words, a million drivers a day, and the client wants it funny but not too funny.",
    degree: "Bachelor's degree",
    pay: "$73,690/year",
    people: "152,000",
    openings: "15,000",
    homePay: "$52K",
    best: [["District of Columbia", "$110K"], ["California", "$96K"], ["New York", "$92K"]],
    knowAbout: ["Grammar, voice and style", "Storytelling and persuasion", "Brands, audiences and marketing", "SEO and web content", "Editing and research"],
    goodAt: ["Writing clearly and fast", "Finding the one right word", "Taking edits without ego", "Hitting deadlines", "Switching voices for different brands"],
    software: ["Google Docs", "Microsoft Word", "Grammarly", "Figma", "Notion"],
    ladder: [
      ["Junior Copywriter or Content Writer", "$48K", "You write product descriptions, social posts, emails and blog articles under an editor.", ["Write web copy", "Draft social posts", "Research topics", "Take edits"], ["Bachelor's degree or a strong portfolio", "Internships or freelance clips"]],
      ["Copywriter or Writer", "$74K", "You own campaigns, brand voice or long form work for clients, agencies or publishers.", ["Write campaigns", "Shape brand voice", "Pitch concepts", "Edit others"], ["2 to 4 years of published work", "A portfolio that shows range"]],
      ["Senior Copywriter, Creative Director or Author", "$120K+", "You lead the words for an agency or brand, or publish and sell your own books and scripts.", ["Lead creative", "Mentor writers", "Pitch clients", "Publish"], ["Years of work people remember", "A voice of your own"]],
    ],
    studies: ["English Language and Literature", "Creative Writing", "Advertising"],
    where: [["50", "Associate's degree"], ["560", "Bachelor's degree"], ["220", "Master's degree"]],
    degreeNote: "Most writers hold a bachelor's in English, journalism or communication; clips and a portfolio get the job, and many work freelance.",
    experienceFirst: "No. You can start without it",
    dist: [1, 5, 10, 6, 60, 16, 2],
    payRange: ["$40,900", "$73,690", "$140,000+"],
    outlook: "The job itself changes by about +7,000 by 2034. It is growing about as fast as most jobs; AI changes the work more than the count.",
  },
  {
    title: "Art Director",
    summary: "Decides how a campaign, magazine, film or product line looks, then leads the team that makes it.",
    scenario: "Imagine a sneaker launch. Photographer, stylist, two designers and a set builder all waiting for you to say which direction is the one.",
    degree: "Bachelor's degree",
    pay: "$111,040/year",
    people: "145,000",
    openings: "12,500",
    homePay: "$78K",
    best: [["New York", "$150K"], ["California", "$142K"], ["Washington", "$130K"]],
    knowAbout: ["Design, photography and typography", "Brand strategy and advertising", "Production, budgets and timelines", "Film, print and digital formats", "Managing creative people"],
    goodAt: ["Seeing the big picture", "Giving clear creative direction", "Presenting and selling ideas", "Deciding fast", "Bringing out the best in a team"],
    software: ["Adobe Creative Cloud", "Figma", "Keynote", "Frame.io", "Milanote"],
    ladder: [
      ["Designer", "$61K", "You design the pieces of campaigns and learn how a creative team ships work.", ["Design layouts", "Build decks", "Prep files", "Support shoots"], ["Bachelor's degree in design or advertising", "A strong portfolio"]],
      ["Art Director", "$111K", "You own the look of campaigns and productions and direct designers, photographers and crews.", ["Set the visual direction", "Direct shoots", "Lead designers", "Present to clients"], ["5+ years designing", "A body of directed work"]],
      ["Creative Director", "$175K+", "You lead the whole creative output of an agency, brand or publication.", ["Lead creative strategy", "Run the department", "Win business", "Mentor directors"], ["Years of campaigns", "Industry recognition"]],
    ],
    studies: ["Graphic Design", "Advertising", "Fine and Studio Arts"],
    where: [["40", "Associate's degree"], ["520", "Bachelor's degree"], ["110", "Master's degree"]],
    degreeNote: "Art directors are designers first; almost all hold a bachelor's in design or a related field and rise through years of work.",
    experienceFirst: "Yes. Years as a designer first",
    dist: [1, 4, 9, 7, 66, 12, 1],
    payRange: ["$63,200", "$111,040", "$200,000+"],
    outlook: "The job itself changes by about +7,000 by 2034. It is growing about as fast as most jobs.",
  },
  {
    title: "Film Director",
    summary: "Leads a film or series from script to screen and makes every creative call on set.",
    scenario: "Imagine day 14 of a 30 day shoot. You are a day behind, the lead is sick, and the sunset scene only works today.",
    degree: "Bachelor's degree",
    pay: "$85,320/year",
    people: "178,000",
    openings: "16,600",
    homePay: "$62K",
    best: [["California", "$126K"], ["New York", "$118K"], ["Georgia", "$92K"]],
    knowAbout: ["Story, scripts and performance", "Cameras, lenses and coverage", "Editing and post production", "How a set is organized", "Budgets, schedules and financing"],
    goodAt: ["Communicating a vision", "Working with actors", "Making decisions under pressure", "Collaborating with crews", "Stamina for long shoots"],
    software: ["Final Draft", "Movie Magic Scheduling", "StudioBinder", "Adobe Premiere Pro", "Shot Designer"],
    ladder: [
      ["Production Assistant or Assistant Director", "$40K", "You run the set's logistics, learn every department, and make your own short films.", ["Run set logistics", "Assist the director", "Make shorts", "Learn departments"], ["Film school or a bachelor's degree", "A short film reel"]],
      ["Director", "$85K", "You direct commercials, music videos, episodes or independent features.", ["Direct shoots", "Work with actors", "Guide the edit", "Pitch projects"], ["Directed work that has been seen", "An agent or manager"]],
      ["Feature or Showrunner Director", "$200K+", "You direct studio features or run a series and choose your projects.", ["Lead a production", "Develop projects", "Hire department heads", "Represent the film"], ["Festival or box office track record", "DGA membership"]],
    ],
    studies: ["Cinematography and Film/Video Production", "Film/Cinema/Media Studies", "Drama and Dramatics/Theatre Arts"],
    where: [["90", "Certificate or associate's degree"], ["380", "Bachelor's degree"], ["70", "Master's degree"]],
    degreeNote: "Nobody checks a diploma on set, but most directors hold a bachelor's, often from film school, where the first crews and reels come from. BLS groups the job with producers and directors.",
    experienceFirst: "Yes. Years on sets first",
    dist: [1, 5, 12, 7, 60, 14, 1],
    payRange: ["$42,300", "$85,320", "$200,000+"],
    payNote: "Figures follow the BLS producers and directors occupation; a few feature directors earn millions, most work project to project.",
    outlook: "The job itself changes by about +14,000 by 2034 across producers and directors. It is growing faster than most jobs.",
  },
  {
    title: "Journalist",
    summary: "Finds out what is happening, checks it, and tells the public clearly and fairly.",
    scenario: "Imagine a tip at 4 p.m. that the city council buried a report. Two sources, one deadline at nine, and it has to be right.",
    degree: "Bachelor's degree",
    pay: "$60,280/year",
    people: "47,000",
    openings: "4,600",
    homePay: "$42K",
    best: [["District of Columbia", "$110K"], ["New York", "$92K"], ["California", "$76K"]],
    knowAbout: ["Reporting, interviewing and verification", "Writing for print, web, audio and video", "Media law and ethics", "Public records and data", "How government and business work"],
    goodAt: ["Asking the hard question", "Writing fast under deadline", "Curiosity and persistence", "Talking to anyone", "Getting it right"],
    software: ["Google Docs", "Otter.ai", "Adobe Audition", "Adobe Premiere Pro", "X and social platforms"],
    ladder: [
      ["Reporter or Producer", "$40K", "You cover a beat for a local outlet, file daily and learn to work sources.", ["Cover a beat", "File daily", "Shoot and edit", "Build sources"], ["Bachelor's degree in journalism or a related field", "Student newsroom clips"]],
      ["Journalist", "$60K", "You report for a regional or national outlet, break stories and lead coverage on your beat.", ["Break stories", "Investigate", "Appear on air or podcasts", "Mentor interns"], ["3 to 5 years of clips", "A beat you own"]],
      ["Senior Correspondent or Editor", "$110K+", "You lead a desk, anchor coverage or write the stories that set the agenda.", ["Lead a desk", "Anchor or correspond", "Edit reporters", "Set coverage"], ["A national body of work", "Awards or a recognized voice"]],
    ],
    studies: ["Journalism", "Communication and Media Studies", "Political Science"],
    where: [["30", "Associate's degree"], ["420", "Bachelor's degree"], ["110", "Master's degree"]],
    degreeNote: "Newsrooms expect a bachelor's and clips; a journalism degree gives you both, but any major plus a student newsroom works.",
    experienceFirst: "No. You can start without it",
    dist: [1, 3, 7, 5, 68, 15, 1],
    payRange: ["$32,700", "$60,280", "$140,000+"],
    outlook: "The job itself changes by about -1,500 by 2034 as local outlets shrink. It is declining slightly, but digital and broadcast outlets keep hiring.",
  },
];

export const ARTS_PROFILES: Record<string, CareerProfile> = Object.fromEntries(LIST.map((c) => { const p = build(c); return [p.slug, p]; }));
