import type { Level } from "./types";

// LEVEL 3 ASSOCIATE, from DreamAri_IB_Levels1-3_Handoff.xlsx, tab "Level 3
// Associate". Unlike Levels 1 and 2, that tab's content columns already carry
// PRODUCTION copy, so the scores here are the sheet's own: +5 / +2 / -3 / -6,
// ten scored beats at 10% each.
//
// The sheet's 46 screens become 30 beats because its sub-screens are children
// of one interaction: L3-12a..12f are the six items of one Two-Bucket Sort,
// L3-14a..14e the five questions of one rapid set, L3-24a..24e the five items of
// the second sort. Same collapse Levels 1 and 2 use for their rapid sets.
//
// Production changes from the sheet that ARE applied here:
// - Onboarding is Christina's, not a fourth unnamed HR character (D11). She is
//   the VP reviewing your work now, so she is the one who says what the job is.
//   Level 2 made the same move.
// - Narrative cards do NOT advance the progress bar (D22). The sheet flags four
//   screens that moved it with no choice on them.
// - Marcus's promotion to Executive Director is SAID on screen (D26) rather than
//   appearing only in a hierarchy chip nobody reads.
// - The rival is Silverman Sacks and the client Maison Laurent throughout (D01,
//   D23). Rank rows arrive shuffled, never pre-solved (D31).
// - Second sort's buttons read Do First / Can Wait, not the pitch labels the
//   build reused on a beat about ordering work (D32).
// - "Mandate" is gone; the email says what it means (D30).
// - Setups are the speaker's own words. The sheet writes them as "Christina (VP)
//   asks ..." and then repeats the instruction in the question column; with a
//   portrait on screen, saying it twice is just more to read.
//
// Left out deliberately:
// - L3-30, the Vice President offer card. Its salary and hours are "TO BE
//   RESEARCHED" in the sheet (D36, D37), and Levels 1 and 2 both open with the
//   offer for the level you are about to play. It belongs at the top of Level 4
//   with real numbers, not invented ones.
// - L3-29's three-way outcome screen is the ending sequence this engine already
//   renders from `endings`, so it is not a beat.

const ART = "/images/play/ib";

export const IB_LEVEL_3: Level = {
  id: "ib-l3",
  n: 3,
  role: "Associate",
  title: "Your First Associate Deal",
  blurb: "Cobalt is close to winning Maison Laurent. This time you lead the Analysts.",
  cover: `${ART}/l3-17.webp`,
  mood: "day",
  cast: {
    Christina: `${ART}/face-christina.webp`,
    Marcus: `${ART}/face-marcus.webp`,
    Lamisa: `${ART}/face-lamisa.webp`,
  },
  beats: [
    {
      kind: "card",
      variant: "step",
      id: "L3-01",
      art: `${ART}/l3-01.webp`,
      artAlt: "Christina at a desk, city windows behind her.",
      speaker: "Christina",
      step: { at: 1, of: 5 },
      setup: '"Analysts prove they can do the work. Associates prove they can guide others."',
      title: "Review Analyst work.",
      body: "Check models, slides and numbers before senior leaders see them.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "step",
      id: "L3-02",
      speaker: "Christina",
      step: { at: 2, of: 5 },
      title: "Manage deadlines.",
      body: "The team should always know what is due and when.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "step",
      id: "L3-03",
      speaker: "Christina",
      step: { at: 3, of: 5 },
      title: "Guide Analysts.",
      body: "Help them improve without doing it all for them.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "step",
      id: "L3-04",
      speaker: "Christina",
      step: { at: 4, of: 5 },
      title: "Prepare for clients.",
      body: "Turn rough work into materials a client can read.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "step",
      id: "L3-05",
      speaker: "Christina",
      step: { at: 5, of: 5 },
      title: "Speak up with senior leaders.",
      body: "Say what you are thinking so they can trust your judgement.",
      cta: "Done",
    },
    {
      kind: "card",
      variant: "character",
      id: "L3-06",
      art: `${ART}/l3-06.webp`,
      artAlt: "Christina on the analyst floor holding a notebook, glass offices behind her.",
      speaker: "Christina",
      setup: '"I made VP. I lead the team and the client prep now."',
      title: "Christina · Vice President",
      note: "Your team levelled up too.",
      cta: "Next",
    },
    {
      kind: "card",
      variant: "character",
      id: "L3-07",
      art: `${ART}/l3-07.webp`,
      artAlt: "Lamisa seated in a corner office, hands folded, city windows behind her.",
      speaker: "Lamisa",
      setup: '"Managing Director. The client relationship is mine, which means the work is mine too."',
      title: "Lamisa · Managing Director",
      note: "You: Associate. Christina: VP. Marcus: Executive Director. Lamisa: MD.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-08",
      art: `${ART}/l3-08.webp`,
      artAlt: "Marcus in a navy suit outside a glass boardroom, city skyline behind him.",
      speaker: "Marcus",
      setup: '"I moved up to Executive Director. Christina has VP. You get the Analysts and the Interns."',
      title: "Your first Associate deal.",
      body: "Cobalt is close to winning Maison Laurent.",
      note: "Can you lead like an Associate?",
      cta: "Start Level 3",
    },
    {
      kind: "rank",
      id: "L3-09",
      speaker: "Dreamy",
      pose: "glasses",
      progress: 0.1,
      setup: "You are an Associate now. Others moved up too.",
      question: "Put the six roles in order, lowest to highest.",
      order: ["Intern", "Analyst", "Associate", "Vice President", "Executive Director", "Managing Director"],
      whenRight: "Right. Knowing the ladder tells you whose sign-off a piece of work needs.",
      whenWrong: "Close. Work moves up one rung at a time, so the order decides who sees it when.",
      feedback: "You are third from the bottom.",
      feedbackCta: "Continue",
      skills: ["Systems Thinking", "Active Learning"],
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-10",
      art: `${ART}/l3-14.webp`,
      artAlt: "The deal team around laptops at night, a wall screen showing the next day's meetings.",
      mood: "crunch",
      speaker: "Dreamy",
      pose: "alert",
      setup: "Crunch time",
      title: "Three days until the Maison Laurent meeting.",
      body: "Lead the Analysts. Follow the seniors closely. Speak up to move up.",
      cta: "Start final prep",
    },
    {
      kind: "pick",
      id: "L3-11",
      mood: "crunch",
      speaker: "Dreamy",
      pose: "curious",
      progress: 0.2,
      timer: 60,
      setup: "You manage two Analysts. Silverman Sacks is chasing the same deal.",
      question: "Pick the 2 tasks that give Cobalt the best chance.",
      pick: 2,
      cards: [
        { label: "Bring sharper market insight", role: "pick" },
        { label: "Point out the risks in Silverman Sacks' plan", role: "pick" },
        { label: "Offer to cut Cobalt's fees", role: "leave" },
        { label: "Get inside information on Silverman Sacks", role: "harmful" },
        { label: "Make the numbers look bigger", role: "harmful" },
      ],
      whenRight: "Right. Better insight and a clear read of the rival are what a client pays a bank for.",
      whenWrong: "Cutting fees buys the work instead of earning it. Cobalt wins on thinking, not price.",
      whenHarmful: "Stolen information and inflated numbers end careers. Nothing won that way survives.",
      feedback: "Insight and a clear read of the rival win deals. Cutting fees and cheating do not.",
      feedbackCta: "Continue",
      skills: ["Decision-Making", "Critical Thinking"],
    },
    {
      kind: "bucket",
      id: "L3-12",
      mood: "crunch",
      speaker: "Christina",
      progress: 0.3,
      setup: '"Which of these belong in the final pitch?"',
      question: "Sort each idea.",
      buckets: ["Helps Cobalt win", "Weak pitch"],
      items: [
        { label: "Show why Asia growth matters", into: 0 },
        { label: "Use general fashion trends", into: 1 },
        { label: "Prove Cobalt understands luxury customers", into: 0 },
        { label: "Focus only on slide design", into: 1 },
        { label: "Explain risks in Silverman Sacks' plan", into: 0 },
        { label: "Promise results without evidence", into: 1 },
      ],
      whenRight: "Right. A pitch is built from what the client cares about, not from what was easy to make.",
      whenWrong: "Close. Look for the ideas that answer why Cobalt, not the ones describing what Cobalt did.",
      feedback: "Strong ideas prove you understand the client. Weak ones talk about effort, design or promises.",
      feedbackCta: "Continue",
      skills: ["Persuasive Communication", "Critical Thinking"],
    },
    {
      kind: "choice",
      layout: "document",
      doc: "Maison Laurent • Slide 4",
      id: "L3-13",
      mood: "crunch",
      speaker: "Christina",
      progress: 0.4,
      timer: 60,
      setup: '"Asia revenue grew 18 percent, more than any other market. Title the slide."',
      question: "Pick the clearest headline.",
      choices: [
        { id: "a", label: "Asia Is Driving Maison Laurent's Growth", tier: "best", why: "Right. The headline says what the number means, so the reader gets it instantly." },
        { id: "b", label: "Revenue Update", tier: "acceptable", why: "True but empty. It names a topic and tells the reader nothing." },
        { id: "c", label: "Maison Laurent Has Many Stores", tier: "wrong", why: "Not what the slide shows. The number is about growth, not store count." },
        { id: "d", label: "Competitors Are Also Growing", tier: "wrong", why: "This is about other companies. The slide is about your client." },
      ],
      feedback: "A headline should say what the number means.",
      feedbackCta: "Continue",
      skills: ["Written Communication", "Persuasive Communication"],
    },
    {
      kind: "rapid",
      id: "L3-14",
      art: `${ART}/l3-16.webp`,
      artAlt: "The deal team at night, a wall screen showing the 9:00 AM prep and 12:00 PM client meetings.",
      mood: "crunch",
      speaker: "Christina",
      progress: 0.5,
      timer: 120,
      setup: '"Last night before the pitch. Can you take the Analysts through it?"',
      question: "Five calls, one clock.",
      items: [
        {
          question: "What do you confirm before the 9:00 AM prep?",
          options: [
            { label: "Who presents each section", correct: false, why: "Useful, but the deck has to be right before anyone can present it." },
            { label: "The final deck version", correct: true, why: "Right. Everyone reads from the same deck. It has to be the final one." },
            { label: "The meeting room booking", correct: false, why: "Admin. Worth doing, but not the thing that ruins a meeting." },
            { label: "New slide colours", correct: false, why: "Colours are the last thing to change and the first thing to drop." },
          ],
        },
        {
          question: "An Analyst is nervous about presenting numbers. What do you do?",
          options: [
            { label: "Present the numbers yourself", correct: false, why: "Quicker today, but they learn nothing and are nervous again tomorrow." },
            { label: "Tell them they will be fine", correct: false, why: "Kind, but it is not preparation. Confidence comes from knowing the numbers." },
            { label: "Review the numbers with them", correct: true, why: "Right. Going through them together is how an Associate builds a team." },
            { label: "Replace every slide", correct: false, why: "The slides are not the problem. Rewriting them wastes the night." },
          ],
        },
        {
          question: "What will senior leaders ask first?",
          options: [
            { label: "What changed overnight?", correct: true, why: "Right. They read it yesterday. They want to know what is different now." },
            { label: "How long will the meeting run?", correct: false, why: "They will ask, but later. First they need to know the work is current." },
            { label: "Who is presenting each part?", correct: false, why: "Fair question, and they can already see it from the deck." },
            { label: "What order are the slides in?", correct: false, why: "Order matters, but not before they know what actually changed." },
          ],
        },
        {
          question: "Lamisa asks for proof. What is ready?",
          options: [
            { label: "A confident summary", correct: false, why: "Confidence is not proof. She is asking where the number came from." },
            { label: "The source data", correct: true, why: "Right. Proof means the original data, so anyone can check it themselves." },
            { label: "A backup slide", correct: false, why: "A backup slide repeats your claim. It does not show where it came from." },
            { label: "A longer intro", correct: false, why: "A longer intro delays the answer she actually asked for." },
          ],
        },
        {
          question: "The client meeting is close. What matters most?",
          options: [
            { label: "A clear story", correct: true, why: "Right. The client remembers one clear story, not forty slides." },
            { label: "A longer deck", correct: false, why: "Longer is not stronger. More pages means less of it gets read." },
            { label: "More data on every slide", correct: false, why: "More data buries the point. The client wants the finding." },
            { label: "A confident opening", correct: false, why: "A good opening helps, but only if the story behind it holds up." },
          ],
        },
      ],
      whenPass: "Right. Four of five means the team can follow you through a long night.",
      whenFail: "You needed four of five. These calls come up every hour on a live deal.",
      feedback: "Four of five to pass. The counter shows how many you have as you go.",
      feedbackCta: "Continue",
      skills: ["Teaching & Guiding Others", "Time Management"],
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-15",
      art: `${ART}/l3-17.webp`,
      artAlt: "Christina, Marcus and Lamisa at a boardroom table, the player's hands in the foreground.",
      speaker: "Marcus",
      setup: '"Almost nine. Lamisa is already in. Jordan is in there sounding confident."',
      title: "Pitch day morning.",
      cta: "Enter the meeting",
    },
    {
      kind: "pick",
      id: "L3-16",
      speaker: "Lamisa",
      progress: 0.6,
      setup: '"What is the client actually worried about?" Jordan guesses: "Profit margins?"',
      question: "Pick 3 ways to correct Jordan respectfully.",
      pick: 3,
      cards: [
        { label: "Credit Jordan's point first", role: "pick" },
        { label: "Refocus the room on Asia brand strength", role: "pick" },
        { label: "Back it with the 18 percent growth", role: "pick" },
        { label: "Say Jordan is wrong, then answer", role: "leave" },
        { label: "Message Jordan about it later", role: "leave" },
      ],
      whenRight: "Right. Credit him, move the room to the real answer, then back it with a number.",
      whenWrong: "Correcting him flatly wins the point and loses the room. Waiting leaves Lamisa with the wrong answer.",
      feedback: "Correcting a peer in front of leaders works when you credit them first, then bring evidence.",
      feedbackCta: "Continue",
      skills: ["Social Awareness", "Persuasive Communication"],
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-17",
      speaker: "Dreamy",
      pose: "idea",
      setup: "Pitch day",
      title: "Crunch time is over.",
      body: "You are in the room with VPs, an Executive Director and the MD.",
      cta: "Continue",
    },
    {
      kind: "pick",
      id: "L3-18",
      progress: 0.7,
      timer: 60,
      speaker: "Lamisa",
      setup: '"They asked me why they should choose Cobalt. Give me three reasons."',
      question: "Pick 3 points.",
      pick: 3,
      cards: [
        { label: "We understand Asia expansion", role: "pick" },
        { label: "We know luxury customers", role: "pick" },
        { label: "We found risks in Silverman Sacks' plan", role: "pick" },
        { label: "We have the largest team on this", role: "leave" },
        { label: "Our materials are the most polished", role: "leave" },
        { label: "We can promise instant results", role: "harmful" },
      ],
      whenRight: "Right. Every one of these is about the client's business, not about Cobalt.",
      whenWrong: "Team size and polish are about you. The client asked what they get.",
      whenHarmful: "Promising results you cannot show is the fastest way to lose a client for good.",
      feedback: "The strongest answers are about the client. Effort, polish and promises are about you.",
      feedbackCta: "Continue",
      skills: ["Persuasive Communication", "Active Listening"],
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-19",
      art: `${ART}/l3-19.webp`,
      artAlt: "Lamisa stopping the player in a glass hallway, a pitch book in the player's hands.",
      speaker: "Lamisa",
      setup: '"You led the Analysts, worked well with the Associates, and stayed on Maison Laurent the whole way."',
      title: "After the pitch.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-20",
      art: `${ART}/l3-20.webp`,
      artAlt: "Christina in the same hallway giving the player a thumbs up.",
      speaker: "Christina",
      setup: '"You got Lamisa\'s attention. That is a big deal. I am proud of you."',
      title: "Christina catches you after.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-21",
      speaker: "Dreamy",
      pose: "nervous",
      setup: "Deal decision",
      title: "Maison Laurent is reviewing the pitch.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "offer",
      id: "L3-22",
      speaker: "Lamisa",
      pose: "party",
      setup: '"We won it. Now we help them raise $30B for Asia."',
      title: "Deal secured.",
      facts: [
        { label: "Client", value: "Maison Laurent" },
        { label: "Raise", value: "$30B for Asia" },
        { label: "Your role", value: "Associate on the deal" },
      ],
      cta: "Continue",
    },
    {
      kind: "rank",
      id: "L3-23",
      speaker: "Christina",
      progress: 0.8,
      setup: '"You have an Analyst and an Intern on the Asia work. Show me how you start."',
      question: "Rank your first four moves, first to last.",
      order: ["Clarify the goal and deadline", "Assign work by skill level", "Set a check-in time", "Review client materials"],
      whenRight: "Right. People need the goal and the date before anyone can be handed the right piece.",
      whenWrong: "Close. Assigning work before naming the goal means someone builds the wrong thing well.",
      feedback: "Goal, then who does what, then when you check in. Reviewing comes after there is work.",
      feedbackCta: "Continue",
      skills: ["Leadership & Team Management", "Time Management"],
    },
    {
      kind: "bucket",
      id: "L3-24",
      speaker: "Christina",
      progress: 0.9,
      setup: '"The deal is won. What does the team do first?"',
      question: "Sort each task.",
      buckets: ["Do first", "Can wait"],
      items: [
        { label: "Fix the revenue number the client already saw", into: 0 },
        { label: "Update the team's internal project tracker", into: 1 },
        { label: "Send the corrected deck to Maison Laurent today", into: 0 },
        { label: "Redesign all charts to a new colour palette", into: 1 },
        { label: "Call the client to explain the correction", into: 0 },
      ],
      whenRight: "Right. Anything the client has already seen, and anything with a deadline, comes first.",
      whenWrong: "Close. Internal tidying and design can always wait. A client-facing error cannot.",
      feedback: "Fix what the client saw, tell them, hit the deadline. Tidying and design wait.",
      feedbackCta: "Continue",
      skills: ["Decision-Making", "Leadership & Team Management"],
    },
    {
      kind: "choice",
      layout: "tiles",
      id: "L3-25",
      speaker: "Christina",
      progress: 1,
      setup: '"Send Maison Laurent a short update. Professional, clear, confident."',
      question: "Pick the opening line.",
      choices: [
        {
          id: "a",
          label: "We are excited to begin and will share the timeline by Friday",
          tier: "best",
          why: "Right. It names something specific and gives the client a date to expect.",
        },
        {
          id: "b",
          label: "Our team has begun the analysis and will coordinate with yours",
          tier: "best",
          why: "Right. Specific about what is happening and who it involves.",
        },
        {
          id: "c",
          label: "Just checking whether you got our last message",
          tier: "wrong",
          why: "Polite, and the client learns no new fact from it.",
        },
        {
          id: "d",
          label: "Let us know if you need anything else from us",
          tier: "wrong",
          why: "Sounds helpful, says nothing. It puts the next move on them.",
        },
      ],
      feedback: "A strong update names what is happening and when. Filler gives the client nothing to hold.",
      feedbackCta: "Continue",
      skills: ["Written Communication", "Helping & Supporting Others"],
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-26",
      speaker: "Dreamy",
      pose: "curious",
      title: "The corrected numbers are with the client.",
      body: "Now the team waits.",
      cta: "Continue",
    },
    {
      kind: "card",
      variant: "chapter",
      id: "L3-27",
      speaker: "Dreamy",
      pose: "party",
      setup: "Maison Laurent signs off",
      title: "The deal stays on track.",
      cta: "Begin final review",
    },
    {
      kind: "review",
      id: "L3-28",
      speaker: "Dreamy",
      pose: "glasses",
      setup: "Final review",
      title: "Cobalt Capital is reviewing your Associate year.",
      body: "Your reputation will decide if you are promoted.",
    },
  ],
  endings: [
    {
      min: 85,
      band: "Trusted",
      headline: "Promoted to Vice President",
      message: "Lamisa put your name forward herself. The Analysts you led asked to stay with you.",
      subline: "Next up: leading the deal, and the client.",
      primary: "Claim Your Reward",
      advances: true,
    },
    {
      min: 60,
      band: "Respected",
      headline: "Another Year as Associate",
      message:
        'No promotion this cycle. Christina is direct: "You did the work. VPs are trusted with the client, and Lamisa does not know your thinking yet."',
      subline: "You will play the Associate year again, from the beginning.",
      primary: "Play the Associate year again",
      advances: false,
    },
    {
      min: 0,
      band: "Cautious",
      headline: "Performance Review",
      message:
        'Cobalt is putting your Associate year under review. Christina: "Leading is different from doing. It caught you. It catches most people. Go again."',
      subline: "You will play the Associate year again, from the beginning.",
      primary: "Play the Associate year again",
      advances: false,
    },
  ],
};
