import type { ComponentPropsWithoutRef } from "react";
import Link from "next/link";
import { Bricolage_Grotesque } from "next/font/google";

// Phase 3 of the design-system alignment: this component now IS the design system's
// CTA (Figma component 2261:12200), rebuilt from the live file's exact state matrix
// and consuming the --component-cta-* tokens generated by the DTCG pipeline
// (design-tokens/components.tokens.json, component.cta group). It had ZERO call
// sites when rebuilt (its old landing-page consumers were deleted in the marketing
// rebuild), so this replacement changes nothing visually until screens adopt it.
//
// The state scheme is NOT the old blue-primary one: the design system's Primary
// CTA is the light foreground surface with dark text, Hover goes deep glass,
// PRESSED is the blue, and Disabled is the whole control at 40% opacity. Secondary
// is the bordered faint-glass family. The destructive variant is intentionally
// absent - still being finalized on the Figma side; check the file before adding.
//
// Bricolage Grotesque loads here via next/font (self-hosted, latin subset, only
// the 600 weight the CTA uses) - fonts load with their adopting component, not
// up-front in the layout, per the alignment plan's page-weight rule.
const ctaFont = Bricolage_Grotesque({ subsets: ["latin"], weight: "600" });

type Variant = "primary" | "secondary";
type Size = "default" | "large";

const VARIANT_CLASSES: Record<Variant, string> = {
  primary: [
    "bg-[var(--component-cta-primary-background)] text-[var(--component-cta-primary-text)]",
    "hover:bg-[var(--component-cta-primary-hover-background)] hover:text-[var(--component-cta-primary-hover-text)]",
    "active:bg-[var(--component-cta-primary-pressed-background)] active:text-[var(--component-cta-primary-pressed-text)]",
    "disabled:pointer-events-none disabled:opacity-[var(--component-cta-primary-disabled-opacity)]",
  ].join(" "),
  secondary: [
    "border border-[var(--component-cta-secondary-border)]",
    "bg-[var(--component-cta-secondary-background)] text-[var(--component-cta-secondary-text)]",
    "hover:bg-[var(--component-cta-secondary-hover-background)] hover:text-[var(--component-cta-secondary-hover-text)]",
    "active:bg-[var(--component-cta-secondary-pressed-background)] active:text-[var(--component-cta-secondary-pressed-text)]",
    // Secondary/Disabled dims CONTENT only (surface stays), per the live spec.
    "disabled:pointer-events-none disabled:[&>span]:opacity-[var(--component-cta-secondary-disabled-content-opacity)]",
  ].join(" "),
};

const SIZE_CLASSES: Record<Size, string> = {
  default:
    "px-[var(--component-cta-size-default-padding-x)] py-[var(--component-cta-size-default-padding-y)] rounded-[var(--component-cta-size-default-radius)]",
  large:
    "px-[var(--component-cta-size-large-padding-x)] py-[var(--component-cta-size-large-padding-y)] rounded-[var(--component-cta-size-large-radius)]",
};

type ButtonProps = {
  variant?: Variant;
  size?: Size;
  href?: string;
} & ComponentPropsWithoutRef<"button">;

export function Button({ variant = "primary", size = "default", href, className = "", children, ...props }: ButtonProps) {
  // 16px/22px semibold mirrors component.cta.typography (UI/Body) - the typography
  // composite validates in the pipeline but isn't emitted as CSS custom properties,
  // so the values are stated here with the token as their source of truth.
  const classes = `${ctaFont.className} inline-flex items-center justify-center gap-[var(--component-cta-gap)] text-[16px] leading-[22px] font-semibold transition-colors duration-150 ${VARIANT_CLASSES[variant]} ${SIZE_CLASSES[size]} ${className}`;

  if (href) {
    return (
      <Link href={href} className={classes}>
        <span className="inline-flex items-center gap-[var(--component-cta-gap)]">{children}</span>
      </Link>
    );
  }

  return (
    <button className={classes} {...props}>
      <span className="inline-flex items-center gap-[var(--component-cta-gap)]">{children}</span>
    </button>
  );
}
